/** Additional open-source families shared by the picker and asset bundler. */
export const FONT_LIBRARY_ADDITIONS = [
  {
    id: "alex-brush",
    family: "Alex Brush",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "bilbo-swash-caps",
    family: "Bilbo Swash Caps",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "cookie",
    family: "Cookie",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "euphoria-script",
    family: "Euphoria Script",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "herr-von-muellerhoff",
    family: "Herr Von Muellerhoff",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "indie-flower",
    family: "Indie Flower",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "italianno",
    family: "Italianno",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "kalam",
    family: "Kalam",
    category: "Script",
    bodySuitable: false,
    weights: "400;700",
  },
  {
    id: "la-belle-aurore",
    family: "La Belle Aurore",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "marck-script",
    family: "Marck Script",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "meie-script",
    family: "Meie Script",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "meddon",
    family: "Meddon",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "monsieur-la-doulaise",
    family: "Monsieur La Doulaise",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "mr-de-haviland",
    family: "Mr De Haviland",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "mrs-saint-delafield",
    family: "Mrs Saint Delafield",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "my-soul",
    family: "My Soul",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "niconne",
    family: "Niconne",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "pinyon-script",
    family: "Pinyon Script",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "petit-formal-script",
    family: "Petit Formal Script",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "redressed",
    family: "Redressed",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "rouge-script",
    family: "Rouge Script",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "shadows-into-light",
    family: "Shadows Into Light",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "sofia",
    family: "Sofia",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "sonsie-one",
    family: "Sonsie One",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "style-script",
    family: "Style Script",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "tangerine",
    family: "Tangerine",
    category: "Script",
    bodySuitable: false,
    weights: "400;700",
  },
  {
    id: "yesteryear",
    family: "Yesteryear",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "zhi-mang-xing",
    family: "Zhi Mang Xing",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "miss-fajardose",
    family: "Miss Fajardose",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "stalemate",
    family: "Stalemate",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "dr-sugiyama",
    family: "Dr Sugiyama",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "caramel",
    family: "Caramel",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "kolker-brush",
    family: "Kolker Brush",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "love-light",
    family: "Love Light",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "luxurious-script",
    family: "Luxurious Script",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "montecarlo",
    family: "MonteCarlo",
    category: "Script",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "open-sans",
    family: "Open Sans",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "roboto",
    family: "Roboto",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "roboto-condensed",
    family: "Roboto Condensed",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "lato",
    family: "Lato",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "nunito-sans",
    family: "Nunito Sans",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "outfit",
    family: "Outfit",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "plus-jakarta-sans",
    family: "Plus Jakarta Sans",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "figtree",
    family: "Figtree",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "sora",
    family: "Sora",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "rubik",
    family: "Rubik",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "mulish",
    family: "Mulish",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "urbanist",
    family: "Urbanist",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "karla",
    family: "Karla",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "barlow",
    family: "Barlow",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "barlow-condensed",
    family: "Barlow Condensed",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "cabin",
    family: "Cabin",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "assistant",
    family: "Assistant",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "public-sans",
    family: "Public Sans",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "jost",
    family: "Jost",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "lexend",
    family: "Lexend",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "exo-2",
    family: "Exo 2",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "comfortaa",
    family: "Comfortaa",
    category: "Sans serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "merriweather",
    family: "Merriweather",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "roboto-slab",
    family: "Roboto Slab",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "eb-garamond",
    family: "EB Garamond",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "crimson-text",
    family: "Crimson Text",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "crimson-pro",
    family: "Crimson Pro",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "spectral",
    family: "Spectral",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "domine",
    family: "Domine",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "vollkorn",
    family: "Vollkorn",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "alegreya",
    family: "Alegreya",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "alice",
    family: "Alice",
    category: "Serif",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "prata",
    family: "Prata",
    category: "Serif",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "marcellus",
    family: "Marcellus",
    category: "Serif",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "vidaloka",
    family: "Vidaloka",
    category: "Serif",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "gloock",
    family: "Gloock",
    category: "Serif",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "instrument-serif",
    family: "Instrument Serif",
    category: "Serif",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "young-serif",
    family: "Young Serif",
    category: "Serif",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "newsreader",
    family: "Newsreader",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "literata",
    family: "Literata",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "cardo",
    family: "Cardo",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "dm-serif-text",
    family: "DM Serif Text",
    category: "Serif",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "cormorant-infant",
    family: "Cormorant Infant",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "zilla-slab",
    family: "Zilla Slab",
    category: "Serif",
    bodySuitable: true,
    weights: "400;700",
  },
  {
    id: "alfa-slab-one",
    family: "Alfa Slab One",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "archivo-black",
    family: "Archivo Black",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "black-ops-one",
    family: "Black Ops One",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "bungee",
    family: "Bungee",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "bungee-shade",
    family: "Bungee Shade",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "changa-one",
    family: "Changa One",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "concert-one",
    family: "Concert One",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "fascinate",
    family: "Fascinate",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "fugaz-one",
    family: "Fugaz One",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "graduate",
    family: "Graduate",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "gruppo",
    family: "Gruppo",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "luckiest-guy",
    family: "Luckiest Guy",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "notable",
    family: "Notable",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "passion-one",
    family: "Passion One",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "patua-one",
    family: "Patua One",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "paytone-one",
    family: "Paytone One",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "permanent-marker",
    family: "Permanent Marker",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "racing-sans-one",
    family: "Racing Sans One",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "russo-one",
    family: "Russo One",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
  {
    id: "unbounded",
    family: "Unbounded",
    category: "Display",
    bodySuitable: false,
    weights: "400",
  },
] as const;
