const FALLBACK_GOOGLE_ANALYTICS_MEASUREMENT_ID = "G-3X25SZMRFY";

export const GOOGLE_ANALYTICS_MEASUREMENT_ID =
  process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID?.trim() ||
  FALLBACK_GOOGLE_ANALYTICS_MEASUREMENT_ID;
