import type { LiveCardButtonPositions, LiveCardInvitationData } from "@/components/studio/StudioLiveCardActionSurface";

type LandingLiveCardTheme = NonNullable<LiveCardInvitationData["theme"]> & Record<string, unknown>;
type LandingLiveCardInteractiveMetadata =
  NonNullable<LiveCardInvitationData["interactiveMetadata"]> & Record<string, unknown>;

export type LandingLiveCardInvitationSnapshot = LiveCardInvitationData & {
  [key: string]: unknown;
  theme?: LandingLiveCardTheme;
  interactiveMetadata?: LandingLiveCardInteractiveMetadata;
};

export type LandingLiveCardSnapshot = {
  id: string;
  slug: string;
  title: string;
  imageUrl: string;
  invitationData: LandingLiveCardInvitationSnapshot;
  positions: LiveCardButtonPositions;
  initialActiveTab?: undefined;
};

export const landingLiveCardSnapshots: LandingLiveCardSnapshot[] = [
  {
    "id": "ca73fe2c-1078-4753-a245-02e1ace85c24",
    "slug": "lara-s-7th-dino-quest",
    "title": "Lara’s 7th Dino-Quest",
    "imageUrl": "/images/landing/live-cards/lara-s-7th-dino-quest.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Jurassic birthday adventure",
        "accentColor": "#C98A2E",
        "primaryColor": "#2F5D50",
        "secondaryColor": "#D8D2C4"
      },
      "title": "Lara’s 7th Dino-Quest",
      "subtitle": "Jurassic birthday adventure",
      "description": "An editorial birthday card for Lara Bennett’s Jurassic adventure, styled with cinematic energy and a polished movie-party feel at AMC Boulevard 10.",
      "callToAction": "RSVP Now",
      "eventDetails": {
        "age": "7",
        "name": "Lara Bennett",
        "style": "Adventurous and celebratory",
        "theme": "Jurassic birthday adventure",
        "colors": "green, stone, amber",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Birthday",
        "giftNote": "",
        "hostedBy": "",
        "location": "Franklin, TN",
        "occasion": "Birthday",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-05-23",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "12:00",
        "venueName": "AMC Boulevard 10",
        "adultsOnly": false,
        "eventTitle": "Lara's 7th Dino-Quest",
        "gradeLevel": "",
        "invitedWho": "Parents and young guests",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "555-0107",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "Join Lara for a polished movie-party birthday with cat-themed treats, popcorn towers, and a private screening feel.",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "AMC Boulevard 10, Franklin, TN",
      "scheduleLine": "Saturday May 23rd at 12:00 PM",
      "socialCaption": "Share the adventure with Lara’s birthday crew.",
      "interactiveMetadata": {
        "ctaLabel": "RSVP Now",
        "funFacts": [
          "Movie-party setting",
          "Popcorn and treats",
          "Private screening feel"
        ],
        "shareNote": "Share the adventure with Lara’s birthday crew.",
        "rsvpMessage": "Please RSVP to 555-0107"
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "a1546f2b-cd8f-4ca9-a726-1f5fdacb25b4",
    "slug": "friday-night-lights-a",
    "title": "Friday Night Lights",
    "imageUrl": "/images/landing/live-cards/friday-night-lights-a.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Bold varsity stadium",
        "accentColor": "#F5F7FA",
        "primaryColor": "#123C7A",
        "secondaryColor": "#D4A017"
      },
      "title": "Friday Night Lights",
      "subtitle": "Game Day",
      "description": "Bold varsity football invitation art for a high-energy home game at Panther Stadium, built around school-color stadium atmosphere and a packed student-section feel.",
      "callToAction": "Join the Crowd",
      "eventDetails": {
        "age": "",
        "name": "",
        "style": "High-energy and proud",
        "theme": "",
        "colors": "blue, gold, stadium white",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Game Day",
        "giftNote": "",
        "hostedBy": "",
        "location": "Panther Stadium, Austin, TX",
        "occasion": "Game Day",
        "rsvpName": "",
        "teamName": "Varsity Panthers",
        "dressCode": "",
        "eventDate": "2026-09-18",
        "lunchInfo": "",
        "sportType": "Football",
        "startTime": "19:00",
        "venueName": "Panther Stadium",
        "adultsOnly": false,
        "eventTitle": "Friday Night Lights",
        "gradeLevel": "",
        "invitedWho": "Students, parents, and fans",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "",
        "opponentName": "Central City Tigers",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "Varsity",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "A high-energy home game with student section turnout, gates opening early, and bold matchup graphics.",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "Panther Stadium, Austin, TX",
      "scheduleLine": "Friday September 18th at 7:00 PM",
      "socialCaption": "Send to fans who want the full Friday night atmosphere.",
      "interactiveMetadata": {
        "ctaLabel": "Join the Crowd",
        "funFacts": [
          "Student section turnout expected",
          "Gates open early",
          "Home game at Panther Stadium"
        ],
        "shareNote": "Send to fans who want the full Friday night atmosphere.",
        "rsvpMessage": "Be there early for gates opening and pregame energy."
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "d9ebe042-5af3-45eb-8eba-a881e9a0340b",
    "slug": "garden-vows",
    "title": "Garden Vows",
    "imageUrl": "/images/landing/live-cards/garden-vows.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Romantic editorial stationery",
        "accentColor": "#7E9273",
        "primaryColor": "#F7F2E8",
        "secondaryColor": "#D8C3A5"
      },
      "title": "Garden Vows",
      "subtitle": "Garden Vows",
      "description": "A refined wedding card for Ava & James, set for an elegant garden ceremony, dinner, candlelight, and dancing beneath the glass atrium.",
      "callToAction": "RSVP",
      "eventDetails": {
        "age": "",
        "name": "",
        "style": "Romantic and refined",
        "theme": "",
        "colors": "ivory, champagne, sage",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Wedding",
        "giftNote": "",
        "hostedBy": "",
        "location": "Charleston, SC",
        "occasion": "Wedding",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-10-10",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "16:30",
        "venueName": "The Conservatory",
        "adultsOnly": false,
        "eventTitle": "Ava & James Garden Vows",
        "gradeLevel": "",
        "invitedWho": "Wedding guests",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "Ava Collins & James Porter",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "garden-vows@example.com",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "Celebrate an elegant garden ceremony followed by dinner, candlelight, and dancing under the glass atrium.",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "The Conservatory • Charleston, SC",
      "scheduleLine": "Saturday October 10th at 4:30 PM",
      "socialCaption": "Share this elegant invitation with your closest guests.",
      "interactiveMetadata": {
        "ctaLabel": "RSVP",
        "funFacts": [
          "Ceremony at The Conservatory",
          "Dinner and dancing to follow",
          "Charleston, SC"
        ],
        "shareNote": "Share this elegant invitation with your closest guests.",
        "rsvpMessage": "Kindly reply to garden-vows@example.com"
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "b755ee5d-f1f4-4d2c-9a62-94cd8e752473",
    "slug": "madeline-s-garden-brunch",
    "title": "Madeline's Garden Brunch",
    "imageUrl": "/images/landing/live-cards/madeline-s-garden-brunch.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "soft editorial brunch",
        "accentColor": "#A9B89A",
        "primaryColor": "#E8C7C5",
        "secondaryColor": "#F7F1E8"
      },
      "title": "Madeline's Garden Brunch",
      "subtitle": "Bridal Shower",
      "description": "An elegant bridal shower for Madeline Rivers with floral brunch details, champagne, and a soft garden-party mood at Willow House.",
      "callToAction": "RSVP Now",
      "eventDetails": {
        "age": "",
        "name": "Madeline Rivers",
        "style": "Elegant and celebratory",
        "theme": "",
        "colors": "blush, cream, sage",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Bridal Shower",
        "giftNote": "",
        "hostedBy": "Sofia and Chloe",
        "location": "Savannah, GA",
        "occasion": "Bridal Shower",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-08-08",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "11:00",
        "venueName": "Willow House",
        "adultsOnly": false,
        "eventTitle": "Madeline's Garden Brunch",
        "gradeLevel": "",
        "invitedWho": "Bridal shower guests",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "garden-brunch@example.com",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "A floral brunch shower with champagne, fresh pastries, and soft garden-party details for Madeline.",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "Willow House, Savannah, GA",
      "scheduleLine": "Saturday August 8th at 11:00 AM",
      "socialCaption": "Share this invite with fellow guests and keep the celebration close.",
      "interactiveMetadata": {
        "ctaLabel": "RSVP Now",
        "funFacts": [
          "Champagne and pastries will be served",
          "Garden-inspired brunch setting",
          "Hosted at Willow House",
          "Savannah, GA"
        ],
        "shareNote": "Share this invite with fellow guests and keep the celebration close.",
        "rsvpMessage": "Please RSVP to garden-brunch@example.com"
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "9db558a0-b738-4772-93ee-9c2669b5fbeb",
    "slug": "elena-s-beary-sweet-shower",
    "title": "Elena's Beary Sweet Shower",
    "imageUrl": "/images/landing/live-cards/elena-s-beary-sweet-shower.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Airy beary baby shower",
        "accentColor": "#D8C3A5",
        "primaryColor": "#A9CFE7",
        "secondaryColor": "#F7F2EA"
      },
      "title": "Elena's Beary Sweet Shower",
      "subtitle": "A baby shower for Elena Martinez",
      "description": "A warm, upscale baby shower with soft blue accents, ivory florals, and a cozy family welcome for Elena Martinez.",
      "callToAction": "RSVP Now",
      "eventDetails": {
        "age": "",
        "name": "",
        "style": "Warm and welcoming",
        "theme": "",
        "colors": "soft blue, ivory, beige",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "Baby Mateo",
        "category": "Baby Shower",
        "giftNote": "",
        "hostedBy": "",
        "location": "Tampa, FL",
        "occasion": "Baby Shower",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-07-19",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "13:00",
        "venueName": "Olive Room",
        "adultsOnly": false,
        "eventTitle": "Elena's Beary Sweet Shower",
        "gradeLevel": "",
        "invitedWho": "Family and friends",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "beary-shower@example.com",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "Elena Martinez",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "A warm baby shower with florals, gifting tables, soft blue details, and a welcoming family atmosphere.",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "Olive Room, Tampa, FL",
      "scheduleLine": "Sunday July 19th at 1:00 PM",
      "socialCaption": "Share the joy with family and friends",
      "interactiveMetadata": {
        "ctaLabel": "RSVP Now",
        "funFacts": [
          "Soft blue and ivory palette",
          "Hosted at Olive Room",
          "Family-friendly celebration",
          "Gifts and well wishes welcome"
        ],
        "shareNote": "Share the joy with family and friends",
        "rsvpMessage": "Please RSVP to beary-shower@example.com"
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "8a974cb7-4635-41fd-a915-23c902561fd6",
    "slug": "lincoln-memorial-discovery-day",
    "title": "Lincoln Memorial Discovery Day",
    "imageUrl": "/images/landing/live-cards/lincoln-memorial-discovery-day.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "documentary civic",
        "accentColor": "#C8A96A",
        "primaryColor": "#7A6F63",
        "secondaryColor": "#7FA8C9"
      },
      "title": "Lincoln Memorial Discovery Day",
      "subtitle": "8th Grade Field Trip",
      "description": "A polished 8th Grade field trip to Washington, DC for a civic history expedition at the Lincoln Memorial.",
      "callToAction": "RSVP Now",
      "eventDetails": {
        "age": "",
        "name": "",
        "style": "Educational and organized",
        "theme": "",
        "colors": "stone, sky blue, muted civic tones",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Field Trip/Day",
        "giftNote": "",
        "hostedBy": "",
        "location": "Washington, DC",
        "occasion": "Field Trip/Day",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-04-30",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "08:15",
        "venueName": "Lincoln Memorial",
        "adultsOnly": false,
        "eventTitle": "Lincoln Memorial Discovery Day",
        "gradeLevel": "8th Grade",
        "invitedWho": "Students and parents",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "discovery-day@example.com",
        "teacherName": "Mrs. Harper",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "A school field trip in Washington, DC focused on civic landmarks, history, and a polished class outing at the Lincoln Memorial.",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "Lincoln Memorial, Washington, DC",
      "scheduleLine": "Thursday April 30th at 8:15 AM",
      "socialCaption": "Share with parents and chaperones.",
      "interactiveMetadata": {
        "ctaLabel": "RSVP Now",
        "funFacts": [
          "8th Grade outing",
          "Arrive by 8:15 AM",
          "Washington, DC",
          "Lincoln Memorial"
        ],
        "shareNote": "Share with parents and chaperones.",
        "rsvpMessage": "Please reply to discovery-day@example.com."
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "83bb6c54-35ed-48da-98e7-867ad728df7e",
    "slug": "the-carter-housewarming",
    "title": "The Carter Housewarming",
    "imageUrl": "/images/landing/live-cards/the-carter-housewarming.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Modern editorial open house",
        "accentColor": "#A66A3F",
        "primaryColor": "#D8C7B2",
        "secondaryColor": "#5E748A"
      },
      "title": "The Carter Housewarming",
      "subtitle": "Modern open house",
      "description": "A modern open-house welcome for neighbors and friends, with warm hosting, easy conversation, and a relaxed evening feel.",
      "callToAction": "RSVP Now",
      "eventDetails": {
        "age": "",
        "name": "",
        "style": "Welcoming and relaxed",
        "theme": "",
        "colors": "warm neutrals, dusk blue, wood",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Housewarming",
        "giftNote": "",
        "hostedBy": "",
        "location": "Nashville, TN",
        "occasion": "Housewarming",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-05-16",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "15:00",
        "venueName": "58 Cedar Park Drive",
        "adultsOnly": false,
        "eventTitle": "The Carter Housewarming",
        "gradeLevel": "",
        "invitedWho": "Neighbors and friends",
        "isSurprise": false,
        "mainPerson": "The Carter Family",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "housewarming@example.com",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "A modern open-house gathering with snacks, music, and a relaxed neighborhood welcome.",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "58 Cedar Park Drive, Nashville, TN",
      "scheduleLine": "Saturday May 16th at 3:00 PM",
      "socialCaption": "Share with friends and neighbors who would love a warm new-home welcome.",
      "interactiveMetadata": {
        "ctaLabel": "RSVP Now",
        "funFacts": [
          "Snacks and music throughout",
          "Casual drop-in welcome",
          "Neighborhood friends invited"
        ],
        "shareNote": "Share with friends and neighbors who would love a warm new-home welcome.",
        "rsvpMessage": "Please RSVP to housewarming@example.com"
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "2e77eeba-5791-4ed2-864c-de2df9ddb1fe",
    "slug": "founder-appreciation-night",
    "title": "Founder Appreciation Night",
    "imageUrl": "/images/landing/live-cards/founder-appreciation-night.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Premium loft, gallery-lit",
        "accentColor": "#E8D7B0",
        "primaryColor": "#0B1F3A",
        "secondaryColor": "#2B2F36"
      },
      "title": "Founder Appreciation Night",
      "subtitle": "An evening for collaborators and partners",
      "description": "An elevated evening honoring North Shore Creative Founders with drinks, brief remarks, and a gallery-style loft setting.",
      "callToAction": "RSVP Now",
      "eventDetails": {
        "age": "",
        "name": "",
        "style": "Elevated and appreciative",
        "theme": "",
        "colors": "navy, charcoal, warm gallery light",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Custom Invite",
        "giftNote": "",
        "hostedBy": "",
        "location": "Seattle, WA",
        "occasion": "Custom Invite",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-11-05",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "18:00",
        "venueName": "Pier 9 Loft",
        "adultsOnly": false,
        "eventTitle": "Founder Appreciation Night",
        "gradeLevel": "",
        "invitedWho": "Guests and partners",
        "isSurprise": false,
        "mainPerson": "North Shore Creative",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "appreciation-night@example.com",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "A bespoke appreciation event for collaborators and partners with drinks, short remarks, and gallery-style ambiance.",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "Pier 9 Loft, Seattle, WA",
      "scheduleLine": "Thursday November 5th at 6:00 PM",
      "socialCaption": "Invite fellow collaborators and partners to join the evening.",
      "interactiveMetadata": {
        "ctaLabel": "RSVP Now",
        "funFacts": [
          "Drinks served throughout the evening",
          "Short remarks will begin at 6:30 PM",
          "Gallery-style ambiance in a loft setting"
        ],
        "shareNote": "Invite fellow collaborators and partners to join the evening.",
        "rsvpMessage": "Please RSVP to appreciation-night@example.com"
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "29e154db-3239-45f3-8ed2-d4b8051b28cf",
    "slug": "lara-s-dino-quest",
    "title": "Lara’s Dino Quest",
    "imageUrl": "/images/landing/live-cards/lara-s-dino-quest.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Dino adventure birthday",
        "accentColor": "#E86A4A",
        "primaryColor": "#2E5E4E",
        "secondaryColor": "#F4C95D"
      },
      "title": "Lara’s Dino Quest",
      "subtitle": "Dinosaur adventure party",
      "description": "A playful birthday live card for Lara Bennett’s 7th, styled as a dinosaur adventure at the park with polished party energy and bold, kid-friendly motion.",
      "callToAction": "RSVP Now",
      "eventDetails": {
        "age": "7",
        "name": "Lara Bennett",
        "style": "",
        "theme": "dinosaurs theme at the adventure park",
        "colors": "",
        "gender": "Girl",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Birthday",
        "giftNote": "",
        "hostedBy": "",
        "location": "AMC Boulevard 10, Franklin, TN",
        "occasion": "",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-05-23",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "12:00",
        "venueName": "",
        "adultsOnly": false,
        "eventTitle": "",
        "gradeLevel": "",
        "invitedWho": "",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "555-0142",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "Lara's fun movie birthday",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "AMC Boulevard 10, Franklin, TN",
      "scheduleLine": "Saturday May 23rd at 12:00 PM",
      "socialCaption": "Send this card to guests and get them ready for Lara’s big day.",
      "interactiveMetadata": {
        "ctaLabel": "RSVP Now",
        "funFacts": [
          "Age 7 celebration",
          "Adventure park setting",
          "Movie birthday fun"
        ],
        "shareNote": "Send this card to guests and get them ready for Lara’s big day.",
        "rsvpMessage": "Please RSVP with a quick call to 555-0142."
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "c787844a-4173-4585-ae7b-e75f8a1ca1cf",
    "slug": "friday-night-lights-b",
    "title": "Friday Night Lights",
    "imageUrl": "/images/landing/live-cards/friday-night-lights-b.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Bold stadium night",
        "accentColor": "#F5F7FA",
        "primaryColor": "#0B1F3A",
        "secondaryColor": "#D4AF37"
      },
      "title": "Friday Night Lights",
      "subtitle": "Game Day",
      "description": "A bold football game-day card for Varsity Panthers vs Central City Tigers, styled in blue and gold with a bright under-the-lights atmosphere.",
      "callToAction": "Be there for kickoff.",
      "eventDetails": {
        "age": "",
        "name": "",
        "style": "",
        "theme": "friday night football under the lights, blue and gold",
        "colors": "",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Game Day",
        "giftNote": "",
        "hostedBy": "",
        "location": "Panther Stadium, 800 Victory Lane, Austin, TX",
        "occasion": "",
        "rsvpName": "",
        "teamName": "Varsity Panthers",
        "dressCode": "",
        "eventDate": "2026-09-18",
        "lunchInfo": "",
        "sportType": "Football",
        "startTime": "19:00",
        "venueName": "",
        "adultsOnly": false,
        "eventTitle": "Friday Night Lights",
        "gradeLevel": "",
        "invitedWho": "",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "",
        "opponentName": "Central City Tigers",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "Big home game tonight",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "Panther Stadium, 800 Victory Lane, Austin, TX",
      "scheduleLine": "Friday, September 18 at 7:00 PM",
      "socialCaption": "Send to guests who love a true Friday night game.",
      "interactiveMetadata": {
        "ctaLabel": "Be there for kickoff.",
        "funFacts": [
          "Football matchup: Varsity Panthers vs Central City Tigers",
          "Kickoff: 7:00 PM",
          "Venue: Panther Stadium, Austin, TX"
        ],
        "shareNote": "Send to guests who love a true Friday night game.",
        "rsvpMessage": "Join us for kickoff night at Panther Stadium."
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "c3a9fd82-b824-4722-97bb-29bf03127498",
    "slug": "garden-candlelight",
    "title": "Garden Candlelight",
    "imageUrl": "/images/landing/live-cards/garden-candlelight.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Elegant garden, candlelit",
        "accentColor": "#C9A227",
        "primaryColor": "#F7F1E8",
        "secondaryColor": "#D8C2A8"
      },
      "title": "Garden Candlelight",
      "subtitle": "Wedding",
      "description": "A refined wedding card for Ava Collins & James Porter, set for an elegant garden celebration with white florals, candlelight, and dinner at The Conservatory.",
      "callToAction": "RSVP",
      "eventDetails": {
        "age": "",
        "name": "",
        "style": "",
        "theme": "elegant garden wedding with white flowers and candles",
        "colors": "",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Wedding",
        "giftNote": "",
        "hostedBy": "",
        "location": "The Conservatory, 125 Garden Terrace, Charleston, SC",
        "occasion": "",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-10-10",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "16:30",
        "venueName": "",
        "adultsOnly": false,
        "eventTitle": "Our Wedding Weekend",
        "gradeLevel": "",
        "invitedWho": "",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "Ava Collins & James Porter",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "garden-candlelight@example.com",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "Garden wedding with dinner",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "The Conservatory, 125 Garden Terrace, Charleston, SC",
      "scheduleLine": "Saturday October 10th at 4:30 PM",
      "socialCaption": "A beautiful evening to share with loved ones.",
      "interactiveMetadata": {
        "ctaLabel": "RSVP",
        "funFacts": [
          "White floral details",
          "Candlelit dinner setting",
          "The Conservatory, Charleston"
        ],
        "shareNote": "A beautiful evening to share with loved ones.",
        "rsvpMessage": "Kindly reply to garden-candlelight@example.com"
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "15baeb75-fb63-4ad9-9d9b-ab77f7791905",
    "slug": "blush-brunch-shower",
    "title": "Blush Brunch Shower",
    "imageUrl": "/images/landing/live-cards/blush-brunch-shower.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Blush garden brunch",
        "accentColor": "#B77A8B",
        "primaryColor": "#F7D6DE",
        "secondaryColor": "#FFF7F2"
      },
      "title": "Blush Brunch Shower",
      "subtitle": "Hosted by Sofia and Chloe",
      "description": "A warm, elevated bridal shower for Madeline Rivers, styled as a garden brunch with blush florals and polished hosting details.",
      "callToAction": "RSVP Now",
      "eventDetails": {
        "age": "",
        "name": "",
        "style": "",
        "theme": "bridal shower garden brunch with blush flowers",
        "colors": "",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "",
        "category": "Bridal Shower",
        "giftNote": "",
        "hostedBy": "Sofia and Chloe",
        "location": "Willow House, 44 Magnolia Street, Savannah, GA",
        "occasion": "",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-08-08",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "11:00",
        "venueName": "",
        "adultsOnly": false,
        "eventTitle": "",
        "gradeLevel": "",
        "invitedWho": "",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "blush-brunch@example.com",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "Madeline Rivers",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "Brunch shower for Madeline",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "Willow House, 44 Magnolia Street, Savannah, GA",
      "scheduleLine": "Saturday August 8th at 11:00 AM",
      "socialCaption": "Share this elegant shower invite with guests who will celebrate Madeline.",
      "interactiveMetadata": {
        "ctaLabel": "RSVP Now",
        "funFacts": [
          "Brunch begins at 11:00 AM",
          "Willow House in Savannah",
          "Your presence is the best gift."
        ],
        "shareNote": "Share this elegant shower invite with guests who will celebrate Madeline.",
        "rsvpMessage": "Kindly RSVP to blush-brunch@example.com"
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  },
  {
    "id": "e7752604-79dd-4316-8ab7-fa25223eda1a",
    "slug": "elena-s-baby-shower",
    "title": "Elena’s Baby Shower",
    "imageUrl": "/images/landing/live-cards/elena-s-baby-shower.webp",
    "invitationData": {
      "theme": {
        "themeStyle": "Soft blue nursery chic",
        "accentColor": "#D9B38C",
        "primaryColor": "#B9D8F3",
        "secondaryColor": "#F6F1EA"
      },
      "title": "Elena’s Baby Shower",
      "subtitle": "Celebrating Elena Martinez",
      "description": "A warm baby shower for Elena Martinez, styled with soft blue balloons, teddy bear accents, and a refined nursery-inspired celebration mood.",
      "callToAction": "RSVP",
      "eventDetails": {
        "age": "",
        "name": "",
        "style": "",
        "theme": "baby shower with soft blue balloons and teddy bears",
        "colors": "",
        "gender": "Neutral",
        "endTime": "",
        "message": "",
        "audience": "",
        "babyName": "Baby Mateo",
        "category": "Baby Shower",
        "giftNote": "",
        "hostedBy": "",
        "location": "Olive Room, 212 Harbor Avenue, Tampa, FL",
        "occasion": "",
        "rsvpName": "",
        "teamName": "",
        "dressCode": "",
        "eventDate": "2026-07-19",
        "lunchInfo": "",
        "sportType": "",
        "startTime": "13:00",
        "venueName": "",
        "adultsOnly": false,
        "eventTitle": "",
        "gradeLevel": "",
        "invitedWho": "",
        "isSurprise": false,
        "mainPerson": "",
        "calloutText": "",
        "coupleNames": "",
        "isMilestone": false,
        "orientation": "portrait",
        "parkingInfo": "",
        "rsvpContact": "baby-shower@example.com",
        "teacherName": "",
        "ticketsLink": "",
        "whatToBring": "",
        "activityNote": "",
        "ceremonyDate": "",
        "ceremonyTime": "",
        "customLabel1": "",
        "customLabel2": "",
        "customValue1": "",
        "customValue2": "",
        "diaperRaffle": false,
        "honoreeNames": "Elena Martinez",
        "opponentName": "",
        "optionalLink": "",
        "registryLink": "",
        "rsvpDeadline": "",
        "broadcastInfo": "",
        "ceremonyVenue": "",
        "plusOnePolicy": "",
        "receptionTime": "",
        "bringABookNote": "",
        "costPerStudent": "",
        "guestImageUrls": [],
        "leagueDivision": "",
        "receptionVenue": "",
        "sourceFlyerUrl": "",
        "weddingWebsite": "",
        "sourceFlyerName": "",
        "sourceMediaMode": "none",
        "visualStyleMode": "editorial_cinematic",
        "chaperonesNeeded": false,
        "emergencyContact": "",
        "likenessStrength": "balanced",
        "accommodationInfo": "",
        "bookInsteadOfCard": false,
        "imageFinishPreset": "",
        "visualPreferences": "",
        "detailsDescription": "Baby shower for Elena",
        "giftPreferenceNote": "",
        "transportationInfo": "",
        "transportationType": "",
        "specialInstructions": "",
        "subjectTransformMode": "default",
        "sourceFlyerPreviewUrl": "",
        "permissionSlipRequired": false
      },
      "heroTextMode": "image",
      "locationLine": "Olive Room, 212 Harbor Avenue, Tampa, FL",
      "scheduleLine": "Saturday July 19th at 1:00 PM",
      "socialCaption": "Share this sweet shower invite with guests who will love celebrating Elena.",
      "interactiveMetadata": {
        "ctaLabel": "RSVP",
        "funFacts": [
          "Olive Room, Tampa",
          "1:00 PM start",
          "Your presence is the best gift."
        ],
        "shareNote": "Share this sweet shower invite with guests who will love celebrating Elena.",
        "rsvpMessage": "Please join us in celebrating Elena Martinez."
      }
    },
    "positions": {
      "rsvp": {
        "x": 0,
        "y": 0
      },
      "share": {
        "x": 0,
        "y": 0
      },
      "details": {
        "x": 0,
        "y": 0
      },
      "calendar": {
        "x": 0,
        "y": 0
      },
      "location": {
        "x": 0,
        "y": 0
      },
      "registry": {
        "x": 0,
        "y": 0
      }
    }
  }
];
