import type { StudioEventDetails, StudioGenerationGuidance } from "./types.ts";

export type StudioPromptSample = {
  slug: string;
  label: string;
  event: StudioEventDetails;
  guidance: StudioGenerationGuidance;
};

export const STUDIO_PROMPT_SAMPLES: StudioPromptSample[] = [
  {
    slug: "birthday",
    label: "Birthday",
    event: {
      title: "Lara's 7th Dino-Quest",
      category: "Birthday",
      occasion: "Birthday",
      honoreeName: "Lara Bennett",
      ageOrMilestone: "7",
      userIdea: "Jurassic birthday adventure",
      date: "2026-05-23",
      startTime: "12:00 PM",
      venueName: "AMC Boulevard 10",
      venueAddress: "Franklin, TN",
      links: [],
    },
    guidance: {
      style: "Editorial cinematic invitation art with clear venue context and clean title hierarchy.",
      tone: "Adventurous and celebratory",
      audience: "Parents and young guests",
      colorPalette: "green, stone, amber",
    },
  },
  {
    slug: "wedding",
    label: "Wedding",
    event: {
      title: "Ava & James Garden Vows",
      category: "Wedding",
      occasion: "Wedding",
      honoreeName: "Ava & James",
      userIdea: "Garden vows",
      date: "2026-10-10",
      startTime: "4:30 PM",
      venueName: "The Conservatory",
      venueAddress: "Charleston, SC",
      links: [],
    },
    guidance: {
      style: "Luxury wedding stationery with editorial restraint and centered typography space.",
      tone: "Romantic and refined",
      audience: "Wedding guests",
      colorPalette: "ivory, champagne, sage",
    },
  },
  {
    slug: "baby-shower",
    label: "Baby Shower",
    event: {
      title: "Elena's Beary Sweet Shower",
      category: "Baby Shower",
      occasion: "Baby Shower",
      honoreeName: "Elena Martinez",
      userIdea: "Beary sweet shower",
      date: "2026-07-19",
      startTime: "1:00 PM",
      venueName: "Olive Room",
      venueAddress: "Tampa, FL",
      links: [],
    },
    guidance: {
      style: "Bright upscale baby shower invitation with restrained motif styling and airy composition.",
      tone: "Warm and welcoming",
      audience: "Family and friends",
      colorPalette: "soft blue, ivory, beige",
    },
  },
  {
    slug: "bridal-shower",
    label: "Bridal Shower",
    event: {
      title: "Madeline's Garden Brunch",
      category: "Bridal Shower",
      occasion: "Bridal Shower",
      honoreeName: "Madeline Rivers",
      userIdea: "Garden brunch",
      date: "2026-08-08",
      startTime: "11:00 AM",
      venueName: "Willow House",
      venueAddress: "44 Magnolia Street",
      links: [],
    },
    guidance: {
      style: "Soft editorial brunch invitation with one polished hosting moment and premium restraint.",
      tone: "Elegant and celebratory",
      audience: "Bridal shower guests",
      colorPalette: "blush, cream, sage",
    },
  },
  {
    slug: "anniversary",
    label: "Anniversary",
    event: {
      title: "Naomi & Daniel Silver Anniversary",
      category: "Anniversary",
      occasion: "Anniversary",
      honoreeName: "Naomi and Daniel Brooks",
      ageOrMilestone: "25",
      userIdea: "Silver anniversary dinner",
      date: "2026-06-14",
      startTime: "6:30 PM",
      venueName: "The Marlowe Room",
      venueAddress: "Chicago",
      links: [],
    },
    guidance: {
      style: "Upscale anniversary invitation with candlelit formality and clean uninterrupted composition.",
      tone: "Romantic and formal",
      audience: "Friends and family",
      colorPalette: "silver, crimson, black",
    },
  },
  {
    slug: "housewarming",
    label: "Housewarming",
    event: {
      title: "The Carter Housewarming",
      category: "Housewarming",
      occasion: "Housewarming",
      honoreeName: "The Carters",
      userIdea: "Modern open house",
      date: "2026-05-16",
      startTime: "3:00 PM",
      venueName: "58 Cedar Park Drive",
      venueAddress: "Nashville, TN",
      links: [],
    },
    guidance: {
      style: "Modern editorial invitation scene with warm hosting cues and lived-in atmosphere.",
      tone: "Welcoming and relaxed",
      audience: "Neighbors and friends",
      colorPalette: "warm neutrals, dusk blue, wood",
    },
  },
  {
    slug: "field-trip-day",
    label: "Field Trip/Day",
    event: {
      title: "Lincoln Memorial Discovery Day",
      category: "Field Trip/Day",
      occasion: "Field Trip/Day",
      honoreeName: "8th Grade",
      userIdea: "Civic history expedition",
      date: "2026-04-30",
      startTime: "8:15 AM",
      venueName: "Lincoln Memorial",
      venueAddress: "Washington, DC",
      links: [],
    },
    guidance: {
      style: "Documentary-realistic field trip invitation with accurate architecture and believable group staging.",
      tone: "Educational and organized",
      audience: "Students and parents",
      colorPalette: "stone, sky blue, muted civic tones",
    },
  },
  {
    slug: "game-day",
    label: "Game Day",
    event: {
      title: "Friday Night Lights",
      category: "Game Day",
      occasion: "Game Day",
      sportType: "Football",
      teamName: "Varsity Panthers",
      opponentName: "Central City Tigers",
      leagueDivision: "Varsity",
      userIdea: "Friday night lights",
      date: "2026-09-18",
      startTime: "7:00 PM",
      venueName: "Panther Stadium",
      venueAddress: "Franklin, TN",
      links: [],
    },
    guidance: {
      style: "Bold sports invitation art with one coherent action scene and strong school-color atmosphere.",
      tone: "High-energy and proud",
      audience: "Students, parents, and fans",
      colorPalette: "blue, gold, stadium white",
    },
  },
  {
    slug: "custom-invite",
    label: "Custom Invite",
    event: {
      title: "Founder Appreciation Night",
      category: "Custom Invite",
      occasion: "Custom Invite",
      hostName: "North Shore Creative",
      honoreeName: "North Shore Creative Founders",
      userIdea: "Founder appreciation night",
      date: "2026-11-05",
      startTime: "6:00 PM",
      venueName: "Pier 9 Loft",
      venueAddress: "Seattle, WA",
      links: [],
    },
    guidance: {
      style: "Premium corporate event invitation with one uninterrupted loft scene and brand-safe composition.",
      tone: "Elevated and appreciative",
      audience: "Guests and partners",
      colorPalette: "navy, charcoal, warm gallery light",
    },
  },
];
