export type BirthdayBodyTreatment = "confetti" | "confection" | "festival" | "journal" | "specimen" | "menu" | "mission" | "stage" | "storybook" | "coast" | "club" | "scorecard" | "atelier" | "dispatch" | "garden" | "archive" | "banquet" | "gallery" | "lounge" | "voyage" | "workshop" | "market" | "dunes" | "salon";
// Art-directed assignments: theme meaning, rather than a hash, decides the page structure.
export const BIRTHDAY_BODY_DIRECTIONS: Record<string, BirthdayBodyTreatment> = {
  "pottery-playhouse": "atelier",
  "friendship-bead-club": "confetti",
  "slime-squish-studio": "specimen",
  "magic-school-owls": "storybook",
  "roller-rink-rainbow": "club",
  "pixel-builder-world": "mission",
  "plushie-sleepover": "salon",
  "kpop-stage-stars": "stage",
  "basketball-court-crew": "scorecard",
  "skatepark-stickers": "workshop",
  "ninja-obstacle-dojo": "dispatch",
  "detective-clue-club": "archive",
  "dragon-cloud-quest": "voyage",
  "axolotl-lagoon": "coast",
  "capybara-orange-spa": "salon",
  "bunny-carrot-garden": "garden",
  "pony-ribbon-rodeo": "festival",
  "butterfly-conservatory": "garden",
  "jellyfish-glow-garden": "lounge",
  "pizza-chef-club": "menu",
  "sushi-roll-studio": "atelier",
  "lemonade-market-day": "market",
  "cherry-picnic-bows": "confection",
  "storybook-library": "archive",
  "board-game-bonanza": "club",
  "mini-olympics-field-day": "scorecard",

  "party-pop":"confetti", "candy-dreams":"confection", "rainbow-bash":"festival", "playful-pals":"journal",
  "birthday-burst":"dispatch", "sweet-celebration":"menu", "super-star":"mission", "happy-dance":"stage",
  "magic-sparkle":"storybook", "celebration-time":"archive", "fun-fiesta":"market", "joyful-jamboree":"festival",
  "whimsical-wonder":"storybook", "cheerful-chaos":"atelier", "party-parade":"dispatch", "birthday-bliss":"garden",
  "sparkle-splash":"coast", "celebration-craze":"club", "happy-hooray":"confetti", "party-palooza":"stage",
  "birthday-bonanza":"workshop", "sweet-surprise":"confection", "party-perfect":"salon", "birthday-bash":"scorecard",
  "backyard-bug-explorer":"specimen", "junior-baker-studio":"menu", "little-firehouse":"dispatch",
  "dinosaur-dig-lab":"journal", "enchanted-forest-tea":"storybook", "outer-space-mission-control":"mission",
  "rainbow-art-studio":"atelier", "construction-crew-yard":"workshop", "undersea-mermaid-cove":"coast",
  "soccer-goal-celebration":"scorecard", "ballet-rehearsal-party":"stage", "superhero-training-hq":"dispatch",
  "race-car-pit-stop":"scorecard", "woodland-camping-night":"journal", "ice-cream-parlor":"confection",
  "farmyard-harvest":"market", "science-lab-spark":"specimen", "pirate-treasure-port":"voyage",
  "princess-garden-ball":"garden", "monster-truck-arena":"workshop", "mini-golf-clubhouse":"scorecard",
  "teddy-bear-picnic":"journal", "safari-expedition-camp":"specimen", "glow-dance-party":"club",
  "train-station-adventure":"dispatch", "airplane-travel-club":"voyage", "comic-book-creator":"atelier",
  "puppy-adoption-party":"journal", "beach-surf-shack":"coast", "winter-snow-lodge":"salon",
  "champagne-bow-soiree":"banquet", "garden-brunch-bloom":"garden", "rose-gold-rooftop-forty":"gallery",
  "parisian-patisserie-thirty":"menu", "coastal-white-linen-fifty":"coast", "disco-cowgirl-night":"club",
  "bookshop-candle-dinner-forty-five":"archive", "spa-day-sage-forty":"salon", "mahogany-wine-table-fifty-five":"menu",
  "sunset-pool-cabana-thirty-five":"coast", "sculptural-floral-forty":"gallery", "emerald-cocktail-forty-five":"lounge",
  "pearl-dinner-fifty":"banquet", "lavender-tea-sixty":"salon", "golden-jubilee-seventy":"archive",
  "whiskey-library-forty-five":"archive", "vintage-garage-forty":"workshop", "stadium-suite-fifty":"scorecard",
  "golf-club-forty-five":"scorecard", "backyard-bbq-fifty":"market", "craft-brew-hall-thirty":"menu",
  "black-tie-forty":"banquet", "bourbon-bluegrass-sixty":"stage", "coastal-sailing-fifty":"voyage",
  "modern-steakhouse-forty-five":"menu", "vinyl-listening-thirty-five":"lounge", "mountain-lodge-fifty-five":"journal",
  "poker-night-forty":"lounge", "classic-roadster-seventy":"workshop", "observatory-night-sixty-five":"mission",
  "mediterranean-dinner-forty":"banquet", "rooftop-city-lights-thirty":"club", "modern-minimal-fifty":"gallery",
  "tropical-sunset-forty-five":"coast", "art-gallery-cocktail-thirty-five":"gallery", "backyard-long-table-sixty":"garden",
  "eighties-retro-dance-forty":"club", "black-white-photo-fifty":"archive", "night-market-thirty":"market",
  "desert-dusk-fifty-five":"dunes", "paper-atelier-first-anniversary":"atelier", "woodland-table-fifth-anniversary":"garden",
  "tin-copper-tenth-anniversary":"workshop", "crystal-dinner-fifteenth-anniversary":"banquet", "porcelain-blue-twentieth-anniversary":"salon",
  "silver-night-twenty-fifth-anniversary":"gallery", "pearl-supper-thirtieth-anniversary":"menu", "ruby-gala-fortieth-anniversary":"stage",
  "golden-dinner-fiftieth-anniversary":"archive", "garden-vow-renewal-anniversary":"garden",
  "cotton-letter-second-anniversary":"journal", "leather-passport-third-anniversary":"voyage",
  "linen-sunday-fourth-anniversary":"menu", "iron-rose-sixth-anniversary":"garden",
  "copper-glow-seventh-anniversary":"lounge", "bronze-hour-eighth-anniversary":"gallery",
  "pottery-studio-ninth-anniversary":"atelier", "steel-skyline-eleventh-anniversary":"club",
  "silk-moon-twelfth-anniversary":"storybook", "lace-heirloom-thirteenth-anniversary":"archive",
  "ivory-orchid-fourteenth-anniversary":"gallery", "sapphire-evening-anniversary":"banquet",
  "emerald-conservatory-anniversary":"garden", "diamond-light-sixtieth-anniversary":"salon",
  "hydrangea-house-anniversary":"journal", "amalfi-postcard-anniversary":"coast",
  "stargazer-vows-anniversary":"mission", "vinyl-love-song-anniversary":"lounge",
  "desert-sunrise-anniversary":"dunes", "champagne-midnight-anniversary":"stage",
};
