// @ts-nocheck
"use client";

import { createSimpleCustomizePage } from "@/components/event-customize/createSimpleCustomizePage";

const AppointmentCustomizePage = createSimpleCustomizePage({
  slug: "doctor-appointment",
  displayName: "Doctor Appointment",
  category: "doctor_appointment",
  categoryLabel: "Doctor Appointment",
  defaultHero:
    "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1800&q=80",
  rsvpCopy: {
    menuTitle: "Reminders",
    menuDesc: "Confirmations, follow-ups, and deadlines.",
    editorTitle: "Reminders",
    toggleLabel: "Enable reminders",
    deadlineLabel: "Confirm by",
    helperText:
      "Patients see the confirmation deadline and can respond in the preview card.",
  },
  prefill: {
    title: "Office Visit with Dr. Ramirez",
    time: "10:30",
    city: "Chicago",
    state: "IL",
    venue: "Downtown Family Care",
    details:
      "Please arrive a few minutes early to complete intake. Bring your medication list and recent labs for a thorough review.",
    rsvpDeadline: (() => {
      const d = new Date();
      d.setDate(d.getDate() + 5);
      return d.toISOString().split("T")[0];
    })(),
    extra: {
      provider: "Dr. Elena Ramirez, MD",
      specialty: "Primary Care / Preventive Medicine",
      practice: "Downtown Family Care",
      visitType: "Annual checkup + follow-up",
      reason: "Blood pressure follow-up, medication review",
      prep: "Arrive 15 minutes early. Fasting not required. Bring your current meds list and home BP readings.",
      insurance: "BlueCross PPO #8472930, photo ID required",
      copay: "$25 copay due at check-in (card accepted)",
      documents: "Recent labs, imaging reports, referral letter if available",
      telehealth: "https://practice.example.com/visit",
      portal: "https://portal.example.com",
      contact: "(555) 123-4567",
      address: "123 Main St, Suite 400",
      parking: "Garage P2, validated parking; take elevator to 4th floor and check in at front desk",
      notes: "Masks optional. Please reschedule if you have fever or respiratory symptoms.",
    },
  },
  detailFields: [
    { key: "provider", label: "Provider", placeholder: "Dr. Ramirez, MD" },
    { key: "specialty", label: "Specialty", placeholder: "Primary Care / Cardiology" },
    { key: "practice", label: "Practice / Clinic", placeholder: "Downtown Family Care" },
    { key: "visitType", label: "Visit Type", placeholder: "Annual checkup / Follow-up" },
    { key: "reason", label: "Reason for Visit", placeholder: "Chest discomfort, med review" },
    { key: "prep", label: "Preparation", placeholder: "Arrive 15 min early, fasting, bring meds list", type: "textarea" },
    { key: "insurance", label: "Insurance / ID", placeholder: "BlueCross #1234567, photo ID required" },
    { key: "copay", label: "Copay / Payment", placeholder: "$25 copay, card accepted" },
    { key: "documents", label: "Documents to Bring", placeholder: "Lab results, imaging CDs, referral letter" },
    { key: "telehealth", label: "Telehealth Link", placeholder: "https://practice.example.com/visit" },
    { key: "portal", label: "Patient Portal", placeholder: "https://portal.example.com" },
    { key: "contact", label: "Office Phone", placeholder: "(555) 123-4567" },
    { key: "address", label: "Office Address / Suite", placeholder: "123 Main St, Suite 400" },
    { key: "parking", label: "Parking & Arrival", placeholder: "Garage P2, validated parking, check in at 4th floor" },
    { key: "notes", label: "Additional Notes", placeholder: "Masks optional; reschedule if symptomatic", type: "textarea" },
  ],
  themes: [
    {
      id: "sterile_white",
      name: "Sterile White",
      bg: "bg-gradient-to-br from-white via-slate-50 to-blue-50",
      text: "text-slate-900",
      accent: "text-blue-700",
      preview: "bg-gradient-to-r from-white via-slate-50 to-blue-50",
    },
    {
      id: "calm_clinic",
      name: "Calm Clinic",
      bg: "bg-gradient-to-br from-slate-100 via-cyan-50 to-slate-200",
      text: "text-slate-900",
      accent: "text-cyan-700",
      preview: "bg-gradient-to-r from-slate-100 via-cyan-50 to-slate-200",
    },
    {
      id: "deep_care",
      name: "Deep Care",
      bg: "bg-gradient-to-br from-slate-900 via-blue-900 to-sky-700",
      text: "text-white",
      accent: "text-sky-200",
      preview: "bg-gradient-to-r from-slate-900 via-blue-900 to-sky-700",
    },
    {
      id: "navy_trust",
      name: "Navy Trust",
      bg: "bg-gradient-to-br from-slate-950 via-slate-900 to-blue-800",
      text: "text-white",
      accent: "text-sky-100",
      preview: "bg-gradient-to-r from-slate-950 via-slate-900 to-blue-800",
    },
    {
      id: "mint_fresh",
      name: "Mint Fresh",
      bg: "bg-gradient-to-br from-emerald-50 via-teal-50 to-white",
      text: "text-slate-900",
      accent: "text-emerald-700",
      preview: "bg-gradient-to-r from-emerald-50 via-teal-50 to-white",
    },
    {
      id: "slate_minimal",
      name: "Slate Minimal",
      bg: "bg-gradient-to-br from-slate-100 via-slate-50 to-white",
      text: "text-slate-900",
      accent: "text-indigo-700",
      preview: "bg-gradient-to-r from-slate-100 via-slate-50 to-white",
    },
    {
      id: "skyline_clinic",
      name: "Skyline Clinic",
      bg: "bg-gradient-to-br from-sky-100 via-white to-slate-50",
      text: "text-slate-900",
      accent: "text-sky-700",
      preview: "bg-gradient-to-r from-sky-100 via-white to-slate-50",
    },
    {
      id: "lavender_relief",
      name: "Lavender Relief",
      bg: "bg-gradient-to-br from-indigo-50 via-purple-50 to-white",
      text: "text-slate-900",
      accent: "text-indigo-700",
      preview: "bg-gradient-to-r from-indigo-50 via-purple-50 to-white",
    },
    {
      id: "teal_trust",
      name: "Teal Trust",
      bg: "bg-gradient-to-br from-teal-900 via-emerald-800 to-teal-600",
      text: "text-white",
      accent: "text-emerald-200",
      preview: "bg-gradient-to-r from-teal-900 via-emerald-800 to-teal-600",
    },
    {
      id: "soft_sand",
      name: "Soft Sand",
      bg: "bg-gradient-to-br from-amber-50 via-amber-100 to-white",
      text: "text-amber-900",
      accent: "text-amber-700",
      preview: "bg-gradient-to-r from-amber-50 via-amber-100 to-white",
    },
    {
      id: "graphite_focus",
      name: "Graphite Focus",
      bg: "bg-gradient-to-br from-slate-900 via-slate-800 to-slate-700",
      text: "text-white",
      accent: "text-cyan-200",
      preview: "bg-gradient-to-r from-slate-900 via-slate-800 to-slate-700",
    },
    {
      id: "seafoam_calm",
      name: "Seafoam Calm",
      bg: "bg-gradient-to-br from-emerald-50 via-teal-100 to-white",
      text: "text-slate-900",
      accent: "text-emerald-700",
      preview: "bg-gradient-to-r from-emerald-50 via-teal-100 to-white",
    },
    {
      id: "copper_warmth",
      name: "Copper Warmth",
      bg: "bg-gradient-to-br from-amber-200 via-orange-100 to-rose-50",
      text: "text-amber-950",
      accent: "text-rose-800",
      preview: "bg-gradient-to-r from-amber-200 via-orange-100 to-rose-50",
    },
    {
      id: "charcoal_blue",
      name: "Charcoal Blue",
      bg: "bg-gradient-to-br from-slate-950 via-slate-900 to-blue-900",
      text: "text-white",
      accent: "text-blue-200",
      preview: "bg-gradient-to-r from-slate-950 via-slate-900 to-blue-900",
    },
    {
      id: "misty_green",
      name: "Misty Green",
      bg: "bg-gradient-to-br from-green-50 via-slate-50 to-white",
      text: "text-slate-900",
      accent: "text-emerald-700",
      preview: "bg-gradient-to-r from-green-50 via-slate-50 to-white",
    },
    {
      id: "clinical_gray",
      name: "Clinical Gray",
      bg: "bg-gradient-to-br from-gray-50 via-gray-100 to-white",
      text: "text-slate-900",
      accent: "text-blue-700",
      preview: "bg-gradient-to-r from-gray-50 via-gray-100 to-white",
    },
  ],
});

export default AppointmentCustomizePage;
