import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const repoRoot = process.cwd();
const readSource = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), "utf8");

test("/chat is the OpenAI-backed concierge workspace", () => {
  const appShell = readSource("src/app/AppShell.tsx");
  const page = readSource("src/app/chat/page.tsx");
  const client = readSource("src/app/chat/ConciergeChatClient.tsx");
  const extract = readSource("src/lib/concierge/extract.ts");
  const eventActions = readSource("src/lib/concierge/event-actions.ts");

  assert.match(page, /ConciergeChatClient/);
  assert.match(page, /getServerSession\(authOptions as any\)/);
  assert.match(page, /getUserByEmail\(email\)/);
  assert.match(page, /userFirstName=\{userFirstName\}/);
  assert.doesNotMatch(page, /isAdmin/);
  assert.doesNotMatch(page, /notFound\(/);

  assert.match(client, /What are we celebrating\?/);
  assert.match(client, /userFirstName\?: string \| null/);
  assert.match(client, /buildInitialAssistantPrompt/);
  assert.match(client, /Hi \$\{cleaned\}, what are we celebrating\?/);
  assert.match(client, /isOpeningAssistantPrompt/);
  assert.match(client, /text-4xl/);
  assert.match(client, /sm:text-6xl/);
  assert.match(client, /STUDIO_CATEGORY_TILES/);
  assert.match(client, /CHAT_STARTER_PROMPTS/);
  assert.match(client, /CELEBRATION_STARTER_TILES/);
  assert.match(client, /Tell me what you need to create/);
  assert.match(client, /Or let's start planning together from scratch/);
  assert.match(client, /\[&::placeholder\]:text-\[0\.82rem\]/);
  assert.match(client, /Birthday live card/);
  assert.match(client, /Wedding invitation/);
  assert.match(client, /Baby shower invite/);
  assert.match(client, /Game event page/);
  assert.match(client, /Bridal shower invite/);
  assert.doesNotMatch(client, /Watch party invite/);
  assert.ok(client.indexOf("Game event page") < client.indexOf("Baby shower invite"));
  assert.match(client, /label: "Baby shower invite"[\s\S]*?size: "desktopWide"/);
  assert.match(client, /col-span-2 aspect-\[2\.055\/1\]/);
  assert.match(client, /sm:col-span-2 sm:aspect-\[2\.055\/1\]/);
  assert.match(client, /aspect-square min-h-\[8\.25rem\]/);
  assert.doesNotMatch(client, /Upload invite or photo/);
  assert.doesNotMatch(client, /CHAT_STUDIO_GRID_COMPOSITION/);
  assert.doesNotMatch(client, /ChatStudioStarterGrid/);
  assert.doesNotMatch(client, /auto-rows-\[92px\]/);
  assert.doesNotMatch(client, /sm:auto-rows-\[130px\]/);
  assert.doesNotMatch(client, /md:auto-rows-\[155px\]/);
  assert.match(client, /max-w-\[90rem\]/);
  assert.doesNotMatch(client, /Choose a category and product to start/);
  assert.doesNotMatch(client, /Upload Your Invite/);
  assert.match(client, /PRODUCT_OPTIONS/);
  assert.match(client, /CATEGORY_OPTIONS/);
  assert.match(client, /categorySelectValueFromDraft/);
  assert.match(client, /handleCategoryChange/);
  assert.match(client, /Inferred category/);
  assert.match(client, /Gym Meet/);
  assert.match(client, /Set the event category to gym meet/);
  assert.doesNotMatch(client, /PRODUCT_CHOICE_PROMPT/);
  assert.doesNotMatch(client, /"What kind of product would you like to create\?"/);
  assert.match(client, /Live Card/);
  assert.match(client, /Flyer \/ Invite/);
  assert.match(client, /Event Page/);

  assert.match(client, /window\.addEventListener\("envitefy:chat:new", handleNewChatSession\)/);
  assert.doesNotMatch(client, /CreationThreadSummary/);
  assert.doesNotMatch(client, /CreationThreadsResponse/);
  assert.doesNotMatch(client, /fetch\("\/api\/creation\/threads"/);
  assert.doesNotMatch(client, /fetch\(`\/api\/creation\/threads\/\$\{encodeURIComponent\(id\)\}`/);
  assert.doesNotMatch(client, /Recent Chats/);
  assert.doesNotMatch(client, /isSidebarOpen/);
  assert.doesNotMatch(client, /isSidebarCollapsed/);
  assert.doesNotMatch(client, /useRouter/);
  assert.doesNotMatch(client, /router\.push\(`\/chat\?thread=/);

  assert.match(client, /fetch\("\/api\/creation\/intake"/);
  assert.match(client, /CreationSessionResumeResponse/);
  assert.match(client, /useSearchParams/);
  assert.match(client, /const threadId = searchParams\.get\("thread"\)/);
  assert.match(client, /restoreThread/);
  assert.match(client, /\/api\/creation\/intake\?threadId=/);
  assert.match(client, /setDraft\(restoredDraft\)/);
  assert.match(client, /CreationChatMessageSnapshot/);
  assert.match(client, /chatMessageFromSnapshot/);
  assert.match(client, /chatMessagesForPersistence/);
  assert.match(client, /json\.chatMessages\?\.length/);
  assert.match(client, /chatMessages: chatMessagesForPersistence/);
  assert.match(client, /activeContext: ConciergeActiveContext/);
  assert.match(client, /currentEventId: liveCardEventId/);

  assert.match(client, /type ConciergePhase =/);
  assert.match(client, /"ready_to_generate"/);
  assert.match(client, /"generating_card"/);
  assert.match(client, /"card_ready"/);
  assert.match(appShell, /const isChatPath = pathname\.replace\(\/\\\/\+\$\/, ""\) === "\/chat"/);
  assert.match(appShell, /className=\{isChatPath \? "h-\[100dvh\] overflow-hidden" : ""\}/);
  assert.match(client, /className="flex h-full min-h-0 w-full overflow-hidden/);
  assert.match(
    client,
    /className="relative flex h-full min-h-0 min-w-0 flex-1 flex-col overflow-hidden"/,
  );
  assert.doesNotMatch(client, /relative flex min-h-screen min-w-0 flex-1 flex-col overflow-y-auto/);
  assert.match(client, /shouldShowWorkspacePanel/);
  assert.match(client, /Boolean\(draft\)/);
  assert.match(client, /mobileView/);
  assert.match(client, /const isEmptyState =/);
  assert.match(client, /className="min-h-0 flex-1 overflow-y-auto/);
  assert.match(client, /setMobileView\("preview"\)/);
  assert.match(client, /Workspace Preview/);
  assert.doesNotMatch(client, /Share preview/);
  assert.doesNotMatch(client, /More preview actions/);
  assert.doesNotMatch(client, /Share2/);
  assert.doesNotMatch(client, /MoreVertical/);
  assert.match(client, /Invitation/);
  assert.match(client, /RSVP/);
  assert.match(client, /Guest List/);
  assert.match(client, /\/api\/events\/\$\{encodeURIComponent\(eventId\)\}\/rsvp/);
  assert.match(client, /rsvpPreview\.stats\.yes/);
  assert.match(client, /rsvpPreview\.responses\.map/);
  assert.match(client, /Generate workspace/);
  assert.match(client, /Regenerate version/);
  assert.match(client, /View product/);
  assert.match(client, /Open workspace/);
  assert.match(client, /Refine workspace/);
  assert.match(client, /sendGeneratedCardEdit/);
  assert.match(client, /fetch\(`\/api\/concierge\/events\/\$\{liveCardEventId\}\/message`/);

  assert.match(client, /NEXT_PUBLIC_CONCIERGE_FAST_UPLOADS/);
  assert.match(client, /FAST_UPLOAD_OCR_URL = "\/api\/ocr\?fast=1&turbo=1&timing=1"/);
  assert.match(client, /DEFAULT_UPLOAD_OCR_URL = "\/api\/ocr\?fast=0"/);
  assert.match(client, /ENABLE_FAST_UPLOAD_OCR \? FAST_UPLOAD_OCR_URL : DEFAULT_UPLOAD_OCR_URL/);
  assert.match(client, /aria-label="Upload file"/);
  assert.match(client, /aria-label="Use camera"/);
  assert.match(client, /bg-\[#fbf9ff\]/);
  assert.match(client, /border-\[#d8caff\]/);
  assert.match(client, /!text-\[#25183a\]/);
  assert.match(client, /!placeholder:text-\[#8b7ca6\]/);
  assert.match(client, /caret-\[#7c4dff\]/);
  assert.match(client, /inline-flex h-9 w-9/);
  assert.match(client, /\(input\.trim\(\) \|\| isListening\) && "text-\[#7c4dff\]"/);
  assert.match(client, /<Mic\s+className="size-6 text-current"/);
  assert.match(client, /<ArrowUp\s+className="size-6 text-current"/);
  assert.doesNotMatch(client, /aria-label=\{`Choose product: \$\{option\.label\}`\}/);
  assert.doesNotMatch(client, /choiceClassName/);
  assert.doesNotMatch(client, /choiceIconClassName/);
  assert.match(client, /<Paperclip className="size-6"/);
  assert.match(client, /<Camera className="size-6"/);
  assert.match(client, /Envitefy is thinking\.\.\./);
  assert.match(client, /isThinking && "animate-pulse"/);
  assert.match(client, /if \(!value\) return/);
  assert.doesNotMatch(client, /Choose Live card, Flyer \/ Invite, or Event page first/);
  assert.doesNotMatch(client, /mobileComposerSpacer/);
  assert.doesNotMatch(client, /composerBottomPadding/);
  assert.doesNotMatch(client, /md:fixed/);
  assert.doesNotMatch(client, /PanelTopDashed/);
  assert.doesNotMatch(client, /PartyFlyerIcon/);
  assert.doesNotMatch(client, /LandingPageIcon/);
  assert.doesNotMatch(client, /bg-\[#1F2023\]/);
  assert.doesNotMatch(client, /border-\[#444444\]/);
  assert.doesNotMatch(client, /placeholder:text-\[#9CA3AF\]/);
  assert.doesNotMatch(client, /bg-\[color:var\(--color-surface\)\]/);
  assert.doesNotMatch(client, /bg-\[color:var\(--color-primary\)\]/);
  assert.doesNotMatch(client, /aria-label=\{`Output: \$\{option\.label\}`\}/);
  assert.doesNotMatch(client, /isOutputLocked/);
  assert.doesNotMatch(client, /aria-label="Product menu"/);
  assert.doesNotMatch(client, /Choose output/);
  assert.doesNotMatch(client, /Add source/);
  assert.doesNotMatch(client, /setIsProductMenuOpen/);
  assert.doesNotMatch(client, /Suggest date/);
  assert.doesNotMatch(client, /My place/);
  assert.doesNotMatch(client, /Make it elegant/);

  assert.match(client, /action: "save"/);
  assert.match(client, /persistSession: true/);
  assert.doesNotMatch(client, /await generateProductForDraft\(json\.draft\)/);
  assert.doesNotMatch(client, /fetch\("\/api\/history"/);
  assert.doesNotMatch(client, /buildConciergeHistoryPayload\(draft\)/);
  assert.doesNotMatch(client, /@google\/genai/);
  assert.doesNotMatch(client, /GEMINI_API_KEY/);
  assert.doesNotMatch(client, /GoogleGenAI/);

  assert.match(extract, /import OpenAI from "openai";/);
  assert.match(extract, /process\.env\.OPENAI_API_KEY/);
  assert.match(extract, /client\.chat\.completions\.create/);
  assert.match(eventActions, /import OpenAI from "openai";/);
  assert.match(eventActions, /process\.env\.OPENAI_API_KEY/);
});

test("/cht typo route is not present", () => {
  assert.equal(fs.existsSync(path.join(repoRoot, "src/app/cht/page.tsx")), false);
});
