import { Cake, Gift, Heart, PartyPopper, WandSparkles } from "lucide-react";
import type { BirthdayPresetAgeGroup, BirthdayPresetSeed } from "./studio-workspace-types";

export function svgThumbnail(label: string, from: string, to: string) {
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="720" height="960" viewBox="0 0 720 960">
      <defs>
        <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="${from}" />
          <stop offset="100%" stop-color="${to}" />
        </linearGradient>
      </defs>
      <rect width="720" height="960" rx="56" fill="url(#g)" />
      <circle cx="610" cy="120" r="96" fill="rgba(255,255,255,0.18)" />
      <circle cx="120" cy="810" r="120" fill="rgba(255,255,255,0.12)" />
      <rect x="76" y="92" width="568" height="776" rx="44" fill="rgba(255,255,255,0.16)" stroke="rgba(255,255,255,0.35)" />
      <text x="92" y="640" fill="white" font-size="70" font-family="Arial, sans-serif" font-weight="700">${label}</text>
      <text x="92" y="718" fill="rgba(255,255,255,0.82)" font-size="26" font-family="Arial, sans-serif">Envitefy Studio preset</text>
    </svg>
  `;
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

export const BIRTHDAY_PRESET_LIBRARY: Record<
  BirthdayPresetAgeGroup,
  {
    label: string;
    female: BirthdayPresetSeed[];
    male: BirthdayPresetSeed[];
  }
> = {
  kids: {
    label: "Kids",
    female: [
      {
        id: "kids-princess-castle",
        name: "Princess Castle",
        description: "Royal pinks, crowns, and storybook sparkle.",
        icon: WandSparkles,
        from: "#ff8cc6",
        to: "#ffcadf",
      },
      {
        id: "kids-unicorn-rainbow",
        name: "Unicorn Rainbow",
        description: "Pastel rainbows, clouds, and candy-color shine.",
        icon: PartyPopper,
        from: "#a855f7",
        to: "#f9a8d4",
      },
      {
        id: "kids-mermaid-lagoon",
        name: "Mermaid Lagoon",
        description: "Ocean sparkle, shells, and aqua birthday magic.",
        icon: Heart,
        from: "#06b6d4",
        to: "#67e8f9",
      },
      {
        id: "kids-fairy-garden",
        name: "Fairy Garden",
        description: "Butterflies, florals, and enchanted meadow charm.",
        icon: WandSparkles,
        from: "#22c55e",
        to: "#f9a8d4",
      },
      {
        id: "kids-kawaii-kitty",
        name: "Kawaii Kitty",
        description: "Cute bows, sweet pinks, and playful kitten vibes.",
        icon: Gift,
        from: "#fb7185",
        to: "#fbcfe8",
      },
      {
        id: "kids-ballet-sparkle",
        name: "Ballet Sparkle",
        description: "Soft blush tones with tutus and stage lights.",
        icon: Cake,
        from: "#f9a8d4",
        to: "#fde68a",
      },
    ],
    male: [
      {
        id: "kids-superhero-city",
        name: "Superhero City",
        description: "Comic-book energy with bold primaries and action bursts.",
        icon: WandSparkles,
        from: "#2563eb",
        to: "#ef4444",
      },
      {
        id: "kids-dino-adventure",
        name: "Dino Adventure",
        description: "Jurassic greens, fossils, and roaring fun.",
        icon: PartyPopper,
        from: "#16a34a",
        to: "#84cc16",
      },
      {
        id: "kids-space-explorer",
        name: "Space Explorer",
        description: "Planets, rockets, and galaxy glow.",
        icon: WandSparkles,
        from: "#0f172a",
        to: "#3b82f6",
      },
      {
        id: "kids-monster-trucks",
        name: "Monster Trucks",
        description: "Mud splashes, ramps, and loud party energy.",
        icon: Gift,
        from: "#f97316",
        to: "#ef4444",
      },
      {
        id: "kids-soccer-stars",
        name: "Soccer Stars",
        description: "Stadium green, trophies, and all-star party action.",
        icon: Cake,
        from: "#16a34a",
        to: "#22c55e",
      },
      {
        id: "kids-construction-zone",
        name: "Construction Zone",
        description: "Bulldozers, caution stripes, and build-it fun.",
        icon: Heart,
        from: "#facc15",
        to: "#f97316",
      },
    ],
  },
  teens: {
    label: "Teen",
    female: [
      {
        id: "teens-coquette-pink",
        name: "Coquette Pink",
        description: "Bows, glossy pinks, and soft glam details.",
        icon: WandSparkles,
        from: "#ec4899",
        to: "#fbcfe8",
      },
      {
        id: "teens-disco-cowgirl",
        name: "Disco Cowgirl",
        description: "Chrome sparkle, western flair, and party shine.",
        icon: PartyPopper,
        from: "#f59e0b",
        to: "#f472b6",
      },
      {
        id: "teens-pop-star-night",
        name: "Pop Star Night",
        description: "Stage lights, glam posters, and concert energy.",
        icon: WandSparkles,
        from: "#7c3aed",
        to: "#ec4899",
      },
      {
        id: "teens-spa-sleepover",
        name: "Spa Sleepover",
        description: "Silk robes, beauty bar details, and chill luxury.",
        icon: Gift,
        from: "#f9a8d4",
        to: "#c4b5fd",
      },
      {
        id: "teens-cherry-y2k",
        name: "Cherry Y2K",
        description: "Retro gloss, cherries, and throwback internet cool.",
        icon: Cake,
        from: "#ef4444",
        to: "#fb7185",
      },
      {
        id: "teens-beach-club",
        name: "Beach Club Glow",
        description: "Sunset tones, palm energy, and coastal sparkle.",
        icon: Heart,
        from: "#fb7185",
        to: "#f59e0b",
      },
    ],
    male: [
      {
        id: "teens-gaming-arena",
        name: "Gaming Arena",
        description: "Neon glow, leaderboard graphics, and tournament hype.",
        icon: WandSparkles,
        from: "#111827",
        to: "#22c55e",
      },
      {
        id: "teens-sneaker-drop",
        name: "Sneaker Drop",
        description: "Streetwear styling with clean hype-release energy.",
        icon: PartyPopper,
        from: "#111827",
        to: "#e5e7eb",
      },
      {
        id: "teens-streetball-night",
        name: "Streetball Night",
        description: "Court lights, bold type, and all-star edge.",
        icon: WandSparkles,
        from: "#ea580c",
        to: "#1d4ed8",
      },
      {
        id: "teens-anime-battle",
        name: "Anime Battle",
        description: "High-contrast action panels with epic energy.",
        icon: Gift,
        from: "#7c3aed",
        to: "#2563eb",
      },
      {
        id: "teens-racing-league",
        name: "Racing League",
        description: "Checkered flags, speed lines, and track-night style.",
        icon: Cake,
        from: "#ef4444",
        to: "#111827",
      },
      {
        id: "teens-soccer-finals",
        name: "Soccer Finals",
        description: "Championship graphics with match-day intensity.",
        icon: Heart,
        from: "#16a34a",
        to: "#0f172a",
      },
    ],
  },
  "young-adults": {
    label: "Young Adult",
    female: [
      {
        id: "young-disco-glam",
        name: "Disco Glam",
        description: "Mirror-ball sparkle with late-night party energy.",
        icon: WandSparkles,
        from: "#7c3aed",
        to: "#f472b6",
      },
      {
        id: "young-coastal-brunch",
        name: "Coastal Brunch",
        description: "Soft blue skies, citrus notes, and chic daylight vibes.",
        icon: PartyPopper,
        from: "#38bdf8",
        to: "#fde68a",
      },
      {
        id: "young-satin-champagne",
        name: "Satin Champagne",
        description: "Glossy neutrals, candlelight, and elevated dinner-party style.",
        icon: WandSparkles,
        from: "#e7cfa3",
        to: "#f8e7c8",
      },
      {
        id: "young-western-disco",
        name: "Western Disco",
        description: "Boots, shimmer, and polished rodeo-night glamour.",
        icon: Gift,
        from: "#f59e0b",
        to: "#ec4899",
      },
      {
        id: "young-garden-soiree",
        name: "Garden Soiree",
        description: "Florals, string lights, and romantic outdoor hosting.",
        icon: Cake,
        from: "#22c55e",
        to: "#f9a8d4",
      },
      {
        id: "young-sunset-rooftop",
        name: "Sunset Rooftop",
        description: "Skyline tones with stylish after-work birthday energy.",
        icon: Heart,
        from: "#fb7185",
        to: "#7c3aed",
      },
    ],
    male: [
      {
        id: "young-rooftop-neon",
        name: "Rooftop Neon",
        description: "City-night glow with modern lounge styling.",
        icon: WandSparkles,
        from: "#111827",
        to: "#3b82f6",
      },
      {
        id: "young-retro-arcade",
        name: "Retro Arcade",
        description: "Pixel graphics, neon cabinets, and playful nostalgia.",
        icon: PartyPopper,
        from: "#0f172a",
        to: "#a855f7",
      },
      {
        id: "young-casino-royale",
        name: "Casino Royale",
        description: "Black, red, and gold with sleek nightlife appeal.",
        icon: WandSparkles,
        from: "#111827",
        to: "#dc2626",
      },
      {
        id: "young-formula-night",
        name: "Formula Night",
        description: "Fast-track styling with premium racing cues.",
        icon: Gift,
        from: "#dc2626",
        to: "#111827",
      },
      {
        id: "young-all-white-party",
        name: "All-White Party",
        description: "Minimal luxe with crisp monochrome celebration energy.",
        icon: Cake,
        from: "#d1d5db",
        to: "#ffffff",
      },
      {
        id: "young-yacht-club",
        name: "Yacht Club",
        description: "Navy, cream, and polished resort-party vibes.",
        icon: Heart,
        from: "#1d4ed8",
        to: "#f8fafc",
      },
    ],
  },
  adults: {
    label: "Adult",
    female: [
      {
        id: "adults-amalfi-citrus",
        name: "Amalfi Citrus",
        description: "Lemon tones, Mediterranean polish, and summer dinner charm.",
        icon: WandSparkles,
        from: "#facc15",
        to: "#60a5fa",
      },
      {
        id: "adults-rose-gold-dinner",
        name: "Rose Gold Dinner",
        description: "Warm metallics with elegant tablescape energy.",
        icon: PartyPopper,
        from: "#fda4af",
        to: "#f5d0fe",
      },
      {
        id: "adults-black-tie-glam",
        name: "Black Tie Glam",
        description: "Sharp evening styling with a luxe editorial edge.",
        icon: WandSparkles,
        from: "#111827",
        to: "#f59e0b",
      },
      {
        id: "adults-boho-sunset",
        name: "Boho Sunset",
        description: "Terracotta tones, pampas details, and warm celebration light.",
        icon: Gift,
        from: "#ea580c",
        to: "#f59e0b",
      },
      {
        id: "adults-garden-party",
        name: "Garden Party",
        description: "Fresh florals, greenery, and polished outdoor hosting.",
        icon: Cake,
        from: "#22c55e",
        to: "#e9d5ff",
      },
      {
        id: "adults-tropical-luxe",
        name: "Tropical Luxe",
        description: "Palm leaves, resort details, and bold celebratory color.",
        icon: Heart,
        from: "#0f766e",
        to: "#f97316",
      },
    ],
    male: [
      {
        id: "adults-whiskey-lounge",
        name: "Whiskey Lounge",
        description: "Moody amber lighting with classic lounge depth.",
        icon: WandSparkles,
        from: "#7c2d12",
        to: "#111827",
      },
      {
        id: "adults-cigar-cards",
        name: "Cigar & Cards",
        description: "Dark wood, card-table styling, and old-school cool.",
        icon: PartyPopper,
        from: "#1f2937",
        to: "#7c2d12",
      },
      {
        id: "adults-backyard-bbq",
        name: "Backyard BBQ",
        description: "Relaxed cookout energy with bold Americana flavor.",
        icon: WandSparkles,
        from: "#dc2626",
        to: "#f59e0b",
      },
      {
        id: "adults-golf-classic",
        name: "Golf Classic",
        description: "Country-club greens with refined daytime polish.",
        icon: Gift,
        from: "#166534",
        to: "#65a30d",
      },
      {
        id: "adults-black-tie-club",
        name: "Black Tie Club",
        description: "Formal monochrome styling with understated luxury.",
        icon: Cake,
        from: "#111827",
        to: "#4b5563",
      },
      {
        id: "adults-vintage-vinyl",
        name: "Vintage Vinyl",
        description: "Record-bar warmth with retro music-night personality.",
        icon: Heart,
        from: "#7c3aed",
        to: "#f97316",
      },
    ],
  },
  milestones: {
    label: "Milestone",
    female: [
      {
        id: "milestones-golden-gala",
        name: "Golden Gala",
        description: "Big-night glamour designed for a statement birthday.",
        icon: WandSparkles,
        from: "#ca8a04",
        to: "#fef08a",
      },
      {
        id: "milestones-diamond-dinner",
        name: "Diamond Dinner",
        description: "Crystal shine, candlelight, and luxe celebration polish.",
        icon: PartyPopper,
        from: "#cbd5e1",
        to: "#f8fafc",
      },
      {
        id: "milestones-parisian-chic",
        name: "Parisian Chic",
        description: "Soft black-and-cream styling with fashion-week elegance.",
        icon: WandSparkles,
        from: "#111827",
        to: "#f5e6c8",
      },
      {
        id: "milestones-bloom-brunch",
        name: "Bloom Brunch",
        description: "Fresh florals and champagne daylight celebration energy.",
        icon: Gift,
        from: "#f9a8d4",
        to: "#fde68a",
      },
      {
        id: "milestones-palm-springs",
        name: "Palm Springs Luxe",
        description: "Resort color, playful elegance, and modern celebration cool.",
        icon: Cake,
        from: "#fb7185",
        to: "#38bdf8",
      },
      {
        id: "milestones-pearl-soiree",
        name: "Pearl Soiree",
        description: "Soft ivory layers with timeless milestone sophistication.",
        icon: Heart,
        from: "#f8fafc",
        to: "#d4d4d8",
      },
    ],
    male: [
      {
        id: "milestones-great-gatsby",
        name: "Great Gatsby",
        description: "Art deco gold, black lacquer, and major-birthday drama.",
        icon: WandSparkles,
        from: "#111827",
        to: "#ca8a04",
      },
      {
        id: "milestones-bourbon-reserve",
        name: "Bourbon Reserve",
        description: "Warm barrel tones with elevated speakeasy mood.",
        icon: PartyPopper,
        from: "#7c2d12",
        to: "#f59e0b",
      },
      {
        id: "milestones-casino-black-gold",
        name: "Casino Black Gold",
        description: "High-contrast luxury with celebratory nightlife edge.",
        icon: WandSparkles,
        from: "#111827",
        to: "#facc15",
      },
      {
        id: "milestones-yacht-dinner",
        name: "Yacht Dinner",
        description: "Navy-and-ivory styling with polished waterfront appeal.",
        icon: Gift,
        from: "#1d4ed8",
        to: "#f8fafc",
      },
      {
        id: "milestones-golf-scotch",
        name: "Golf & Scotch",
        description: "Classic club styling for a relaxed upscale milestone.",
        icon: Cake,
        from: "#166534",
        to: "#92400e",
      },
      {
        id: "milestones-havana-night",
        name: "Havana Night",
        description: "Rich tropical tones with smooth evening energy.",
        icon: Heart,
        from: "#b45309",
        to: "#0f766e",
      },
    ],
  },
};