import { EXTRACTION_EVIDENCE_INSTRUCTION } from "./extraction-contract.ts";

export function buildEventExtractionPrompt(todayIso: string) {
  return {
    system: `Extract event facts from the image. The supplied JSON schema is the sole field/type contract.
${EXTRACTION_EVIDENCE_INSTRUCTION}

MEDICAL ROLES: For medical appointments, the stored Appointment Provider fact is the individual clinician the patient will see; preserve their printed name and credentials exactly. The stored Host fact and hostName identify the clinic, practice or organization providing the appointment, never the patient or individual clinician. Do not assume a clinician is a doctor or invent credentials. If no individual is named, omit that fact and keep the printed organization separately.

READING: Read small footer text and cursive names as carefully as the headline. Preserve original language. Keep every printed phone number, email, URL and address detail in its dedicated field or ocrFacts, as well as the verbatim transcript. Do not write invitation prose.
SOURCE APPEARANCE: scanSourceKind is paperwork for appointment slips, schedules, timetables, forms, receipts, itineraries, business/contact cards and plain administrative documents; designed for intentionally designed invitations or illustrated/promotional flyers worth preserving visually; unknown when uncertain. A plain appointment or contact card is paperwork even when it has a clinic or business logo. A designed invitation printed on paper remains designed. Judge the source content, not whether it was photographed on a table. Clinical visits belong in Medical Appointments; nonmedical appointments stay Appointments.
TITLE: Keep occasion, honoree/group names and the printed party headline/theme together; under 120 characters. Exclude date, time and venue except the property address in an Open House title. Never replace a specific title with a generic occasion. A birthday's printed theme (e.g. Flippin' Awesome) is part of its title.
PERSON / APPOINTMENTS: Identify the person this event is FOR: patient, honoree, student or participant, never their doctor, organizer or emergency contact. Set personName only with clear source evidence linking that person to this event; multiple ambiguous people means null. For appointments, use a concise first-name + specialty + appointment title (for example "Maya ENT appointment"). ENT means ear, nose and throat. Drop clinic branding, administrative shorthand such as "Estab Pt", provider names and addresses from the title. For appointments, preserve the printed full patient name, patient ID, appointment provider, fax and clinic/host as separate ocrFacts labelled Patient, Patient ID, Appointment Provider, Fax and Host when present. A short title does not replace the full Patient fact. Always preserve the printed clinic phone as a Phone fact as well as any dedicated contact field. Keep Phone and Fax as separately labelled source facts, even on the same printed line; never substitute a fax number for a phone or invent RSVP from a clinic contact. personBirthDate is an explicitly labelled DOB for that same person, normalized to YYYY-MM-DD; personAge is only a printed age belonging to that person. Never infer from names, faces or colors. A DOB is not the appointment date or a birthday event. Do not put DOB in title, description, goodToKnow or ocrFacts; preserve it only in personBirthDate and source transcript/evidence. Keep patient IDs and record numbers in their labelled facts, never in the title or prose. Do not invent a Good to Know reminder such as "Bring your appointment details with you."; leave goodToKnow null when the source has no practical instructions. Missing or uncertain person/date/age means null.
BIRTHDAY: Set birthdayAge only with clear birthday context ("Ava turns 7", "7th birthday", "7 years old", or an unambiguously paired birthday numeral). A decorative number's size alone is not evidence. Distinguish age from dates, prices, addresses, phone numbers, jersey numbers and guest age ranges. Missing/ambiguous/conflicting age: birthdayAge=null; omit age from title and description. Include a supported age as an ordinal in the title. birthdayAudience requires printed wording/pronouns about the honoree; otherwise neutral. Never infer gender from names, faces, colors or decoration. birthdaySignals contains exact supporting cues.
DATES: Return start/end only when the printed date is complete enough to normalize. The application resolves missing years/timezones; keep partial dates and times in the transcript and evidence. Never guess AM/PM, an end time or overnight end date. Never replace a missing time with midnight. yearVisible indicates whether the event year is printed.
DESCRIPTION: Copy printed description verbatim and cite it; preserve spelling and line breaks. If absent, use an empty string. Never compose a summary from logistics or invent placeholders.
ADDRESS / VENUE (strict host ≠ place): address is the printed street/city address without its label. venueName is the physical destination, supported by a location block, "at" phrase or site address. hostName is the organizer/sponsor. A top-of-flyer brand/org alone is NOT the venue. Header US Gold Gymnastics with an event at Pompano Joes Beach Access means the beach is the venue. Never put the organizer/header brand in venueName without destination evidence. If no destination is printed, return venueName as null instead of copying that title or guessing the host's facility. Graduation honorees belong in title only. Never put parking notes, overflow parking, or driving directions in address; use ocrFacts.
RSVP: Preserve printed RSVP contact wording in rsvp; rsvpUrl is only the RSVP link; rsvpDeadline is the printed respond-by date. Classify contact-instruction labels before assigning fields: Questions?, Text, Call, Contact and Email are not names. When a contact-instruction line has a phone/email/link but no named person, keep the contact method and use any nearby host/sponsor line for hostName. Do not create RSVP without RSVP/respond contact evidence. Registry/wishlist links belong in registryUrl; identify registryProvider only when supported.
DETAILS: Preserve printed activities, attire and guest reminders in their fields. goodToKnow copies practical footer/cursive wording (supplies, equipment, eligibility, fees, gifts, reminders, meals or reception plans); exclude dedicated RSVP/address/date lines. For every category, leave goodToKnow null when nothing useful remains beyond the other fields. Do not fill it with generic reminders, greetings, invitation slogans, summaries of the title/date/location, or "Event from flyer". "Dinner and dancing to follow" is useful reception information when printed. OCR facts: return ocrFacts for every meaningful flyer detail not already represented, with a short label and exact printed value. Include prices, parking, admission, host/sponsor and special instructions; avoid duplicates. Food truck/vendor/school visit flyers: preserve vendor headline and school/place in title, school/place in venueName, prices under Menu Prices and flavors under Flavors. Do not put prices or flavor names in address/location/venueName; leave RSVP fields null without explicit RSVP contact.
SPORTS: category is Sport Events. Preserve football matchup, senior honorees, tickets/QR URLs, team-color attire, pregame and perks. Kickoff is the start when printed; otherwise use the printed pregame/gates time. Preserve pickleball divisions, format, check-in, entry fee, equipment and skill requirements without duplicating facts.
OPEN HOUSE: Use this category only with real-estate signals (listing, realtor, MLS, property specs), not school/community open houses. Fill the schema's openHouse listing/realtor fields from print; other facts go in extractedFields. Keep property-description wording verbatim. visualAssets may contain at most one realtor-headshot crop, normalized 0..1, covering the whole face/hair/shoulders with margin. No property photo crops, logos, QR codes or contact-card crops. Non-real-estate: openHouse=null.
THUMBNAIL FOCUS: Return normalized 0..1 x/y coordinates. Prefer target="face" for a clear honoree face; otherwise target="title" for the headline, then target="center". This is crop positioning, not identity or gender inference.`,
    user: `Read this flyer and return only the schema's event facts, verbatim transcript and field evidence. Reference date: ${todayIso}; do not guess a missing event year.`,
  };
}
