import { EXTRACTION_EVIDENCE_INSTRUCTION } from "./extraction-contract.ts";

export function buildEventExtractionPrompt(todayIso: string) {
  return {
    system: `Extract event facts from the image. The supplied JSON schema is the sole field/type contract.
${EXTRACTION_EVIDENCE_INSTRUCTION}

READING: Read small footer text and cursive names as carefully as the headline. Preserve original language. Keep every printed phone number, email, URL and address detail in its dedicated field or ocrFacts, as well as the verbatim transcript. Do not write invitation prose.
TITLE: Keep occasion, honoree/group names and the printed party headline/theme together; under 120 characters. Exclude date, time and venue except the property address in an Open House title. Never replace a specific title with a generic occasion. A birthday's printed theme (e.g. Flippin' Awesome) is part of its title.
BIRTHDAY: Set birthdayAge only with clear birthday context ("Ava turns 7", "7th birthday", "7 years old", or an unambiguously paired birthday numeral). A decorative number's size alone is not evidence. Distinguish age from dates, prices, addresses, phone numbers, jersey numbers and guest age ranges. Missing/ambiguous/conflicting age: birthdayAge=null; omit age from title and description. Include a supported age as an ordinal in the title. birthdayAudience requires printed wording/pronouns about the honoree; otherwise neutral. Never infer gender from names, faces, colors or decoration. birthdaySignals contains exact supporting cues.
DATES: Return start/end only when the printed date is complete enough to normalize. The application resolves missing years/timezones; keep partial dates and times in the transcript and evidence. Never guess AM/PM, an end time or overnight end date. Never replace a missing time with midnight. yearVisible indicates whether the event year is printed.
DESCRIPTION: Copy printed description verbatim and cite it; preserve spelling and line breaks. If absent, use an empty string. Never compose a summary from logistics or invent placeholders.
ADDRESS / VENUE (strict host ≠ place): address is the printed street/city address without its label. venueName is the physical destination, supported by a location block, "at" phrase or site address. hostName is the organizer/sponsor. A top-of-flyer brand/org alone is NOT the venue. Header US Gold Gymnastics with an event at Pompano Joes Beach Access means the beach is the venue. Never put the organizer/header brand in venueName without destination evidence. If no destination is printed, return venueName as null instead of copying that title or guessing the host's facility. Graduation honorees belong in title only. Never put parking notes, overflow parking, or driving directions in address; use ocrFacts.
RSVP: Preserve printed RSVP contact wording in rsvp; rsvpUrl is only the RSVP link; rsvpDeadline is the printed respond-by date. Classify contact-instruction labels before assigning fields: Questions?, Text, Call, Contact and Email are not names. When a contact-instruction line has a phone/email/link but no named person, keep the contact method and use any nearby host/sponsor line for hostName. Do not create RSVP without RSVP/respond contact evidence. Registry/wishlist links belong in registryUrl; identify registryProvider only when supported.
DETAILS: Preserve printed activities, attire and guest reminders in their fields. goodToKnow copies practical footer/cursive wording (supplies, equipment, eligibility, fees, gifts, reminders); exclude dedicated RSVP/address/date lines. OCR facts: return ocrFacts for every meaningful flyer detail not already represented, with a short label and exact printed value. Include prices, parking, admission, host/sponsor and special instructions; avoid duplicates. Food truck/vendor/school visit flyers: preserve vendor headline and school/place in title, school/place in venueName, prices under Menu Prices and flavors under Flavors. Do not put prices or flavor names in address/location/venueName; leave RSVP fields null without explicit RSVP contact.
SPORTS: category is Sport Events. Preserve football matchup, senior honorees, tickets/QR URLs, team-color attire, pregame and perks. Kickoff is the start when printed; otherwise use the printed pregame/gates time. Preserve pickleball divisions, format, check-in, entry fee, equipment and skill requirements without duplicating facts.
OPEN HOUSE: Use this category only with real-estate signals (listing, realtor, MLS, property specs), not school/community open houses. Fill the schema's openHouse listing/realtor fields from print; other facts go in extractedFields. Keep property-description wording verbatim. visualAssets may contain at most one realtor-headshot crop, normalized 0..1, covering the whole face/hair/shoulders with margin. No property photo crops, logos, QR codes or contact-card crops. Non-real-estate: openHouse=null.
THUMBNAIL FOCUS: Return normalized 0..1 x/y coordinates. Prefer target="face" for a clear honoree face; otherwise target="title" for the headline, then target="center". This is crop positioning, not identity or gender inference.`,
    user: `Read this flyer and return only the schema's event facts, verbatim transcript and field evidence. Reference date: ${todayIso}; do not guess a missing event year.`,
  };
}
