// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/campaigns" | "/admin/emails" | "/admin/emails/event-share" | "/admin/emails/password-changed" | "/admin/emails/password-reset" | "/calendar" | "/contact" | "/event" | "/event/[id]" | "/event/appointments" | "/event/appointments/customize" | "/event/baby-showers" | "/event/baby-showers/customize" | "/event/birthdays" | "/event/birthdays/customize" | "/event/cheerleading/customize" | "/event/dance-ballet/customize" | "/event/football" | "/event/football-season/customize" | "/event/football/customize" | "/event/gender-reveal" | "/event/gender-reveal/customize" | "/event/general" | "/event/general/customize" | "/event/gymnastics" | "/event/gymnastics/customize" | "/event/new" | "/event/soccer/customize" | "/event/special-events" | "/event/special-events/customize" | "/event/sport-events" | "/event/sport-events/customize" | "/event/weddings" | "/event/weddings/[id]/registry" | "/event/weddings/customize" | "/event/weddings/customize/[id]" | "/event/workshops/customize" | "/faq" | "/football" | "/forgot" | "/gymnastics" | "/how-it-works" | "/landing" | "/open" | "/privacy" | "/registry/[id]" | "/reset" | "/settings" | "/smart-signup-form" | "/smart-signup-form/[id]" | "/subscription" | "/templates/signup" | "/terms" | "/verify-request" | "/who-its-for"
type AppRouteHandlerRoutes = "/api/admin/campaigns" | "/api/admin/campaigns/send" | "/api/admin/stats" | "/api/admin/users/filter" | "/api/admin/users/search" | "/api/auth/[...nextauth]" | "/api/auth/forgot" | "/api/auth/reset" | "/api/auth/signup" | "/api/billing/stripe/checkout" | "/api/billing/stripe/portal" | "/api/billing/stripe/sync" | "/api/blob/[...path]" | "/api/calendars" | "/api/contact" | "/api/dashboard" | "/api/dashboard/enrich-next-event" | "/api/db-test" | "/api/debug" | "/api/debug-db" | "/api/debug-egress" | "/api/debug-env" | "/api/debug-ocr" | "/api/debug-vision" | "/api/debug/history" | "/api/debug/oauth-tokens" | "/api/debug/promo" | "/api/events/[id]/rsvp" | "/api/events/[id]/thumbnail" | "/api/events/[id]/unlock" | "/api/events/[id]/update-theme" | "/api/events/google" | "/api/events/google/bulk" | "/api/events/ics/bulk" | "/api/events/outlook" | "/api/events/outlook/bulk" | "/api/events/share" | "/api/events/share/accept" | "/api/events/share/remove" | "/api/google/auth" | "/api/google/callback" | "/api/google/insert" | "/api/health" | "/api/history" | "/api/history/[id]" | "/api/history/[id]/carpool" | "/api/history/[id]/signup" | "/api/history/[id]/volunteer" | "/api/ics" | "/api/ingest" | "/api/maps/static" | "/api/meet/[eventId]" | "/api/net" | "/api/oauth/disconnect" | "/api/ocr" | "/api/outlook/auth" | "/api/outlook/callback" | "/api/outlook/insert" | "/api/parse/[eventId]" | "/api/parse/[eventId]/enrich" | "/api/promo/gift" | "/api/promo/redeem" | "/api/registry/add" | "/api/registry/autofill" | "/api/registry/claim" | "/api/registry/list" | "/api/rsvp/attendance" | "/api/stripe/webhook" | "/api/templates/signup" | "/api/upload" | "/api/uploads/birthday-asset" | "/api/user/change-password" | "/api/user/feature-visibility" | "/api/user/profile" | "/api/user/subscription"
type PageRoutes = never
type LayoutRoutes = "/" | "/contact" | "/forgot" | "/open" | "/privacy" | "/reset" | "/terms"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/campaigns": {}
  "/admin/emails": {}
  "/admin/emails/event-share": {}
  "/admin/emails/password-changed": {}
  "/admin/emails/password-reset": {}
  "/api/admin/campaigns": {}
  "/api/admin/campaigns/send": {}
  "/api/admin/stats": {}
  "/api/admin/users/filter": {}
  "/api/admin/users/search": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/forgot": {}
  "/api/auth/reset": {}
  "/api/auth/signup": {}
  "/api/billing/stripe/checkout": {}
  "/api/billing/stripe/portal": {}
  "/api/billing/stripe/sync": {}
  "/api/blob/[...path]": { "path": string[]; }
  "/api/calendars": {}
  "/api/contact": {}
  "/api/dashboard": {}
  "/api/dashboard/enrich-next-event": {}
  "/api/db-test": {}
  "/api/debug": {}
  "/api/debug-db": {}
  "/api/debug-egress": {}
  "/api/debug-env": {}
  "/api/debug-ocr": {}
  "/api/debug-vision": {}
  "/api/debug/history": {}
  "/api/debug/oauth-tokens": {}
  "/api/debug/promo": {}
  "/api/events/[id]/rsvp": { "id": string; }
  "/api/events/[id]/thumbnail": { "id": string; }
  "/api/events/[id]/unlock": { "id": string; }
  "/api/events/[id]/update-theme": { "id": string; }
  "/api/events/google": {}
  "/api/events/google/bulk": {}
  "/api/events/ics/bulk": {}
  "/api/events/outlook": {}
  "/api/events/outlook/bulk": {}
  "/api/events/share": {}
  "/api/events/share/accept": {}
  "/api/events/share/remove": {}
  "/api/google/auth": {}
  "/api/google/callback": {}
  "/api/google/insert": {}
  "/api/health": {}
  "/api/history": {}
  "/api/history/[id]": { "id": string; }
  "/api/history/[id]/carpool": { "id": string; }
  "/api/history/[id]/signup": { "id": string; }
  "/api/history/[id]/volunteer": { "id": string; }
  "/api/ics": {}
  "/api/ingest": {}
  "/api/maps/static": {}
  "/api/meet/[eventId]": { "eventId": string; }
  "/api/net": {}
  "/api/oauth/disconnect": {}
  "/api/ocr": {}
  "/api/outlook/auth": {}
  "/api/outlook/callback": {}
  "/api/outlook/insert": {}
  "/api/parse/[eventId]": { "eventId": string; }
  "/api/parse/[eventId]/enrich": { "eventId": string; }
  "/api/promo/gift": {}
  "/api/promo/redeem": {}
  "/api/registry/add": {}
  "/api/registry/autofill": {}
  "/api/registry/claim": {}
  "/api/registry/list": {}
  "/api/rsvp/attendance": {}
  "/api/stripe/webhook": {}
  "/api/templates/signup": {}
  "/api/upload": {}
  "/api/uploads/birthday-asset": {}
  "/api/user/change-password": {}
  "/api/user/feature-visibility": {}
  "/api/user/profile": {}
  "/api/user/subscription": {}
  "/calendar": {}
  "/contact": {}
  "/event": {}
  "/event/[id]": { "id": string; }
  "/event/appointments": {}
  "/event/appointments/customize": {}
  "/event/baby-showers": {}
  "/event/baby-showers/customize": {}
  "/event/birthdays": {}
  "/event/birthdays/customize": {}
  "/event/cheerleading/customize": {}
  "/event/dance-ballet/customize": {}
  "/event/football": {}
  "/event/football-season/customize": {}
  "/event/football/customize": {}
  "/event/gender-reveal": {}
  "/event/gender-reveal/customize": {}
  "/event/general": {}
  "/event/general/customize": {}
  "/event/gymnastics": {}
  "/event/gymnastics/customize": {}
  "/event/new": {}
  "/event/soccer/customize": {}
  "/event/special-events": {}
  "/event/special-events/customize": {}
  "/event/sport-events": {}
  "/event/sport-events/customize": {}
  "/event/weddings": {}
  "/event/weddings/[id]/registry": { "id": string; }
  "/event/weddings/customize": {}
  "/event/weddings/customize/[id]": { "id": string; }
  "/event/workshops/customize": {}
  "/faq": {}
  "/football": {}
  "/forgot": {}
  "/gymnastics": {}
  "/how-it-works": {}
  "/landing": {}
  "/open": {}
  "/privacy": {}
  "/registry/[id]": { "id": string; }
  "/reset": {}
  "/settings": {}
  "/smart-signup-form": {}
  "/smart-signup-form/[id]": { "id": string; }
  "/subscription": {}
  "/templates/signup": {}
  "/terms": {}
  "/verify-request": {}
  "/who-its-for": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/contact": never
  "/forgot": never
  "/open": never
  "/privacy": never
  "/reset": never
  "/terms": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
