// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/admin/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/event-share/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails/event-share">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/event-share/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/password-changed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails/password-changed">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/password-changed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/password-reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails/password-reset">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/password-reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/event/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/appointments/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/appointments/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/appointments/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/appointments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/appointments">> = Specific
  const handler = {} as typeof import("../../src/app/event/appointments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/baby-showers/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/baby-showers/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/baby-showers/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/baby-showers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/baby-showers">> = Specific
  const handler = {} as typeof import("../../src/app/event/baby-showers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/birthdays/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/birthdays/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/birthdays/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/birthdays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/birthdays">> = Specific
  const handler = {} as typeof import("../../src/app/event/birthdays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/cheerleading/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/cheerleading/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/cheerleading/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/dance-ballet/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/dance-ballet/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/dance-ballet/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/football-season/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/football-season/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/football-season/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/football/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/football/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/football/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/football/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/football">> = Specific
  const handler = {} as typeof import("../../src/app/event/football/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/gender-reveal/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/gender-reveal/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/gender-reveal/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/gender-reveal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/gender-reveal">> = Specific
  const handler = {} as typeof import("../../src/app/event/gender-reveal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/general/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/general/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/general/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/general/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/general">> = Specific
  const handler = {} as typeof import("../../src/app/event/general/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/gymnastics/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/gymnastics/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/gymnastics/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/gymnastics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/gymnastics">> = Specific
  const handler = {} as typeof import("../../src/app/event/gymnastics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/new">> = Specific
  const handler = {} as typeof import("../../src/app/event/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event">> = Specific
  const handler = {} as typeof import("../../src/app/event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/soccer/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/soccer/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/soccer/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/special-events/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/special-events/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/special-events/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/special-events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/special-events">> = Specific
  const handler = {} as typeof import("../../src/app/event/special-events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/sport-events/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/sport-events/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/sport-events/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/sport-events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/sport-events">> = Specific
  const handler = {} as typeof import("../../src/app/event/sport-events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/weddings/[id]/registry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/weddings/[id]/registry">> = Specific
  const handler = {} as typeof import("../../src/app/event/weddings/[id]/registry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/weddings/customize/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/weddings/customize/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/event/weddings/customize/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/weddings/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/weddings/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/weddings/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/weddings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/weddings">> = Specific
  const handler = {} as typeof import("../../src/app/event/weddings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/workshops/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/workshops/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/workshops/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/football/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/football">> = Specific
  const handler = {} as typeof import("../../src/app/football/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot">> = Specific
  const handler = {} as typeof import("../../src/app/forgot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gymnastics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gymnastics">> = Specific
  const handler = {} as typeof import("../../src/app/gymnastics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/how-it-works/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/how-it-works">> = Specific
  const handler = {} as typeof import("../../src/app/how-it-works/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../src/app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/open/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/open">> = Specific
  const handler = {} as typeof import("../../src/app/open/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/registry/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registry/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/registry/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset">> = Specific
  const handler = {} as typeof import("../../src/app/reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/smart-signup-form/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/smart-signup-form/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/smart-signup-form/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/smart-signup-form/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/smart-signup-form">> = Specific
  const handler = {} as typeof import("../../src/app/smart-signup-form/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/templates/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/signup">> = Specific
  const handler = {} as typeof import("../../src/app/templates/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-request">> = Specific
  const handler = {} as typeof import("../../src/app/verify-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/who-its-for/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/who-its-for">> = Specific
  const handler = {} as typeof import("../../src/app/who-its-for/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/campaigns/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/campaigns/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/campaigns/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/filter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/filter">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/filter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/stripe/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/stripe/portal">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/stripe/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/stripe/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/stripe/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/stripe/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blob/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blob/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/blob/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendars/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendars">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendars/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/enrich-next-event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/enrich-next-event">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/enrich-next-event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/db-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/db-test">> = Specific
  const handler = {} as typeof import("../../src/app/api/db-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-db">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug-egress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-egress">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug-egress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug-env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-env">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug-env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug-ocr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-ocr">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug-ocr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug-vision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-vision">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug-vision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/oauth-tokens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/oauth-tokens">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/oauth-tokens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/promo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/promo">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/promo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/rsvp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/rsvp">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/rsvp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/thumbnail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/thumbnail">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/thumbnail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/unlock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/unlock">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/unlock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/update-theme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/update-theme">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/update-theme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/google/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/google/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/google/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/google">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/ics/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/ics/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/ics/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/outlook/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/outlook/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/outlook/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/outlook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/outlook">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/outlook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/share/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/share/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/share/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/share/remove/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/share/remove">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/share/remove/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/share">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/google/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google/insert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/insert">> = Specific
  const handler = {} as typeof import("../../src/app/api/google/insert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/[id]/carpool/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/[id]/carpool">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/[id]/carpool/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/[id]/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/[id]/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/[id]/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/[id]/volunteer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/[id]/volunteer">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/[id]/volunteer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ics">> = Specific
  const handler = {} as typeof import("../../src/app/api/ics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest">> = Specific
  const handler = {} as typeof import("../../src/app/api/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/maps/static/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maps/static">> = Specific
  const handler = {} as typeof import("../../src/app/api/maps/static/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meet/[eventId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meet/[eventId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/meet/[eventId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/net/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/net">> = Specific
  const handler = {} as typeof import("../../src/app/api/net/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/oauth/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/disconnect">> = Specific
  const handler = {} as typeof import("../../src/app/api/oauth/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ocr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ocr">> = Specific
  const handler = {} as typeof import("../../src/app/api/ocr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outlook/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outlook/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/outlook/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outlook/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outlook/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/outlook/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outlook/insert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outlook/insert">> = Specific
  const handler = {} as typeof import("../../src/app/api/outlook/insert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parse/[eventId]/enrich/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parse/[eventId]/enrich">> = Specific
  const handler = {} as typeof import("../../src/app/api/parse/[eventId]/enrich/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parse/[eventId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parse/[eventId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/parse/[eventId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/promo/gift/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promo/gift">> = Specific
  const handler = {} as typeof import("../../src/app/api/promo/gift/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/promo/redeem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promo/redeem">> = Specific
  const handler = {} as typeof import("../../src/app/api/promo/redeem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registry/add/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registry/add">> = Specific
  const handler = {} as typeof import("../../src/app/api/registry/add/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registry/autofill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registry/autofill">> = Specific
  const handler = {} as typeof import("../../src/app/api/registry/autofill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registry/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registry/claim">> = Specific
  const handler = {} as typeof import("../../src/app/api/registry/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registry/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registry/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/registry/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rsvp/attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rsvp/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/api/rsvp/attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/templates/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/templates/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploads/birthday-asset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads/birthday-asset">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploads/birthday-asset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/change-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/feature-visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/feature-visibility">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/feature-visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/forgot">> = Specific
  const handler = {} as typeof import("../../src/app/forgot/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/open/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/open">> = Specific
  const handler = {} as typeof import("../../src/app/open/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/reset">> = Specific
  const handler = {} as typeof import("../../src/app/reset/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
