// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[category]/templates/[templateId]/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[category]/templates/[templateId]/customize">> = Specific
  const handler = {} as typeof import("../../src/app/[category]/templates/[templateId]/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[category]/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[category]/templates">> = Specific
  const handler = {} as typeof import("../../src/app/[category]/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ad-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ad-studio">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ad-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/admin/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/concierge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/concierge">> = Specific
  const handler = {} as typeof import("../../src/app/admin/concierge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails/editor">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/event-share/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails/event-share">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/event-share/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/magazine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails/magazine">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/magazine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/password-changed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails/password-changed">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/password-changed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/password-reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails/password-reset">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/password-reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events">> = Specific
  const handler = {} as typeof import("../../src/app/admin/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/health">> = Specific
  const handler = {} as typeof import("../../src/app/admin/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/landing-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/landing-preview">> = Specific
  const handler = {} as typeof import("../../src/app/admin/landing-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/marketing-assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketing-assets">> = Specific
  const handler = {} as typeof import("../../src/app/admin/marketing-assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/marketing-campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketing-campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/admin/marketing-campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/scans/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/scans/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/scans/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/scans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/scans">> = Specific
  const handler = {} as typeof import("../../src/app/admin/scans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/anniversaries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/anniversaries">> = Specific
  const handler = {} as typeof import("../../src/app/anniversaries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/baby-showers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/baby-showers">> = Specific
  const handler = {} as typeof import("../../src/app/baby-showers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/birthdays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/birthdays">> = Specific
  const handler = {} as typeof import("../../src/app/birthdays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bridal-showers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bridal-showers">> = Specific
  const handler = {} as typeof import("../../src/app/bridal-showers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/card/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/card/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/card/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../src/app/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/e/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/e/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/e/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/envitefy-concierge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/envitefy-concierge">> = Specific
  const handler = {} as typeof import("../../src/app/envitefy-concierge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/event/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/anniversaries/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/anniversaries/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/anniversaries/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/anniversaries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/anniversaries">> = Specific
  const handler = {} as typeof import("../../src/app/event/anniversaries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/appointments/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/appointments/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/appointments/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/appointments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/appointments">> = Specific
  const handler = {} as typeof import("../../src/app/event/appointments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/baby-showers/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/baby-showers/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/baby-showers/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/baby-showers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/baby-showers">> = Specific
  const handler = {} as typeof import("../../src/app/event/baby-showers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/birthdays/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/birthdays/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/birthdays/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/birthdays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/birthdays">> = Specific
  const handler = {} as typeof import("../../src/app/event/birthdays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/cheerleading/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/cheerleading/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/cheerleading/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/dance-ballet/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/dance-ballet/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/dance-ballet/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/football-season/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/football-season/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/football-season/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/football/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/football/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/football/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/football/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/football">> = Specific
  const handler = {} as typeof import("../../src/app/event/football/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/gender-reveal/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/gender-reveal/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/gender-reveal/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/gender-reveal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/gender-reveal">> = Specific
  const handler = {} as typeof import("../../src/app/event/gender-reveal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/general/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/general/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/general/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/general/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/general">> = Specific
  const handler = {} as typeof import("../../src/app/event/general/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/gymnastics/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/gymnastics/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/gymnastics/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/gymnastics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/gymnastics">> = Specific
  const handler = {} as typeof import("../../src/app/event/gymnastics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/new">> = Specific
  const handler = {} as typeof import("../../src/app/event/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event">> = Specific
  const handler = {} as typeof import("../../src/app/event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/soccer/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/soccer/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/soccer/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/special-events/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/special-events/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/special-events/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/special-events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/special-events">> = Specific
  const handler = {} as typeof import("../../src/app/event/special-events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/sport-events/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/sport-events/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/sport-events/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/sport-events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/sport-events">> = Specific
  const handler = {} as typeof import("../../src/app/event/sport-events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/weddings/[id]/registry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/weddings/[id]/registry">> = Specific
  const handler = {} as typeof import("../../src/app/event/weddings/[id]/registry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/weddings/customize/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/weddings/customize/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/event/weddings/customize/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/weddings/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/weddings/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/weddings/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/weddings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/weddings">> = Specific
  const handler = {} as typeof import("../../src/app/event/weddings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/event/workshops/customize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/workshops/customize">> = Specific
  const handler = {} as typeof import("../../src/app/event/workshops/customize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/events/[id]/manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/manage">> = Specific
  const handler = {} as typeof import("../../src/app/events/[id]/manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/football/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/football">> = Specific
  const handler = {} as typeof import("../../src/app/football/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot">> = Specific
  const handler = {} as typeof import("../../src/app/forgot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gender-reveal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gender-reveal">> = Specific
  const handler = {} as typeof import("../../src/app/gender-reveal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/birthday-rsvp-invitation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/birthday-rsvp-invitation">> = Specific
  const handler = {} as typeof import("../../src/app/guides/birthday-rsvp-invitation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/flyer-to-event-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/flyer-to-event-page">> = Specific
  const handler = {} as typeof import("../../src/app/guides/flyer-to-event-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/gymnastics-meet-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/gymnastics-meet-page">> = Specific
  const handler = {} as typeof import("../../src/app/guides/gymnastics-meet-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/live-card-invitations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/live-card-invitations">> = Specific
  const handler = {} as typeof import("../../src/app/guides/live-card-invitations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides">> = Specific
  const handler = {} as typeof import("../../src/app/guides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/pdf-to-event-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/pdf-to-event-page">> = Specific
  const handler = {} as typeof import("../../src/app/guides/pdf-to-event-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/registry-invitation-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/registry-invitation-page">> = Specific
  const handler = {} as typeof import("../../src/app/guides/registry-invitation-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/rsvp-event-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/rsvp-event-page">> = Specific
  const handler = {} as typeof import("../../src/app/guides/rsvp-event-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/share-event-page-without-app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/share-event-page-without-app">> = Specific
  const handler = {} as typeof import("../../src/app/guides/share-event-page-without-app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/smart-signup-forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/smart-signup-forms">> = Specific
  const handler = {} as typeof import("../../src/app/guides/smart-signup-forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/wedding-event-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/wedding-event-page">> = Specific
  const handler = {} as typeof import("../../src/app/guides/wedding-event-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gymnastics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gymnastics">> = Specific
  const handler = {} as typeof import("../../src/app/gymnastics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/how-it-works/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/how-it-works">> = Specific
  const handler = {} as typeof import("../../src/app/how-it-works/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invitation-maker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invitation-maker">> = Specific
  const handler = {} as typeof import("../../src/app/invitation-maker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../src/app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/open/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/open">> = Specific
  const handler = {} as typeof import("../../src/app/open/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/registry/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registry/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/registry/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset">> = Specific
  const handler = {} as typeof import("../../src/app/reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/showcase/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/showcase/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/showcase/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/showcase">> = Specific
  const handler = {} as typeof import("../../src/app/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup-forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup-forms">> = Specific
  const handler = {} as typeof import("../../src/app/signup-forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/smart-signup-form/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/smart-signup-form/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/smart-signup-form/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/smart-signup-form/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/smart-signup-form">> = Specific
  const handler = {} as typeof import("../../src/app/smart-signup-form/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/snap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/snap">> = Specific
  const handler = {} as typeof import("../../src/app/snap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sport-events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sport-events">> = Specific
  const handler = {} as typeof import("../../src/app/sport-events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sports">> = Specific
  const handler = {} as typeof import("../../src/app/sports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio">> = Specific
  const handler = {} as typeof import("../../src/app/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/templates/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/signup">> = Specific
  const handler = {} as typeof import("../../src/app/templates/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unsubscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe">> = Specific
  const handler = {} as typeof import("../../src/app/unsubscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-request">> = Specific
  const handler = {} as typeof import("../../src/app/verify-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/weddings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/weddings">> = Specific
  const handler = {} as typeof import("../../src/app/weddings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/who-its-for/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/who-its-for">> = Specific
  const handler = {} as typeof import("../../src/app/who-its-for/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ad-studio/assets/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ad-studio/assets/[runId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ad-studio/assets/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ad-studio/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ad-studio/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ad-studio/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ad-studio/images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ad-studio/images">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ad-studio/images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ad-studio/video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ad-studio/video">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ad-studio/video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/campaigns/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/campaigns/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/campaigns/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/campaigns/process-due/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/campaigns/process-due">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/campaigns/process-due/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/campaigns/send-raw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/campaigns/send-raw">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/campaigns/send-raw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/campaigns/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/campaigns/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/campaigns/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/concierge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/concierge">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/concierge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/emails/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/emails/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/emails/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing-campaigns/[runId]/asset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing-campaigns/[runId]/asset">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing-campaigns/[runId]/asset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing-campaigns/[runId]/captions/regenerate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing-campaigns/[runId]/captions/regenerate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing-campaigns/[runId]/captions/regenerate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing-campaigns/[runId]/captions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing-campaigns/[runId]/captions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing-campaigns/[runId]/captions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing-campaigns/[runId]/preview-frame/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing-campaigns/[runId]/preview-frame">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing-campaigns/[runId]/preview-frame/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing-campaigns/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing-campaigns/[runId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing-campaigns/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing-campaigns/[runId]/social-images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing-campaigns/[runId]/social-images">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing-campaigns/[runId]/social-images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing-campaigns/[runId]/storyboard/regenerate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing-campaigns/[runId]/storyboard/regenerate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing-campaigns/[runId]/storyboard/regenerate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing-campaigns/[runId]/video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing-campaigns/[runId]/video">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing-campaigns/[runId]/video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing-campaigns/prompt-ideas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing-campaigns/prompt-ideas">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing-campaigns/prompt-ideas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing-campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing-campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing-campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/scan-attempts/[id]/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/scan-attempts/[id]/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/scan-attempts/[id]/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/scans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/scans">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/scans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/debug-links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/debug-links">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/debug-links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/filter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/filter">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/filter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/legal-acceptance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/legal-acceptance">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/legal-acceptance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup-source/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup-source">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup-source/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blob/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blob/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/blob/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendars/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendars">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendars/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/client-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/events/[id]/message/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/events/[id]/message">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/events/[id]/message/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/message/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/message">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/message/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/creation/intake/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creation/intake">> = Specific
  const handler = {} as typeof import("../../src/app/api/creation/intake/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/creation/intake/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creation/intake/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/creation/intake/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/creation/threads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creation/threads/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/creation/threads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/creation/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creation/threads">> = Specific
  const handler = {} as typeof import("../../src/app/api/creation/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/enrich-next-event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/enrich-next-event">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/enrich-next-event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/db-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/db-test">> = Specific
  const handler = {} as typeof import("../../src/app/api/db-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-db">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug-egress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-egress">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug-egress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug-env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-env">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug-env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug-ocr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-ocr">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug-ocr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug-vision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-vision">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug-vision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/oauth-tokens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/oauth-tokens">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/oauth-tokens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/discovery/[eventId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/[eventId]/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/discovery/[eventId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/discovery/[eventId]/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/[eventId]/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/discovery/[eventId]/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/discovery/[eventId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/[eventId]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/discovery/[eventId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/discovery/intake/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/intake">> = Specific
  const handler = {} as typeof import("../../src/app/api/discovery/intake/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/unsubscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/email/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/event-pages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/event-pages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/event-pages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/event-pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/event-pages">> = Specific
  const handler = {} as typeof import("../../src/app/api/event-pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/event-pages/slug/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/event-pages/slug/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/event-pages/slug/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/assets/[assetId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/assets/[assetId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/assets/[assetId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/assets">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/card/edit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/card/edit">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/card/edit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/public-slug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/public-slug">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/public-slug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/rsvp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/rsvp">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/rsvp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/thumbnail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/thumbnail">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/thumbnail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/unlock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/unlock">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/unlock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/update-theme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/update-theme">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/update-theme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/calendar/auto/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/calendar/auto">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/calendar/auto/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/google/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/google/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/google/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/google">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/ics/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/ics/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/ics/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/outlook/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/outlook/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/outlook/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/outlook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/outlook">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/outlook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/share/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/share/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/share/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/share/remove/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/share/remove">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/share/remove/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/share">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/google/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google/insert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/insert">> = Specific
  const handler = {} as typeof import("../../src/app/api/google/insert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/guest-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest-chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/guest-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/[id]/carpool/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/[id]/carpool">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/[id]/carpool/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/[id]/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/[id]/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/[id]/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/[id]/volunteer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/[id]/volunteer">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/[id]/volunteer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ics">> = Specific
  const handler = {} as typeof import("../../src/app/api/ics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest">> = Specific
  const handler = {} as typeof import("../../src/app/api/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal/scan-diagnostics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/scan-diagnostics">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal/scan-diagnostics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/maps/static/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maps/static">> = Specific
  const handler = {} as typeof import("../../src/app/api/maps/static/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meet/[eventId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meet/[eventId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/meet/[eventId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/net/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/net">> = Specific
  const handler = {} as typeof import("../../src/app/api/net/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/oauth/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/disconnect">> = Specific
  const handler = {} as typeof import("../../src/app/api/oauth/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ocr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ocr">> = Specific
  const handler = {} as typeof import("../../src/app/api/ocr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outlook/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outlook/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/outlook/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outlook/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outlook/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/outlook/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outlook/insert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outlook/insert">> = Specific
  const handler = {} as typeof import("../../src/app/api/outlook/insert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parse/[eventId]/enrich/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parse/[eventId]/enrich">> = Specific
  const handler = {} as typeof import("../../src/app/api/parse/[eventId]/enrich/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registry/add/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registry/add">> = Specific
  const handler = {} as typeof import("../../src/app/api/registry/add/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registry/autofill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registry/autofill">> = Specific
  const handler = {} as typeof import("../../src/app/api/registry/autofill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registry/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registry/claim">> = Specific
  const handler = {} as typeof import("../../src/app/api/registry/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registry/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registry/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/registry/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rsvp/attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rsvp/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/api/rsvp/attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scan/event-page/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scan/event-page">> = Specific
  const handler = {} as typeof import("../../src/app/api/scan/event-page/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/library/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/library">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/library/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/templates/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/media">> = Specific
  const handler = {} as typeof import("../../src/app/api/templates/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/templates/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/templates/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploads/birthday-asset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads/birthday-asset">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploads/birthday-asset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/change-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/feature-visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/feature-visibility">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/feature-visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/profile/avatar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile/avatar">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/profile/avatar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/media/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/media/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/media/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/media/events/[id]/thumbnail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/media/events/[id]/thumbnail">> = Specific
  const handler = {} as typeof import("../../src/app/media/events/[id]/thumbnail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/forgot">> = Specific
  const handler = {} as typeof import("../../src/app/forgot/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/open/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/open">> = Specific
  const handler = {} as typeof import("../../src/app/open/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/reset">> = Specific
  const handler = {} as typeof import("../../src/app/reset/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
