import { ThemeDefinition, ThemeKey, ThemeVariant, ThemeVariantDefinition, THEME_KEYS } from "./types";

function vars(input: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(input)) {
    out[`--${key}`] = value;
  }
  return out;
}

const generalLight: ThemeVariantDefinition = {
  label: "General Light",
  cssVariables: {
    ...vars({
      background: "#FFFBF7",
      surface: "#FFFFFF",
      "surface-alt": "#F8F5F1",
      foreground: "#3F3C3C",
      "muted-foreground": "#6F6C69",
      border: "#E4DED4",
      primary: "#2DD4BF",
      secondary: "#6366F1",
      accent: "#A855F7",
      success: "#22C55E",
      info: "#3B82F6",
      warning: "#F97316",
      error: "#EF4444",
      "on-primary": "#FFFFFF",
      "on-secondary": "#FFFFFF",
      "on-accent": "#FFFFFF",
      "theme-overlay": "rgba(45, 212, 191, 0.12)",
      "theme-overlay-secondary": "rgba(99, 102, 241, 0.10)",
      "theme-card-glow": "rgba(168, 85, 247, 0.16)",
      "theme-hero-gradient":
        "radial-gradient(120% 120% at 10% -10%, rgba(99,102,241,0.12), transparent 60%), radial-gradient(80% 60% at 80% 0%, rgba(45,212,191,0.18), transparent 70%)",
    }),
    "--theme-illustration": "url('/themes/general/confetti.svg')",
  },
  accentIcon: "/themes/general/burst.svg",
  accentAlt: "Confetti illustration",
};

const generalDark: ThemeVariantDefinition = {
  label: "General Dark",
  cssVariables: {
    ...vars({
      background: "#1C1B1A",
      surface: "#272625",
      "surface-alt": "#2F2D2C",
      foreground: "#F8F8F9",
      "muted-foreground": "#B0ADAA",
      border: "#3D3C3B",
      primary: "#2DD4BF",
      secondary: "#818CF8",
      accent: "#C084FC",
      success: "#4ADE80",
      info: "#60A5FA",
      warning: "#FB923C",
      error: "#F87171",
      "on-primary": "#052725",
      "on-secondary": "#0E1036",
      "on-accent": "#2B063C",
      "theme-overlay": "rgba(129, 140, 248, 0.16)",
      "theme-overlay-secondary": "rgba(45, 212, 191, 0.12)",
      "theme-card-glow": "rgba(192, 132, 252, 0.22)",
      "theme-hero-gradient":
        "radial-gradient(140% 140% at 0% -10%, rgba(192,132,252,0.28), transparent 70%), radial-gradient(100% 80% at 90% 10%, rgba(45,212,191,0.24), transparent 75%)",
    }),
    "--theme-illustration": "url('/themes/general/confetti-dark.svg')",
  },
  accentIcon: "/themes/general/burst-dark.svg",
  accentAlt: "Night confetti illustration",
};

function createThemeDefinition(params: {
  key: ThemeKey;
  label: string;
  description: string;
  order: number;
  scheduleSummary: string;
  light: ThemeVariantDefinition;
  dark: ThemeVariantDefinition;
}): ThemeDefinition {
  return {
    key: params.key,
    label: params.label,
    description: params.description,
    order: params.order,
    scheduleSummary: params.scheduleSummary,
    variants: {
      light: params.light,
      dark: params.dark,
    },
  };
}

const THEMES_ARRAY: ThemeDefinition[] = [
  createThemeDefinition({
    key: "general",
    label: "General",
    description: "Default Snap My Date experience with teal + indigo accent colors.",
    order: 0,
    scheduleSummary: "Used whenever no seasonal window is active.",
    light: generalLight,
    dark: generalDark,
  }),
  createThemeDefinition({
    key: "halloween",
    label: "Halloween",
    description: "Pumpkin spice palette with playful bats and glow lighting.",
    order: 10,
    scheduleSummary: "October 1  October 31",
    light: {
      label: "Halloween Light",
      cssVariables: {
        ...vars({
          background: "#FFF8F1",
          surface: "#FFEFE0",
          "surface-alt": "#FFE3C7",
          foreground: "#3B2110",
          "muted-foreground": "#704732",
          border: "#F5D3B3",
          primary: "#F97316",
          secondary: "#7C3AED",
          accent: "#FB923C",
          success: "#22C55E",
          info: "#38BDF8",
          warning: "#FACC15",
          error: "#F43F5E",
          "on-primary": "#3B1805",
          "on-secondary": "#F9F5FF",
          "on-accent": "#3B1805",
          "theme-overlay": "rgba(249, 115, 22, 0.18)",
          "theme-overlay-secondary": "rgba(124, 58, 237, 0.14)",
          "theme-card-glow": "rgba(251, 146, 60, 0.22)",
          "theme-hero-gradient":
            "radial-gradient(110% 120% at 5% -15%, rgba(124,58,237,0.20), transparent 60%), radial-gradient(90% 70% at 80% 0%, rgba(249,115,22,0.24), transparent 65%)",
        }),
        "--theme-illustration": "url('/themes/halloween/bats.svg')",
      },
      accentIcon: "/themes/halloween/pumpkin.svg",
      accentAlt: "Smiling jack-o'-lantern",
    },
    dark: {
      label: "Halloween Dark",
      cssVariables: {
        ...vars({
          background: "#140A1A",
          surface: "#1E1026",
          "surface-alt": "#2B1636",
          foreground: "#F8F3FF",
          "muted-foreground": "#C7B6E4",
          border: "#402450",
          primary: "#FB923C",
          secondary: "#C084FC",
          accent: "#F97316",
          success: "#22C55E",
          info: "#60A5FA",
          warning: "#FACC15",
          error: "#FB7185",
          "on-primary": "#2B0C05",
          "on-secondary": "#110219",
          "on-accent": "#2B0C05",
          "theme-overlay": "rgba(192, 132, 252, 0.28)",
          "theme-overlay-secondary": "rgba(249, 115, 22, 0.22)",
          "theme-card-glow": "rgba(251, 146, 60, 0.32)",
          "theme-hero-gradient":
            "radial-gradient(120% 120% at 0% -10%, rgba(251,146,60,0.32), transparent 58%), radial-gradient(90% 70% at 90% 5%, rgba(124,58,237,0.24), transparent 70%)",
        }),
        "--theme-illustration": "url('/themes/halloween/bats-dark.svg')",
      },
      accentIcon: "/themes/halloween/pumpkin-dark.svg",
      accentAlt: "Glowing jack-o'-lantern",
    },
  }),
  createThemeDefinition({
    key: "thanksgiving",
    label: "Thanksgiving",
    description: "Harvest neutrals with cranberry accents and friendly turkey art.",
    order: 20,
    scheduleSummary: "November 1  Thanksgiving Day",
    light: {
      label: "Thanksgiving Light",
      cssVariables: {
        ...vars({
          background: "#FEF8F1",
          surface: "#FDEED9",
          "surface-alt": "#F9E2C3",
          foreground: "#402612",
          "muted-foreground": "#805033",
          border: "#E8C9A8",
          primary: "#B45309",
          secondary: "#D97706",
          accent: "#DC2626",
          success: "#16A34A",
          info: "#2563EB",
          warning: "#F97316",
          error: "#B91C1C",
          "on-primary": "#FFF3E4",
          "on-secondary": "#241205",
          "on-accent": "#FDF2F2",
          "theme-overlay": "rgba(220, 38, 38, 0.16)",
          "theme-overlay-secondary": "rgba(217, 119, 6, 0.16)",
          "theme-card-glow": "rgba(236, 98, 65, 0.24)",
          "theme-hero-gradient":
            "radial-gradient(120% 120% at 10% -20%, rgba(217,119,6,0.22), transparent 60%), radial-gradient(80% 70% at 90% 10%, rgba(220,38,38,0.20), transparent 68%)",
        }),
        "--theme-illustration": "url('/themes/thanksgiving/turkey.svg')",
      },
      accentIcon: "/themes/thanksgiving/leaf.svg",
      accentAlt: "Maple leaf",
    },
    dark: {
      label: "Thanksgiving Dark",
      cssVariables: {
        ...vars({
          background: "#1A1209",
          surface: "#24170B",
          "surface-alt": "#331E0C",
          foreground: "#FDF4E7",
          "muted-foreground": "#E2C7AD",
          border: "#4B2D12",
          primary: "#F97316",
          secondary: "#EA580C",
          accent: "#F87171",
          success: "#34D399",
          info: "#60A5FA",
          warning: "#FBBF24",
          error: "#F87171",
          "on-primary": "#1C0C02",
          "on-secondary": "#230B02",
          "on-accent": "#230B0B",
          "theme-overlay": "rgba(249, 115, 22, 0.26)",
          "theme-overlay-secondary": "rgba(250, 204, 21, 0.18)",
          "theme-card-glow": "rgba(248, 113, 113, 0.28)",
          "theme-hero-gradient":
            "radial-gradient(140% 140% at -5% -15%, rgba(250,204,21,0.22), transparent 62%), radial-gradient(90% 80% at 95% 10%, rgba(249,115,22,0.30), transparent 70%)",
        }),
        "--theme-illustration": "url('/themes/thanksgiving/turkey-dark.svg')",
      },
      accentIcon: "/themes/thanksgiving/leaf-dark.svg",
      accentAlt: "Golden maple leaf",
    },
  }),
  createThemeDefinition({
    key: "christmas",
    label: "Christmas",
    description: "Evergreen and candy-cane reds with twinkling snow details.",
    order: 30,
    scheduleSummary: "Day after Thanksgiving  December 25",
    light: {
      label: "Christmas Light",
      cssVariables: {
        ...vars({
          background: "#F5FAF6",
          surface: "#FFFFFF",
          "surface-alt": "#ECF7EE",
          foreground: "#143321",
          "muted-foreground": "#2F6B46",
          border: "#CBE8D2",
          primary: "#15803D",
          secondary: "#B91C1C",
          accent: "#EF4444",
          success: "#22C55E",
          info: "#2563EB",
          warning: "#F59E0B",
          error: "#DC2626",
          "on-primary": "#EBFDF2",
          "on-secondary": "#FEF2F2",
          "on-accent": "#FEF2F2",
          "theme-overlay": "rgba(21, 128, 61, 0.18)",
          "theme-overlay-secondary": "rgba(239, 68, 68, 0.16)",
          "theme-card-glow": "rgba(59, 130, 246, 0.18)",
          "theme-hero-gradient":
            "radial-gradient(120% 120% at 0% -15%, rgba(21,128,61,0.26), transparent 60%), radial-gradient(90% 70% at 90% 10%, rgba(239,68,68,0.26), transparent 68%)",
        }),
        "--theme-illustration": "url('/themes/christmas/tree.svg')",
      },
      accentIcon: "/themes/christmas/ornament.svg",
      accentAlt: "Christmas ornament",
    },
    dark: {
      label: "Christmas Dark",
      cssVariables: {
        ...vars({
          background: "#0B1A1C",
          surface: "#112325",
          "surface-alt": "#1A3336",
          foreground: "#E4FAF3",
          "muted-foreground": "#96CEC1",
          border: "#1C3A3F",
          primary: "#22C55E",
          secondary: "#F87171",
          accent: "#F43F5E",
          success: "#34D399",
          info: "#60A5FA",
          warning: "#FACC15",
          error: "#F87171",
          "on-primary": "#02140A",
          "on-secondary": "#250202",
          "on-accent": "#250202",
          "theme-overlay": "rgba(34, 197, 94, 0.28)",
          "theme-overlay-secondary": "rgba(244, 63, 94, 0.28)",
          "theme-card-glow": "rgba(96, 165, 250, 0.22)",
          "theme-hero-gradient":
            "radial-gradient(140% 140% at -10% -10%, rgba(34,197,94,0.32), transparent 60%), radial-gradient(90% 70% at 95% 10%, rgba(244,63,94,0.32), transparent 68%)",
        }),
        "--theme-illustration": "url('/themes/christmas/tree-dark.svg')",
      },
      accentIcon: "/themes/christmas/ornament-dark.svg",
      accentAlt: "Snowy ornament",
    },
  }),
  createThemeDefinition({
    key: "new-years",
    label: "New Year",
    description: "Festive champagne gold and midnight confetti sparkles.",
    order: 40,
    scheduleSummary: "December 26  January 1",
    light: {
      label: "New Year Light",
      cssVariables: {
        ...vars({
          background: "#FFFDF5",
          surface: "#FDF6E9",
          "surface-alt": "#F8EDD9",
          foreground: "#2F1E10",
          "muted-foreground": "#6B4F2F",
          border: "#E9DCC3",
          primary: "#D97706",
          secondary: "#1F2937",
          accent: "#B45309",
          success: "#22C55E",
          info: "#1D4ED8",
          warning: "#F59E0B",
          error: "#DC2626",
          "on-primary": "#2F1602",
          "on-secondary": "#F9FAFB",
          "on-accent": "#2F1602",
          "theme-overlay": "rgba(217, 119, 6, 0.18)",
          "theme-overlay-secondary": "rgba(31, 41, 55, 0.12)",
          "theme-card-glow": "rgba(217, 119, 6, 0.22)",
          "theme-hero-gradient":
            "radial-gradient(110% 120% at 5% -15%, rgba(217,119,6,0.24), transparent 60%), radial-gradient(90% 70% at 90% 0%, rgba(31,41,55,0.20), transparent 65%)",
        }),
        "--theme-illustration": "url('/themes/new-years/fireworks.svg')",
      },
      accentIcon: "/themes/new-years/clock.svg",
      accentAlt: "Countdown clock",
    },
    dark: {
      label: "New Year Dark",
      cssVariables: {
        ...vars({
          background: "#0D0C0F",
          surface: "#16151A",
          "surface-alt": "#1F1E24",
          foreground: "#F7F6FB",
          "muted-foreground": "#D1C8B6",
          border: "#302D36",
          primary: "#F59E0B",
          secondary: "#FACC15",
          accent: "#FDE68A",
          success: "#34D399",
          info: "#60A5FA",
          warning: "#FBBF24",
          error: "#F97316",
          "on-primary": "#190F02",
          "on-secondary": "#211902",
          "on-accent": "#1F1A05",
          "theme-overlay": "rgba(245, 158, 11, 0.28)",
          "theme-overlay-secondary": "rgba(250, 204, 21, 0.24)",
          "theme-card-glow": "rgba(252, 211, 77, 0.34)",
          "theme-hero-gradient":
            "radial-gradient(140% 140% at -10% -10%, rgba(245,158,11,0.34), transparent 62%), radial-gradient(90% 70% at 95% 5%, rgba(250,204,21,0.34), transparent 72%)",
        }),
        "--theme-illustration": "url('/themes/new-years/fireworks-dark.svg')",
      },
      accentIcon: "/themes/new-years/clock-dark.svg",
      accentAlt: "Midnight clock",
    },
  }),
  createThemeDefinition({
    key: "valentines",
    label: "Valentine's Day",
    description: "Romantic blush gradients with floating hearts and letters.",
    order: 50,
    scheduleSummary: "14 days ahead of February 14",
    light: {
      label: "Valentine's Light",
      cssVariables: {
        ...vars({
          background: "#FFF6F9",
          surface: "#FFE8F0",
          "surface-alt": "#FFD6E4",
          foreground: "#511429",
          "muted-foreground": "#A53B5D",
          border: "#F8C8D7",
          primary: "#E11D48",
          secondary: "#F472B6",
          accent: "#EC4899",
          success: "#22C55E",
          info: "#38BDF8",
          warning: "#FB7185",
          error: "#BE123C",
          "on-primary": "#FFF1F5",
          "on-secondary": "#520016",
          "on-accent": "#520016",
          "theme-overlay": "rgba(236, 72, 153, 0.18)",
          "theme-overlay-secondary": "rgba(244, 114, 182, 0.18)",
          "theme-card-glow": "rgba(244, 114, 182, 0.26)",
          "theme-hero-gradient":
            "radial-gradient(120% 120% at 0% -10%, rgba(236,72,153,0.26), transparent 60%), radial-gradient(90% 70% at 90% 10%, rgba(244,114,182,0.24), transparent 68%)",
        }),
        "--theme-illustration": "url('/themes/valentines/hearts.svg')",
      },
      accentIcon: "/themes/valentines/envelope.svg",
      accentAlt: "Love letter",
    },
    dark: {
      label: "Valentine's Dark",
      cssVariables: {
        ...vars({
          background: "#240713",
          surface: "#360A1E",
          "surface-alt": "#4B0F2B",
          foreground: "#FDE9F2",
          "muted-foreground": "#FEB1CB",
          border: "#7F2146",
          primary: "#F43F5E",
          secondary: "#FB7185",
          accent: "#F472B6",
          success: "#34D399",
          info: "#93C5FD",
          warning: "#FBBF24",
          error: "#FB7185",
          "on-primary": "#2E0311",
          "on-secondary": "#2E0311",
          "on-accent": "#2E0311",
          "theme-overlay": "rgba(251, 113, 133, 0.32)",
          "theme-overlay-secondary": "rgba(244, 114, 182, 0.28)",
          "theme-card-glow": "rgba(244, 114, 182, 0.36)",
          "theme-hero-gradient":
            "radial-gradient(140% 140% at -10% -10%, rgba(244,114,182,0.38), transparent 62%), radial-gradient(90% 70% at 95% 10%, rgba(251,113,133,0.32), transparent 70%)",
        }),
        "--theme-illustration": "url('/themes/valentines/hearts-dark.svg')",
      },
      accentIcon: "/themes/valentines/envelope-dark.svg",
      accentAlt: "Glowing heart letter",
    },
  }),
  createThemeDefinition({
    key: "st-patricks",
    label: "St. Patrick's Day",
    description: "Shamrock greens with gold foil sparkles and jaunty hats.",
    order: 60,
    scheduleSummary: "7 days ahead of March 17",
    light: {
      label: "St. Patrick's Light",
      cssVariables: {
        ...vars({
          background: "#F4FBF2",
          surface: "#E5F6DF",
          "surface-alt": "#D2EEC5",
          foreground: "#0F2B17",
          "muted-foreground": "#2E5D37",
          border: "#A8DEB0",
          primary: "#15803D",
          secondary: "#10B981",
          accent: "#FACC15",
          success: "#2DD4BF",
          info: "#0EA5E9",
          warning: "#F59E0B",
          error: "#E11D48",
          "on-primary": "#EFFDF4",
          "on-secondary": "#052F18",
          "on-accent": "#3B2602",
          "theme-overlay": "rgba(16, 185, 129, 0.22)",
          "theme-overlay-secondary": "rgba(250, 204, 21, 0.18)",
          "theme-card-glow": "rgba(34, 197, 94, 0.24)",
          "theme-hero-gradient":
            "radial-gradient(120% 120% at 0% -10%, rgba(16,185,129,0.26), transparent 60%), radial-gradient(90% 70% at 88% 5%, rgba(21,128,61,0.26), transparent 70%)",
        }),
        "--theme-illustration": "url('/themes/st-patricks/clover.svg')",
      },
      accentIcon: "/themes/st-patricks/hat.svg",
      accentAlt: "Leprechaun hat",
    },
    dark: {
      label: "St. Patrick's Dark",
      cssVariables: {
        ...vars({
          background: "#05140A",
          surface: "#092112",
          "surface-alt": "#10331D",
          foreground: "#E5F7EB",
          "muted-foreground": "#91D7A8",
          border: "#164127",
          primary: "#34D399",
          secondary: "#22C55E",
          accent: "#FACC15",
          success: "#5EEAD4",
          info: "#22D3EE",
          warning: "#F97316",
          error: "#F87171",
          "on-primary": "#022011",
          "on-secondary": "#02170B",
          "on-accent": "#2A2000",
          "theme-overlay": "rgba(34, 197, 94, 0.32)",
          "theme-overlay-secondary": "rgba(250, 204, 21, 0.28)",
          "theme-card-glow": "rgba(34, 197, 94, 0.32)",
          "theme-hero-gradient":
            "radial-gradient(140% 140% at -10% -10%, rgba(34,197,94,0.36), transparent 62%), radial-gradient(90% 70% at 95% 10%, rgba(250,204,21,0.28), transparent 70%)",
        }),
        "--theme-illustration": "url('/themes/st-patricks/clover-dark.svg')",
      },
      accentIcon: "/themes/st-patricks/hat-dark.svg",
      accentAlt: "Golden leprechaun hat",
    },
  }),
  createThemeDefinition({
    key: "easter",
    label: "Easter",
    description: "Pastel egg dyes with soft indigo nights and bunny friends.",
    order: 70,
    scheduleSummary: "14 days ahead of Easter Sunday",
    light: {
      label: "Easter Light",
      cssVariables: {
        ...vars({
          background: "#F7F6FF",
          surface: "#F1EEFF",
          "surface-alt": "#E7E4FF",
          foreground: "#2F1B74",
          "muted-foreground": "#5B4AA8",
          border: "#CFC7FF",
          primary: "#7C3AED",
          secondary: "#F97316",
          accent: "#EC4899",
          success: "#10B981",
          info: "#0EA5E9",
          warning: "#FACC15",
          error: "#EF4444",
          "on-primary": "#F8F5FF",
          "on-secondary": "#341102",
          "on-accent": "#42001F",
          "theme-overlay": "rgba(124, 58, 237, 0.18)",
          "theme-overlay-secondary": "rgba(14, 165, 233, 0.16)",
          "theme-card-glow": "rgba(236, 72, 153, 0.22)",
          "theme-hero-gradient":
            "radial-gradient(120% 120% at -5% -10%, rgba(124,58,237,0.26), transparent 62%), radial-gradient(90% 70% at 92% 10%, rgba(14,165,233,0.22), transparent 68%)",
        }),
        "--theme-illustration": "url('/themes/easter/bunny.svg')",
      },
      accentIcon: "/themes/easter/egg.svg",
      accentAlt: "Painted egg",
    },
    dark: {
      label: "Easter Dark",
      cssVariables: {
        ...vars({
          background: "#0E0C2A",
          surface: "#14113A",
          "surface-alt": "#1F1D4F",
          foreground: "#EAE8FF",
          "muted-foreground": "#BDB7FF",
          border: "#3B3680",
          primary: "#A855F7",
          secondary: "#F97316",
          accent: "#F472B6",
          success: "#34D399",
          info: "#38BDF8",
          warning: "#FBBF24",
          error: "#F87171",
          "on-primary": "#140433",
          "on-secondary": "#2C0D01",
          "on-accent": "#2E0118",
          "theme-overlay": "rgba(168, 85, 247, 0.32)",
          "theme-overlay-secondary": "rgba(244, 114, 182, 0.26)",
          "theme-card-glow": "rgba(59, 130, 246, 0.30)",
          "theme-hero-gradient":
            "radial-gradient(140% 140% at -10% -10%, rgba(168,85,247,0.36), transparent 62%), radial-gradient(90% 70% at 95% 10%, rgba(59,130,246,0.28), transparent 70%)",
        }),
        "--theme-illustration": "url('/themes/easter/bunny-dark.svg')",
      },
      accentIcon: "/themes/easter/egg-dark.svg",
      accentAlt: "Glowing egg",
    },
  }),
  createThemeDefinition({
    key: "childrens-day",
    label: "Children's Day",
    description: "Playful sky blues and sunshine yellow kites in motion.",
    order: 80,
    scheduleSummary: "7 days ahead of June 14",
    light: {
      label: "Children's Day Light",
      cssVariables: {
        ...vars({
          background: "#F3FAFF",
          surface: "#E5F4FF",
          "surface-alt": "#D6EDFF",
          foreground: "#0F2D48",
          "muted-foreground": "#1F5A86",
          border: "#B8DFFC",
          primary: "#0EA5E9",
          secondary: "#FACC15",
          accent: "#22C55E",
          success: "#22C55E",
          info: "#0284C7",
          warning: "#F97316",
          error: "#EF4444",
          "on-primary": "#03273A",
          "on-secondary": "#2D1B00",
          "on-accent": "#04210E",
          "theme-overlay": "rgba(14, 165, 233, 0.20)",
          "theme-overlay-secondary": "rgba(250, 204, 21, 0.20)",
          "theme-card-glow": "rgba(34, 197, 94, 0.22)",
          "theme-hero-gradient":
            "radial-gradient(120% 120% at -5% -10%, rgba(14,165,233,0.24), transparent 62%), radial-gradient(90% 70% at 92% 10%, rgba(250,204,21,0.22), transparent 68%)",
        }),
        "--theme-illustration": "url('/themes/childrens-day/kites.svg')",
      },
      accentIcon: "/themes/childrens-day/balloon.svg",
      accentAlt: "Balloon and kite",
    },
    dark: {
      label: "Children's Day Dark",
      cssVariables: {
        ...vars({
          background: "#071725",
          surface: "#0B2232",
          "surface-alt": "#123449",
          foreground: "#DDF3FF",
          "muted-foreground": "#9BD5FF",
          border: "#1B4A64",
          primary: "#38BDF8",
          secondary: "#FACC15",
          accent: "#34D399",
          success: "#34D399",
          info: "#38BDF8",
          warning: "#FB923C",
          error: "#F87171",
          "on-primary": "#021521",
          "on-secondary": "#221902",
          "on-accent": "#022016",
          "theme-overlay": "rgba(59, 130, 246, 0.28)",
          "theme-overlay-secondary": "rgba(250, 204, 21, 0.26)",
          "theme-card-glow": "rgba(52, 211, 153, 0.28)",
          "theme-hero-gradient":
            "radial-gradient(140% 140% at -10% -10%, rgba(59,130,246,0.32), transparent 62%), radial-gradient(90% 70% at 95% 5%, rgba(250,204,21,0.30), transparent 70%)",
        }),
        "--theme-illustration": "url('/themes/childrens-day/kites-dark.svg')",
      },
      accentIcon: "/themes/childrens-day/balloon-dark.svg",
      accentAlt: "Night balloons",
    },
  }),
  createThemeDefinition({
    key: "independence-day",
    label: "Independence Day",
    description: "Patriotic navy, white, and firework bursts with flag ribbons.",
    order: 90,
    scheduleSummary: "7 days ahead of July 4",
    light: {
      label: "Independence Day Light",
      cssVariables: {
        ...vars({
          background: "#F5F7FF",
          surface: "#FFFFFF",
          "surface-alt": "#E9EEFF",
          foreground: "#111C3D",
          "muted-foreground": "#2F3F6A",
          border: "#C4D0FF",
          primary: "#1D4ED8",
          secondary: "#B91C1C",
          accent: "#F97316",
          success: "#16A34A",
          info: "#0EA5E9",
          warning: "#F59E0B",
          error: "#DC2626",
          "on-primary": "#F1F5FF",
          "on-secondary": "#FEF2F2",
          "on-accent": "#2F1300",
          "theme-overlay": "rgba(29, 78, 216, 0.24)",
          "theme-overlay-secondary": "rgba(185, 28, 28, 0.22)",
          "theme-card-glow": "rgba(14, 165, 233, 0.22)",
          "theme-hero-gradient":
            "radial-gradient(120% 120% at 0% -10%, rgba(29,78,216,0.26), transparent 60%), radial-gradient(90% 70% at 92% 8%, rgba(185,28,28,0.22), transparent 68%)",
        }),
        "--theme-illustration": "url('/themes/independence-day/fireworks.svg')",
      },
      accentIcon: "/themes/independence-day/star.svg",
      accentAlt: "Star badge",
    },
    dark: {
      label: "Independence Day Dark",
      cssVariables: {
        ...vars({
          background: "#040817",
          surface: "#091122",
          "surface-alt": "#131C33",
          foreground: "#E7EDFF",
          "muted-foreground": "#95A9F8",
          border: "#1E2C4B",
          primary: "#3B82F6",
          secondary: "#EF4444",
          accent: "#F97316",
          success: "#22C55E",
          info: "#38BDF8",
          warning: "#FDBA74",
          error: "#FB7185",
          "on-primary": "#050E25",
          "on-secondary": "#260203",
          "on-accent": "#2B1702",
          "theme-overlay": "rgba(59, 130, 246, 0.30)",
          "theme-overlay-secondary": "rgba(239, 68, 68, 0.28)",
          "theme-card-glow": "rgba(249, 115, 22, 0.30)",
          "theme-hero-gradient":
            "radial-gradient(140% 140% at -10% -10%, rgba(59,130,246,0.34), transparent 62%), radial-gradient(90% 70% at 95% 10%, rgba(239,68,68,0.32), transparent 70%)",
        }),
        "--theme-illustration": "url('/themes/independence-day/fireworks-dark.svg')",
      },
      accentIcon: "/themes/independence-day/star-dark.svg",
      accentAlt: "Neon star",
    },
  }),
  createThemeDefinition({
    key: "labor-day",
    label: "Labor Day",
    description: "Denim blues and warm amber with hardworking tool accents.",
    order: 100,
    scheduleSummary: "10 days ahead of Labor Day (first Monday of September)",
    light: {
      label: "Labor Day Light",
      cssVariables: {
        ...vars({
          background: "#F6F8FA",
          surface: "#FFFFFF",
          "surface-alt": "#E9EFF5",
          foreground: "#14212F",
          "muted-foreground": "#37506A",
          border: "#CBD5E1",
          primary: "#2563EB",
          secondary: "#F59E0B",
          accent: "#1E40AF",
          success: "#16A34A",
          info: "#0284C7",
          warning: "#EA580C",
          error: "#DC2626",
          "on-primary": "#051730",
          "on-secondary": "#311A02",
          "on-accent": "#E2E8F0",
          "theme-overlay": "rgba(37, 99, 235, 0.22)",
          "theme-overlay-secondary": "rgba(245, 158, 11, 0.18)",
          "theme-card-glow": "rgba(30, 64, 175, 0.24)",
          "theme-hero-gradient":
            "radial-gradient(120% 120% at 0% -10%, rgba(37,99,235,0.26), transparent 60%), radial-gradient(90% 70% at 92% 5%, rgba(245,158,11,0.22), transparent 70%)",
        }),
        "--theme-illustration": "url('/themes/labor-day/tools.svg')",
      },
      accentIcon: "/themes/labor-day/helmet.svg",
      accentAlt: "Hard hat",
    },
    dark: {
      label: "Labor Day Dark",
      cssVariables: {
        ...vars({
          background: "#0B1018",
          surface: "#131B27",
          "surface-alt": "#1B2533",
          foreground: "#E6ECF7",
          "muted-foreground": "#9FB5D6",
          border: "#263448",
          primary: "#3B82F6",
          secondary: "#FBBF24",
          accent: "#1D4ED8",
          success: "#22C55E",
          info: "#38BDF8",
          warning: "#FB923C",
          error: "#F87171",
          "on-primary": "#041022",
          "on-secondary": "#251602",
          "on-accent": "#020A1E",
          "theme-overlay": "rgba(59, 130, 246, 0.30)",
          "theme-overlay-secondary": "rgba(251, 191, 36, 0.30)",
          "theme-card-glow": "rgba(29, 78, 216, 0.30)",
          "theme-hero-gradient":
            "radial-gradient(140% 140% at -10% -10%, rgba(59,130,246,0.34), transparent 62%), radial-gradient(90% 70% at 95% 10%, rgba(251,191,36,0.32), transparent 70%)",
        }),
        "--theme-illustration": "url('/themes/labor-day/tools-dark.svg')",
      },
      accentIcon: "/themes/labor-day/helmet-dark.svg",
      accentAlt: "Night work helmet",
    },
  }),
];

export const THEMES: Record<ThemeKey, ThemeDefinition> = THEMES_ARRAY.reduce(
  (acc, theme) => {
    acc[theme.key] = theme;
    return acc;
  },
  {} as Record<ThemeKey, ThemeDefinition>
);

export function getThemeDefinition(key: ThemeKey): ThemeDefinition {
  return THEMES[key] ?? THEMES.general;
}

export function getThemeVariantDefinition(
  key: ThemeKey,
  variant: ThemeVariant
): ThemeVariantDefinition {
  const theme = getThemeDefinition(key);
  return theme.variants[variant] ?? theme.variants.light;
}

export function resolveThemeCssVariables(key: ThemeKey, variant: ThemeVariant): Record<string, string> {
  return getThemeVariantDefinition(key, variant).cssVariables;
}

export function listThemesSorted(): ThemeDefinition[] {
  return [...THEMES_ARRAY].sort((a, b) => a.order - b.order);
}

export function isValidThemeKey(value: unknown): value is ThemeKey {
  return typeof value === "string" && (THEME_KEYS as string[]).includes(value);
}

export function isValidVariant(value: unknown): value is ThemeVariant {
  return value === "light" || value === "dark";
}

