import type { GymMeetPageTemplateMeta, GymMeetTemplateId } from "./types";

export const DEFAULT_GYM_MEET_TEMPLATE_ID: GymMeetTemplateId = "airborne-atlas";
export const DEFAULT_NEW_GYM_MEET_TEMPLATE_ID: GymMeetTemplateId = "airborne-atlas";

export const GYM_MEET_TEMPLATE_LIBRARY: GymMeetPageTemplateMeta[] = [
  {
    "id": "airborne-atlas",
    "name": "Airborne Atlas",
    "style": "Editorial",
    "description": "Airborne Atlas pairs editorial artwork with a layered meet journal.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Airborne Atlas Invitational",
    "previewKicker": "A beautiful day to fly",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "playfair",
    "artwork": "/templates/gymnastics/collection-2026/airborne-atlas.webp",
    "artworkAlt": "Balance beam arabesque in a sunlit timber-roof gymnasium; editorial sports photography, navy leotard, warm ivory architecture",
    "background": "#f6f1e7",
    "foreground": "#17293c",
    "accent": "#b15d35",
    "displayFont": "Gym Playfair",
    "sampleVenue": "Atlas Fieldhouse",
    "sampleLocation": "Denver, CO",
    "sampleHost": "Airborne Gymnastics",
    "sampleNote": "Join Airborne Gymnastics at Atlas Fieldhouse for the Airborne Atlas Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "airborne-atlas",
    "bodyStyle": "schedule"
  },
  {
    "id": "neon-runway",
    "name": "Neon Runway",
    "style": "Electric",
    "description": "Neon Runway pairs electric artwork with a bold arena poster.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Neon Runway Invitational",
    "previewKicker": "Small steps. Extraordinary moments.",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "orbitron",
    "artwork": "/templates/gymnastics/collection-2026/neon-runway.webp",
    "artworkAlt": "Low-angle regulation vault runway with an adult gymnast sprinting toward a vault table, lime runway markings and ultraviolet arena lights, cinematic sports photography",
    "background": "#101321",
    "foreground": "#f5f5ff",
    "accent": "#bbfc58",
    "displayFont": "Gym Orbitron",
    "sampleVenue": "Voltage Arena",
    "sampleLocation": "Austin, TX",
    "sampleHost": "Neon Gymnastics",
    "sampleNote": "Join Neon Gymnastics at Voltage Arena for the Neon Runway Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "neon-runway",
    "bodyStyle": "schedule"
  },
  {
    "id": "petal-poise",
    "name": "Petal & Poise",
    "style": "Botanical",
    "description": "Petal & Poise pairs botanical artwork with a framed invitation.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Petal Poise Invitational",
    "previewKicker": "Bring your team spirit",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "cormorant",
    "artwork": "/templates/gymnastics/collection-2026/petal-poise.webp",
    "artworkAlt": "Delicate gouache painting of an adult gymnast on a balance beam surrounded by floating magnolia petals, blush and mulberry, pale paper texture",
    "background": "#faf0f2",
    "foreground": "#4b2541",
    "accent": "#a74169",
    "displayFont": "Gym Cormorant",
    "sampleVenue": "Magnolia Pavilion",
    "sampleLocation": "Savannah, GA",
    "sampleHost": "Petal Gymnastics",
    "sampleNote": "Join Petal Gymnastics at Magnolia Pavilion for the Petal Poise Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "petal-poise",
    "bodyStyle": "schedule"
  },
  {
    "id": "copper-grip",
    "name": "Copper Grip",
    "style": "Artisan",
    "description": "Copper Grip pairs artisan artwork with a asymmetric photo story.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Copper Grip Invitational",
    "previewKicker": "Find your next great moment",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "anton",
    "artwork": "/templates/gymnastics/collection-2026/copper-grip.webp",
    "artworkAlt": "Macro still life of leather gymnastics hand grips and chalk on a copper-brown worn wooden bench, tactile dramatic studio photography",
    "background": "#f0e2cf",
    "foreground": "#452919",
    "accent": "#92532d",
    "displayFont": "Gym Anton",
    "sampleVenue": "Foundry Sports Hall",
    "sampleLocation": "Pittsburgh, PA",
    "sampleHost": "Copper Gymnastics",
    "sampleNote": "Join Copper Gymnastics at Foundry Sports Hall for the Copper Grip Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "copper-grip",
    "bodyStyle": "schedule"
  },
  {
    "id": "tidal-tumble",
    "name": "Tidal Tumble",
    "style": "Coastal",
    "description": "Tidal Tumble pairs coastal artwork with a airy team program.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Tidal Tumble Invitational",
    "previewKicker": "Every routine tells a story",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "montserrat",
    "artwork": "/templates/gymnastics/collection-2026/tidal-tumble.webp",
    "artworkAlt": "Painterly ocean-blue wave curling into the sweep of an adult gymnast floor leap, sophisticated gouache illustration, frothy white motion and sea glass",
    "background": "#eaf6f6",
    "foreground": "#124953",
    "accent": "#13747e",
    "displayFont": "Gym Montserrat",
    "sampleVenue": "Seabright Athletic Center",
    "sampleLocation": "San Diego, CA",
    "sampleHost": "Tidal Gymnastics",
    "sampleNote": "Join Tidal Gymnastics at Seabright Athletic Center for the Tidal Tumble Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "tidal-tumble",
    "bodyStyle": "schedule"
  },
  {
    "id": "crimson-collegiate",
    "name": "Crimson Collegiate",
    "style": "Heritage",
    "description": "Crimson Collegiate pairs heritage artwork with a sculptural event cover.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Crimson Collegiate Invitational",
    "previewKicker": "A weekend worth cheering for",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "playfair",
    "artwork": "/templates/gymnastics/collection-2026/crimson-collegiate.webp",
    "artworkAlt": "Film photograph of an empty historic collegiate gymnastics arena with crimson mats and dark wooden bleachers, symmetrical composition, golden afternoon",
    "background": "#f7eddd",
    "foreground": "#661f2a",
    "accent": "#9d303b",
    "displayFont": "Gym Playfair",
    "sampleVenue": "Heritage Fieldhouse",
    "sampleLocation": "Madison, WI",
    "sampleHost": "Crimson Gymnastics",
    "sampleNote": "Join Crimson Gymnastics at Heritage Fieldhouse for the Crimson Collegiate Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "crimson-collegiate",
    "bodyStyle": "schedule"
  },
  {
    "id": "moonbeam-balance",
    "name": "Moonbeam Balance",
    "style": "Celestial",
    "description": "Moonbeam Balance pairs celestial artwork with a layered meet journal.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Moonbeam Balance Invitational",
    "previewKicker": "A beautiful day to fly",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "cormorant",
    "artwork": "/templates/gymnastics/collection-2026/moonbeam-balance.webp",
    "artworkAlt": "Dreamlike fine art illustration of a single balance beam under a enormous luminous moon, silver chalk stars, midnight blue velvet sky, no people",
    "background": "#171e3e",
    "foreground": "#f6efda",
    "accent": "#dac58a",
    "displayFont": "Gym Cormorant",
    "sampleVenue": "Lunar Gymnasium",
    "sampleLocation": "Flagstaff, AZ",
    "sampleHost": "Moonbeam Gymnastics",
    "sampleNote": "Join Moonbeam Gymnastics at Lunar Gymnasium for the Moonbeam Balance Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "moonbeam-balance",
    "bodyStyle": "schedule"
  },
  {
    "id": "citrus-springboard",
    "name": "Citrus Springboard",
    "style": "Playful",
    "description": "Citrus Springboard pairs playful artwork with a bold arena poster.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Citrus Springboard Invitational",
    "previewKicker": "Small steps. Extraordinary moments.",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "bungee",
    "artwork": "/templates/gymnastics/collection-2026/citrus-springboard.webp",
    "artworkAlt": "Playful clay sculpture of a gymnastics springboard and cheerful abstract orange segments bouncing in a sun-yellow studio, sophisticated stop-motion miniature",
    "background": "#fff4d3",
    "foreground": "#49381c",
    "accent": "#b05d05",
    "displayFont": "Gym Bangers",
    "sampleVenue": "Zest Recreation Hall",
    "sampleLocation": "Orlando, FL",
    "sampleHost": "Citrus Gymnastics",
    "sampleNote": "Join Citrus Gymnastics at Zest Recreation Hall for the Citrus Springboard Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "citrus-springboard",
    "bodyStyle": "schedule"
  },
  {
    "id": "monochrome-flight",
    "name": "Monochrome Flight",
    "style": "Minimal",
    "description": "Monochrome Flight pairs minimal artwork with a framed invitation.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Monochrome Flight Invitational",
    "previewKicker": "Bring your team spirit",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "anton",
    "artwork": "/templates/gymnastics/collection-2026/monochrome-flight.webp",
    "artworkAlt": "High contrast black and white film photograph of an adult male gymnast extended horizontally above a regulation high bar, powerful precise anatomy, dark background",
    "background": "#f2f2ef",
    "foreground": "#1c2020",
    "accent": "#515a5a",
    "displayFont": "Gym Anton",
    "sampleVenue": "Frame Athletics",
    "sampleLocation": "Portland, OR",
    "sampleHost": "Monochrome Gymnastics",
    "sampleNote": "Join Monochrome Gymnastics at Frame Athletics for the Monochrome Flight Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "monochrome-flight",
    "bodyStyle": "schedule"
  },
  {
    "id": "desert-dismount",
    "name": "Desert Dismount",
    "style": "Destination",
    "description": "Desert Dismount pairs destination artwork with a asymmetric photo story.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Desert Dismount Invitational",
    "previewKicker": "Find your next great moment",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "barlow-condensed",
    "artwork": "/templates/gymnastics/collection-2026/desert-dismount.webp",
    "artworkAlt": "Warm linocut illustration of an adult gymnast landing on a mat framed by terracotta desert mesas and a rising apricot sun, artistic symbolic landscape",
    "background": "#f4e4d4",
    "foreground": "#613a32",
    "accent": "#a45137",
    "displayFont": "Gym Condensed",
    "sampleVenue": "Mesa Event Center",
    "sampleLocation": "Tucson, AZ",
    "sampleHost": "Desert Gymnastics",
    "sampleNote": "Join Desert Gymnastics at Mesa Event Center for the Desert Dismount Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "desert-dismount",
    "bodyStyle": "schedule"
  },
  {
    "id": "prism-routine",
    "name": "Prism Routine",
    "style": "Modern",
    "description": "Prism Routine pairs modern artwork with a airy team program.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Prism Routine Invitational",
    "previewKicker": "Every routine tells a story",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "sora",
    "artwork": "/templates/gymnastics/collection-2026/prism-routine.webp",
    "artworkAlt": "Prismatic glass sculptural arc suggesting a floor routine ribbon of motion above lavender gym mats, premium 3D still life with rainbow refractions",
    "background": "#efeffb",
    "foreground": "#302d62",
    "accent": "#6650a6",
    "displayFont": "Gym Space",
    "sampleVenue": "Spectrum Pavilion",
    "sampleLocation": "Seattle, WA",
    "sampleHost": "Prism Gymnastics",
    "sampleNote": "Join Prism Gymnastics at Spectrum Pavilion for the Prism Routine Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "prism-routine",
    "bodyStyle": "notebook"
  },
  {
    "id": "maple-medal",
    "name": "Maple Medal",
    "style": "Seasonal",
    "description": "Maple Medal pairs seasonal artwork with a sculptural event cover.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Maple Medal Invitational",
    "previewKicker": "A weekend worth cheering for",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "playfair",
    "artwork": "/templates/gymnastics/collection-2026/maple-medal.webp",
    "artworkAlt": "Editorial still life of a bronze gymnastics medal with a plain burgundy ribbon beside amber maple leaves on cream linen, no lettering",
    "background": "#f4e9d3",
    "foreground": "#543a26",
    "accent": "#996027",
    "displayFont": "Gym Playfair",
    "sampleVenue": "Harvest Sports Barn",
    "sampleLocation": "Burlington, VT",
    "sampleHost": "Maple Gymnastics",
    "sampleNote": "Join Maple Gymnastics at Harvest Sports Barn for the Maple Medal Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "maple-medal",
    "bodyStyle": "notebook"
  },
  {
    "id": "electric-orchid",
    "name": "Electric Orchid",
    "style": "Electric",
    "description": "Electric Orchid pairs electric artwork with a layered meet journal.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Electric Orchid Invitational",
    "previewKicker": "A beautiful day to fly",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "audiowide",
    "artwork": "/templates/gymnastics/collection-2026/electric-orchid.webp",
    "artworkAlt": "Photographic adult gymnast preparing on uneven bars with orchid-magenta light and plum-colored arena darkness, wide scene with realistic equipment",
    "background": "#241629",
    "foreground": "#fceafb",
    "accent": "#e181d6",
    "displayFont": "Gym Orbitron",
    "sampleVenue": "Orchid Arena",
    "sampleLocation": "Miami, FL",
    "sampleHost": "Electric Gymnastics",
    "sampleNote": "Join Electric Gymnastics at Orchid Arena for the Electric Orchid Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "electric-orchid",
    "bodyStyle": "notebook"
  },
  {
    "id": "porcelain-podium",
    "name": "Porcelain Podium",
    "style": "Elegant",
    "description": "Porcelain Podium pairs elegant artwork with a bold arena poster.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Porcelain Podium Invitational",
    "previewKicker": "Small steps. Extraordinary moments.",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "cormorant",
    "artwork": "/templates/gymnastics/collection-2026/porcelain-podium.webp",
    "artworkAlt": "Sculptural white porcelain awards podium and pale blue chalk clouds, fine blue botanical glaze details, gallery still-life photography, no numbers or text",
    "background": "#f4f7f9",
    "foreground": "#264459",
    "accent": "#56728c",
    "displayFont": "Gym Cormorant",
    "sampleVenue": "Celadon Hall",
    "sampleLocation": "Charleston, SC",
    "sampleHost": "Porcelain Gymnastics",
    "sampleNote": "Join Porcelain Gymnastics at Celadon Hall for the Porcelain Podium Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "porcelain-podium",
    "bodyStyle": "notebook"
  },
  {
    "id": "rally-pennants",
    "name": "Rally Pennants",
    "style": "Heritage",
    "description": "Rally Pennants pairs heritage artwork with a framed invitation.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Rally Pennants Invitational",
    "previewKicker": "Bring your team spirit",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "league-spartan",
    "artwork": "/templates/gymnastics/collection-2026/rally-pennants.webp",
    "artworkAlt": "Cut-paper collage of forest green and rust triangular sports pennants over a gymnastics floor diagram, handmade textured paper, celebratory and crisp, no lettering",
    "background": "#faf1d7",
    "foreground": "#203f37",
    "accent": "#a45233",
    "displayFont": "Gym Spartan",
    "sampleVenue": "Pennant Fieldhouse",
    "sampleLocation": "Ann Arbor, MI",
    "sampleHost": "Rally Gymnastics",
    "sampleNote": "Join Rally Gymnastics at Pennant Fieldhouse for the Rally Pennants Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "rally-pennants",
    "bodyStyle": "notebook"
  },
  {
    "id": "rose-quartz-rise",
    "name": "Rose Quartz Rise",
    "style": "Elegant",
    "description": "Rose Quartz Rise pairs elegant artwork with a asymmetric photo story.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Rose Quartz Rise Invitational",
    "previewKicker": "Find your next great moment",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "playfair",
    "artwork": "/templates/gymnastics/collection-2026/rose-quartz-rise.webp",
    "artworkAlt": "Translucent rose quartz sculptures framing a pink balance beam miniature, airy luxury product photograph, soft shadows and pearl light",
    "background": "#f9eef0",
    "foreground": "#673b4d",
    "accent": "#a34f6d",
    "displayFont": "Gym Playfair",
    "sampleVenue": "Quartz Pavilion",
    "sampleLocation": "Scottsdale, AZ",
    "sampleHost": "Rose Gymnastics",
    "sampleNote": "Join Rose Gymnastics at Quartz Pavilion for the Rose Quartz Rise Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "rose-quartz-rise",
    "bodyStyle": "notebook"
  },
  {
    "id": "velocity-blueprint",
    "name": "Velocity Blueprint",
    "style": "Technical",
    "description": "Velocity Blueprint pairs technical artwork with a airy team program.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Velocity Blueprint Invitational",
    "previewKicker": "Every routine tells a story",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "ibm-plex-mono",
    "artwork": "/templates/gymnastics/collection-2026/velocity-blueprint.webp",
    "artworkAlt": "Cyanotype technical illustration of regulation parallel bars with precise fine lines and motion arcs, rich cobalt and pale blue paper, no text or numbers",
    "background": "#eaf3fc",
    "foreground": "#183b68",
    "accent": "#33639d",
    "displayFont": "ui-monospace",
    "sampleVenue": "Vector Training Center",
    "sampleLocation": "Huntsville, AL",
    "sampleHost": "Velocity Gymnastics",
    "sampleNote": "Join Velocity Gymnastics at Vector Training Center for the Velocity Blueprint Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "velocity-blueprint",
    "bodyStyle": "notebook"
  },
  {
    "id": "jungle-cartwheel",
    "name": "Jungle Cartwheel",
    "style": "Botanical",
    "description": "Jungle Cartwheel pairs botanical artwork with a sculptural event cover.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Jungle Cartwheel Invitational",
    "previewKicker": "A weekend worth cheering for",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "poppins",
    "artwork": "/templates/gymnastics/collection-2026/jungle-cartwheel.webp",
    "artworkAlt": "Vibrant hand-painted adult gymnast cartwheeling across a soft gymnastics mat surrounded by oversized tropical monstera leaves, lush emerald and lime gouache",
    "background": "#edf3d7",
    "foreground": "#284834",
    "accent": "#527d37",
    "displayFont": "Gym Rounded",
    "sampleVenue": "Canopy Sports Lodge",
    "sampleLocation": "Tampa, FL",
    "sampleHost": "Jungle Gymnastics",
    "sampleNote": "Join Jungle Gymnastics at Canopy Sports Lodge for the Jungle Cartwheel Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "jungle-cartwheel",
    "bodyStyle": "notebook"
  },
  {
    "id": "saffron-salute",
    "name": "Saffron Salute",
    "style": "Artisan",
    "description": "Saffron Salute pairs artisan artwork with a layered meet journal.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Saffron Salute Invitational",
    "previewKicker": "A beautiful day to fly",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "kanit",
    "artwork": "/templates/gymnastics/collection-2026/saffron-salute.webp",
    "artworkAlt": "Handcrafted risograph illustration of a gymnast standing tall with both arms raised on a saffron floor mat, burnt sienna shadows and ochre ink textures",
    "background": "#fcf0cd",
    "foreground": "#65342a",
    "accent": "#9e5422",
    "displayFont": "Gym Anton",
    "sampleVenue": "Marigold Events Hall",
    "sampleLocation": "Santa Fe, NM",
    "sampleHost": "Saffron Gymnastics",
    "sampleNote": "Join Saffron Gymnastics at Marigold Events Hall for the Saffron Salute Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "saffron-salute",
    "bodyStyle": "notebook"
  },
  {
    "id": "silver-apparatus",
    "name": "Silver Apparatus",
    "style": "Minimal",
    "description": "Silver Apparatus pairs minimal artwork with a bold arena poster.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Silver Apparatus Invitational",
    "previewKicker": "Small steps. Extraordinary moments.",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "exo2",
    "artwork": "/templates/gymnastics/collection-2026/silver-apparatus.webp",
    "artworkAlt": "Sleek architectural photograph of still rings hanging in a clean steel-and-glass training hall, silvery morning light, perfectly composed industrial geometry",
    "background": "#e9edf1",
    "foreground": "#34404e",
    "accent": "#586c80",
    "displayFont": "Gym Space",
    "sampleVenue": "Alloy Athletic Hall",
    "sampleLocation": "Columbus, OH",
    "sampleHost": "Silver Gymnastics",
    "sampleNote": "Join Silver Gymnastics at Alloy Athletic Hall for the Silver Apparatus Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "silver-apparatus",
    "bodyStyle": "notebook"
  },
  {
    "id": "aurora-chalk",
    "name": "Aurora Chalk",
    "style": "Celestial",
    "description": "Aurora Chalk pairs celestial artwork with a framed invitation.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Aurora Chalk Invitational",
    "previewKicker": "Bring your team spirit",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "sora",
    "artwork": "/templates/gymnastics/collection-2026/aurora-chalk.webp",
    "artworkAlt": "Fine-art photographic chalk dust plume glowing green like an aurora above chalk bowl in a dark gym, mesmerizing fluid details, teal and seafoam",
    "background": "#0e3033",
    "foreground": "#e4faf2",
    "accent": "#84d9bc",
    "displayFont": "Gym Space",
    "sampleVenue": "Boreal Center",
    "sampleLocation": "Anchorage, AK",
    "sampleHost": "Aurora Gymnastics",
    "sampleNote": "Join Aurora Gymnastics at Boreal Center for the Aurora Chalk Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "aurora-chalk",
    "bodyStyle": "rail"
  },
  {
    "id": "peach-practice",
    "name": "Peach Practice",
    "style": "Playful",
    "description": "Peach Practice pairs playful artwork with a asymmetric photo story.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Peach Practice Invitational",
    "previewKicker": "Find your next great moment",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "poppins",
    "artwork": "/templates/gymnastics/collection-2026/peach-practice.webp",
    "artworkAlt": "Soft pastel illustration of neatly arranged peach gymnastics mats, a lavender water bottle and white ankle socks, sunny gentle club-practice atmosphere",
    "background": "#fff0e3",
    "foreground": "#623c37",
    "accent": "#b86646",
    "displayFont": "Gym Rounded",
    "sampleVenue": "Peachwood Gym",
    "sampleLocation": "Atlanta, GA",
    "sampleHost": "Peach Gymnastics",
    "sampleNote": "Join Peach Gymnastics at Peachwood Gym for the Peach Practice Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "peach-practice",
    "bodyStyle": "rail"
  },
  {
    "id": "grandstand-gold",
    "name": "Grandstand Gold",
    "style": "Elegant",
    "description": "Grandstand Gold pairs elegant artwork with a airy team program.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Grandstand Gold Invitational",
    "previewKicker": "Every routine tells a story",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "oswald",
    "artwork": "/templates/gymnastics/collection-2026/grandstand-gold.webp",
    "artworkAlt": "Cinematic photograph from the upper seats of a magnificent gymnastics arena with warm golden spotlights over a floor exercise mat, anticipation and scale",
    "background": "#201d16",
    "foreground": "#fbf3d8",
    "accent": "#ddbd67",
    "displayFont": "Gym Condensed",
    "sampleVenue": "Crown Exhibition Hall",
    "sampleLocation": "Las Vegas, NV",
    "sampleHost": "Grandstand Gymnastics",
    "sampleNote": "Join Grandstand Gymnastics at Crown Exhibition Hall for the Grandstand Gold Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "grandstand-gold",
    "bodyStyle": "rail"
  },
  {
    "id": "indigo-ink",
    "name": "Indigo Ink",
    "style": "Artisan",
    "description": "Indigo Ink pairs artisan artwork with a sculptural event cover.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Indigo Ink Invitational",
    "previewKicker": "A weekend worth cheering for",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "space-mono",
    "artwork": "/templates/gymnastics/collection-2026/indigo-ink.webp",
    "artworkAlt": "Expressive indigo sumi ink brush painting of an adult gymnast swinging between uneven bars, fluid dynamic negative space on ivory handmade paper",
    "background": "#f1efe4",
    "foreground": "#25385b",
    "accent": "#466188",
    "displayFont": "ui-monospace",
    "sampleVenue": "Inkstone Pavilion",
    "sampleLocation": "Asheville, NC",
    "sampleHost": "Indigo Gymnastics",
    "sampleNote": "Join Indigo Gymnastics at Inkstone Pavilion for the Indigo Ink Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "indigo-ink",
    "bodyStyle": "rail"
  },
  {
    "id": "coral-clubhouse",
    "name": "Coral Clubhouse",
    "style": "Coastal",
    "description": "Coral Clubhouse pairs coastal artwork with a layered meet journal.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Coral Clubhouse Invitational",
    "previewKicker": "A beautiful day to fly",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "montserrat",
    "artwork": "/templates/gymnastics/collection-2026/coral-clubhouse.webp",
    "artworkAlt": "Retro seaside sports-club illustration with coral-red gymnastics mats and turquoise arched windows overlooking palms, charming sunlit architecture",
    "background": "#fce9df",
    "foreground": "#633b3e",
    "accent": "#ae5254",
    "displayFont": "Gym Montserrat",
    "sampleVenue": "Palmetto Club Hall",
    "sampleLocation": "Sarasota, FL",
    "sampleHost": "Coral Gymnastics",
    "sampleNote": "Join Coral Gymnastics at Palmetto Club Hall for the Coral Clubhouse Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "coral-clubhouse",
    "bodyStyle": "rail"
  },
  {
    "id": "alpine-ascent",
    "name": "Alpine Ascent",
    "style": "Destination",
    "description": "Alpine Ascent pairs destination artwork with a bold arena poster.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Alpine Ascent Invitational",
    "previewKicker": "Small steps. Extraordinary moments.",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "league-spartan",
    "artwork": "/templates/gymnastics/collection-2026/alpine-ascent.webp",
    "artworkAlt": "Vintage alpine travel-poster illustration of a balance beam inside a chalet-like sports hall with snowy mountain peaks beyond broad windows, pine and cream",
    "background": "#eef0e3",
    "foreground": "#334b44",
    "accent": "#5b7666",
    "displayFont": "Gym Spartan",
    "sampleVenue": "Ridgecrest Lodge",
    "sampleLocation": "Bozeman, MT",
    "sampleHost": "Alpine Gymnastics",
    "sampleNote": "Join Alpine Gymnastics at Ridgecrest Lodge for the Alpine Ascent Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "alpine-ascent",
    "bodyStyle": "rail"
  },
  {
    "id": "confetti-kip",
    "name": "Confetti Kip",
    "style": "Playful",
    "description": "Confetti Kip pairs playful artwork with a framed invitation.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Confetti Kip Invitational",
    "previewKicker": "Bring your team spirit",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "bungee",
    "artwork": "/templates/gymnastics/collection-2026/confetti-kip.webp",
    "artworkAlt": "Joyful torn-paper collage of an adult gymnast performing a kip on a horizontal bar, scattered confetti in lilac orange and cobalt, bold handmade forms",
    "background": "#fff3ea",
    "foreground": "#49305b",
    "accent": "#9a4b91",
    "displayFont": "Gym Bangers",
    "sampleVenue": "Jubilee Recreation Center",
    "sampleLocation": "Nashville, TN",
    "sampleHost": "Confetti Gymnastics",
    "sampleNote": "Join Confetti Gymnastics at Jubilee Recreation Center for the Confetti Kip Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "confetti-kip",
    "bodyStyle": "rail"
  },
  {
    "id": "midnight-marquee",
    "name": "Midnight Marquee",
    "style": "Electric",
    "description": "Midnight Marquee pairs electric artwork with a asymmetric photo story.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Midnight Marquee Invitational",
    "previewKicker": "Find your next great moment",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "anton",
    "artwork": "/templates/gymnastics/collection-2026/midnight-marquee.webp",
    "artworkAlt": "Noir sports photograph of one regulation pommel horse under a hard amber spotlight, cinematic smoky black arena, elegant negative space",
    "background": "#171820",
    "foreground": "#f5ead7",
    "accent": "#e0a376",
    "displayFont": "Gym Anton",
    "sampleVenue": "Beacon Arena",
    "sampleLocation": "New York, NY",
    "sampleHost": "Midnight Gymnastics",
    "sampleNote": "Join Midnight Gymnastics at Beacon Arena for the Midnight Marquee Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "midnight-marquee",
    "bodyStyle": "rail"
  },
  {
    "id": "willow-warmup",
    "name": "Willow Warmup",
    "style": "Botanical",
    "description": "Willow Warmup pairs botanical artwork with a airy team program.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Willow Warmup Invitational",
    "previewKicker": "Every routine tells a story",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "cormorant",
    "artwork": "/templates/gymnastics/collection-2026/willow-warmup.webp",
    "artworkAlt": "Soft watercolor of willow branches reflected on polished gym flooring beside a linen-covered bench and rolled sage training mat, serene botanical naturalism",
    "background": "#edf1e6",
    "foreground": "#3f5345",
    "accent": "#708162",
    "displayFont": "Gym Cormorant",
    "sampleVenue": "Willowbrook Hall",
    "sampleLocation": "Eugene, OR",
    "sampleHost": "Willow Gymnastics",
    "sampleNote": "Join Willow Gymnastics at Willowbrook Hall for the Willow Warmup Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "willow-warmup",
    "bodyStyle": "rail"
  },
  {
    "id": "studio-arc",
    "name": "Studio Arc",
    "style": "Modern",
    "description": "Studio Arc pairs modern artwork with a sculptural event cover.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Studio Arc Invitational",
    "previewKicker": "A weekend worth cheering for",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "manrope",
    "artwork": "/templates/gymnastics/collection-2026/studio-arc.webp",
    "artworkAlt": "Bauhaus-inspired physical sculpture of a gymnastics arch and springboard with warm wooden spheres on ivory background, modernist studio still life",
    "background": "#f1ece5",
    "foreground": "#433d36",
    "accent": "#966647",
    "displayFont": "Gym Inter",
    "sampleVenue": "Arc Arts & Athletics",
    "sampleLocation": "Minneapolis, MN",
    "sampleHost": "Studio Gymnastics",
    "sampleNote": "Join Studio Gymnastics at Arc Arts & Athletics for the Studio Arc Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "studio-arc",
    "bodyStyle": "rail"
  },
  {
    "id": "cherry-blossom-vault",
    "name": "Cherry Blossom Vault",
    "style": "Botanical",
    "description": "Cherry Blossom Vault pairs botanical artwork with a layered meet journal.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Cherry Blossom Vault Invitational",
    "previewKicker": "A beautiful day to fly",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "playfair",
    "artwork": "/templates/gymnastics/collection-2026/cherry-blossom-vault.webp",
    "artworkAlt": "Japanese woodblock inspired illustration of a regulation vault table with cherry blossom branches and an airy pink sky, restrained elegant print texture",
    "background": "#f9e8ec",
    "foreground": "#5d2d43",
    "accent": "#ad5471",
    "displayFont": "Gym Playfair",
    "sampleVenue": "Sakura Sports Pavilion",
    "sampleLocation": "Washington, DC",
    "sampleHost": "Cherry Gymnastics",
    "sampleNote": "Join Cherry Gymnastics at Sakura Sports Pavilion for the Cherry Blossom Vault Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "cherry-blossom-vault",
    "bodyStyle": "tiles"
  },
  {
    "id": "oceanic-rings",
    "name": "Oceanic Rings",
    "style": "Coastal",
    "description": "Oceanic Rings pairs coastal artwork with a bold arena poster.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Oceanic Rings Invitational",
    "previewKicker": "Small steps. Extraordinary moments.",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "exo2",
    "artwork": "/templates/gymnastics/collection-2026/oceanic-rings.webp",
    "artworkAlt": "Photoreal close-up of two wooden gymnastics rings hanging against large aqua-tinted gym windows, rippling water reflections dancing across the wood",
    "background": "#e2f4f3",
    "foreground": "#1c4d60",
    "accent": "#337d8c",
    "displayFont": "Gym Space",
    "sampleVenue": "Harborlight Gym",
    "sampleLocation": "Newport, RI",
    "sampleHost": "Oceanic Gymnastics",
    "sampleNote": "Join Oceanic Gymnastics at Harborlight Gym for the Oceanic Rings Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "oceanic-rings",
    "bodyStyle": "tiles"
  },
  {
    "id": "flame-focus",
    "name": "Flame & Focus",
    "style": "Electric",
    "description": "Flame & Focus pairs electric artwork with a framed invitation.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Flame Focus Invitational",
    "previewKicker": "Bring your team spirit",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "kanit",
    "artwork": "/templates/gymnastics/collection-2026/flame-focus.webp",
    "artworkAlt": "Editorial sports portrait scene of an adult gymnast chalking hands at a chalk bowl, copper-red backlight and smoke-like chalk powder, determined candid atmosphere",
    "background": "#301b21",
    "foreground": "#ffede1",
    "accent": "#f0a36c",
    "displayFont": "Gym Anton",
    "sampleVenue": "Ember Athletics Hall",
    "sampleLocation": "Phoenix, AZ",
    "sampleHost": "Flame Gymnastics",
    "sampleNote": "Join Flame Gymnastics at Ember Athletics Hall for the Flame Focus Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "flame-focus",
    "bodyStyle": "tiles"
  },
  {
    "id": "lilac-leap",
    "name": "Lilac Leap",
    "style": "Elegant",
    "description": "Lilac Leap pairs elegant artwork with a asymmetric photo story.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Lilac Leap Invitational",
    "previewKicker": "Find your next great moment",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "cormorant",
    "artwork": "/templates/gymnastics/collection-2026/lilac-leap.webp",
    "artworkAlt": "Pastel impressionist painting of an adult gymnast mid-split-leap on floor exercise, lilac tulle-like painted motion strokes and warm white light",
    "background": "#f3edf9",
    "foreground": "#514365",
    "accent": "#8964a7",
    "displayFont": "Gym Cormorant",
    "sampleVenue": "Wisteria Performance Hall",
    "sampleLocation": "Lexington, KY",
    "sampleHost": "Lilac Gymnastics",
    "sampleNote": "Join Lilac Gymnastics at Wisteria Performance Hall for the Lilac Leap Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "lilac-leap",
    "bodyStyle": "tiles"
  },
  {
    "id": "court-of-champions",
    "name": "Court of Champions",
    "style": "Heritage",
    "description": "Court of Champions pairs heritage artwork with a airy team program.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Court of Champions Invitational",
    "previewKicker": "Every routine tells a story",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "oswald",
    "artwork": "/templates/gymnastics/collection-2026/court-of-champions.webp",
    "artworkAlt": "Vintage sports editorial still life of green-striped warmup jacket, wooden gym bench and gold cup, afternoon window light, no logos or lettering",
    "background": "#ecf0e5",
    "foreground": "#284b3a",
    "accent": "#527a43",
    "displayFont": "Gym Condensed",
    "sampleVenue": "Laurel Fieldhouse",
    "sampleLocation": "South Bend, IN",
    "sampleHost": "Court Gymnastics",
    "sampleNote": "Join Court Gymnastics at Laurel Fieldhouse for the Court of Champions Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "court-of-champions",
    "bodyStyle": "tiles"
  },
  {
    "id": "papaya-pop",
    "name": "Papaya Pop",
    "style": "Playful",
    "description": "Papaya Pop pairs playful artwork with a sculptural event cover.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Papaya Pop Invitational",
    "previewKicker": "A weekend worth cheering for",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "bungee",
    "artwork": "/templates/gymnastics/collection-2026/papaya-pop.webp",
    "artworkAlt": "Bold Memphis-style illustration of a gymnastics floor mat, peach vault and papaya-orange geometric zigzags, playful tropical graphic composition",
    "background": "#fff0d4",
    "foreground": "#754c30",
    "accent": "#bf662f",
    "displayFont": "Gym Bangers",
    "sampleVenue": "Papaya Activity Center",
    "sampleLocation": "Honolulu, HI",
    "sampleHost": "Papaya Gymnastics",
    "sampleNote": "Join Papaya Gymnastics at Papaya Activity Center for the Papaya Pop Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "papaya-pop",
    "bodyStyle": "tiles"
  },
  {
    "id": "obsidian-precision",
    "name": "Obsidian Precision",
    "style": "Minimal",
    "description": "Obsidian Precision pairs minimal artwork with a layered meet journal.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Obsidian Precision Invitational",
    "previewKicker": "A beautiful day to fly",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "orbitron",
    "artwork": "/templates/gymnastics/collection-2026/obsidian-precision.webp",
    "artworkAlt": "Ultra-minimal black stone sculpture of a gymnast holding an iron cross on rings, believable adult athletic proportions, graphite background and thin silver rim light",
    "background": "#191d21",
    "foreground": "#f2f3eb",
    "accent": "#b7c5c7",
    "displayFont": "Gym Orbitron",
    "sampleVenue": "Onyx Arena",
    "sampleLocation": "Dallas, TX",
    "sampleHost": "Obsidian Gymnastics",
    "sampleNote": "Join Obsidian Gymnastics at Onyx Arena for the Obsidian Precision Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "obsidian-precision",
    "bodyStyle": "tiles"
  },
  {
    "id": "bluebird-morning",
    "name": "Bluebird Morning",
    "style": "Seasonal",
    "description": "Bluebird Morning pairs seasonal artwork with a bold arena poster.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Bluebird Morning Invitational",
    "previewKicker": "Small steps. Extraordinary moments.",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "poppins",
    "artwork": "/templates/gymnastics/collection-2026/bluebird-morning.webp",
    "artworkAlt": "Delicate colored-pencil illustration of a sunlit pale-blue gymnastics club interior, white balance beam and two small bluebirds perched on the outside windowsill",
    "background": "#edf6fb",
    "foreground": "#2b4c62",
    "accent": "#57809b",
    "displayFont": "Gym Rounded",
    "sampleVenue": "Bluebird Community Gym",
    "sampleLocation": "Raleigh, NC",
    "sampleHost": "Bluebird Gymnastics",
    "sampleNote": "Join Bluebird Gymnastics at Bluebird Community Gym for the Bluebird Morning Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "bluebird-morning",
    "bodyStyle": "tiles"
  },
  {
    "id": "terrazzo-team",
    "name": "Terrazzo Team",
    "style": "Modern",
    "description": "Terrazzo Team pairs modern artwork with a framed invitation.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Terrazzo Team Invitational",
    "previewKicker": "Bring your team spirit",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "sora",
    "artwork": "/templates/gymnastics/collection-2026/terrazzo-team.webp",
    "artworkAlt": "Premium still life of a rolled gym mat and chalk bowl on colorful terrazzo stone in salmon sage and cream, sculptural morning shadows, design magazine photography",
    "background": "#f3ede7",
    "foreground": "#534741",
    "accent": "#9c6456",
    "displayFont": "Gym Space",
    "sampleVenue": "Mosaic Sports House",
    "sampleLocation": "Kansas City, MO",
    "sampleHost": "Terrazzo Gymnastics",
    "sampleNote": "Join Terrazzo Gymnastics at Mosaic Sports House for the Terrazzo Team Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "terrazzo-team",
    "bodyStyle": "tiles"
  },
  {
    "id": "amethyst-arena",
    "name": "Amethyst Arena",
    "style": "Celestial",
    "description": "Amethyst Arena pairs celestial artwork with a asymmetric photo story.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Amethyst Arena Invitational",
    "previewKicker": "Find your next great moment",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "audiowide",
    "artwork": "/templates/gymnastics/collection-2026/amethyst-arena.webp",
    "artworkAlt": "Wide cinematic purple-lit gymnastics arena with amethyst-like light facets shining over regulation uneven bars, vivid violet spotlight beams",
    "background": "#2a1d42",
    "foreground": "#f4edff",
    "accent": "#bca0e9",
    "displayFont": "Gym Orbitron",
    "sampleVenue": "Geode Exhibition Center",
    "sampleLocation": "Salt Lake City, UT",
    "sampleHost": "Amethyst Gymnastics",
    "sampleNote": "Join Amethyst Gymnastics at Geode Exhibition Center for the Amethyst Arena Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "amethyst-arena",
    "bodyStyle": "tiles"
  },
  {
    "id": "golden-hour-gym",
    "name": "Golden Hour Gym",
    "style": "Editorial",
    "description": "Golden Hour Gym pairs editorial artwork with a airy team program.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Golden Hour Gym Invitational",
    "previewKicker": "Every routine tells a story",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "playfair",
    "artwork": "/templates/gymnastics/collection-2026/golden-hour-gym.webp",
    "artworkAlt": "Candid film photograph of an adult gymnast stretching beside a beam at golden hour, honey sunlight and long window shadows on oatmeal-colored mats",
    "background": "#f6eddf",
    "foreground": "#604630",
    "accent": "#9f7039",
    "displayFont": "Gym Playfair",
    "sampleVenue": "Solstice Athletic Hall",
    "sampleLocation": "Sacramento, CA",
    "sampleHost": "Golden Gymnastics",
    "sampleNote": "Join Golden Gymnastics at Solstice Athletic Hall for the Golden Hour Gym Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "golden-hour-gym",
    "bodyStyle": "ticket"
  },
  {
    "id": "aqua-acrobat",
    "name": "Aqua Acrobat",
    "style": "Modern",
    "description": "Aqua Acrobat pairs modern artwork with a sculptural event cover.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Aqua Acrobat Invitational",
    "previewKicker": "A weekend worth cheering for",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "exo2",
    "artwork": "/templates/gymnastics/collection-2026/aqua-acrobat.webp",
    "artworkAlt": "Refined 3D sculpture of a fluid turquoise figure in a gymnastics handstand on a pale plinth, smooth abstract anatomically legible form and soft aqua backdrop",
    "background": "#e7fbf8",
    "foreground": "#235958",
    "accent": "#318d82",
    "displayFont": "Gym Space",
    "sampleVenue": "Current Recreation Hall",
    "sampleLocation": "Fort Lauderdale, FL",
    "sampleHost": "Aqua Gymnastics",
    "sampleNote": "Join Aqua Gymnastics at Current Recreation Hall for the Aqua Acrobat Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "aqua-acrobat",
    "bodyStyle": "ticket"
  },
  {
    "id": "red-clay-rotation",
    "name": "Red Clay Rotation",
    "style": "Artisan",
    "description": "Red Clay Rotation pairs artisan artwork with a layered meet journal.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Red Clay Rotation Invitational",
    "previewKicker": "A beautiful day to fly",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "barlow-condensed",
    "artwork": "/templates/gymnastics/collection-2026/red-clay-rotation.webp",
    "artworkAlt": "Claymation miniature artistic gymnastics arena with terracotta floor mats and ivory wooden rings, overhead isometric composition, handmade tactile architecture",
    "background": "#f2e2d8",
    "foreground": "#63372e",
    "accent": "#a35b42",
    "displayFont": "Gym Condensed",
    "sampleVenue": "Kiln Sports Complex",
    "sampleLocation": "Durham, NC",
    "sampleHost": "Red Gymnastics",
    "sampleNote": "Join Red Gymnastics at Kiln Sports Complex for the Red Clay Rotation Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "red-clay-rotation",
    "bodyStyle": "ticket"
  },
  {
    "id": "starfall-session",
    "name": "Starfall Session",
    "style": "Celestial",
    "description": "Starfall Session pairs celestial artwork with a bold arena poster.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Starfall Session Invitational",
    "previewKicker": "Small steps. Extraordinary moments.",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "orbitron",
    "artwork": "/templates/gymnastics/collection-2026/starfall-session.webp",
    "artworkAlt": "Imaginative night illustration of an empty gymnastics floor beneath a glass roof filled with a meteor shower, navy gold and soft starlight, elegant painterly detail",
    "background": "#182447",
    "foreground": "#f3eedf",
    "accent": "#c9b977",
    "displayFont": "Gym Orbitron",
    "sampleVenue": "Meteor Pavilion",
    "sampleLocation": "Albuquerque, NM",
    "sampleHost": "Starfall Gymnastics",
    "sampleNote": "Join Starfall Gymnastics at Meteor Pavilion for the Starfall Session Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "starfall-session",
    "bodyStyle": "ticket"
  },
  {
    "id": "daisy-daybreak",
    "name": "Daisy Daybreak",
    "style": "Seasonal",
    "description": "Daisy Daybreak pairs seasonal artwork with a framed invitation.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Daisy Daybreak Invitational",
    "previewKicker": "Bring your team spirit",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "cormorant",
    "artwork": "/templates/gymnastics/collection-2026/daisy-daybreak.webp",
    "artworkAlt": "Warm gouache illustration of fresh white daisies beside a yellow gymnastics springboard and pale green mat, cheerful spring morning, hand-painted shadows",
    "background": "#faf8df",
    "foreground": "#4a5533",
    "accent": "#8b914e",
    "displayFont": "Gym Cormorant",
    "sampleVenue": "Meadow Recreation Hall",
    "sampleLocation": "Des Moines, IA",
    "sampleHost": "Daisy Gymnastics",
    "sampleNote": "Join Daisy Gymnastics at Meadow Recreation Hall for the Daisy Daybreak Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "daisy-daybreak",
    "bodyStyle": "ticket"
  },
  {
    "id": "metro-motion",
    "name": "Metro Motion",
    "style": "Editorial",
    "description": "Metro Motion pairs editorial artwork with a asymmetric photo story.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Metro Motion Invitational",
    "previewKicker": "Find your next great moment",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "anton",
    "artwork": "/templates/gymnastics/collection-2026/metro-motion.webp",
    "artworkAlt": "Gritty yet polished editorial sports photograph of an adult male gymnast on parallel bars in an urban brick gym with tall industrial windows, slate blue tones",
    "background": "#e9ebee",
    "foreground": "#313949",
    "accent": "#506885",
    "displayFont": "Gym Anton",
    "sampleVenue": "Transit Athletics",
    "sampleLocation": "Detroit, MI",
    "sampleHost": "Metro Gymnastics",
    "sampleNote": "Join Metro Gymnastics at Transit Athletics for the Metro Motion Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "metro-motion",
    "bodyStyle": "ticket"
  },
  {
    "id": "velvet-victory",
    "name": "Velvet Victory",
    "style": "Elegant",
    "description": "Velvet Victory pairs elegant artwork with a airy team program.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Velvet Victory Invitational",
    "previewKicker": "Every routine tells a story",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "playfair",
    "artwork": "/templates/gymnastics/collection-2026/velvet-victory.webp",
    "artworkAlt": "Luxury still life of a plain gold gymnastics medal on pleated aubergine velvet with a dusty rose ribbon, dramatic diagonal warm light, no letters",
    "background": "#352535",
    "foreground": "#fff0e4",
    "accent": "#d5a389",
    "displayFont": "Gym Playfair",
    "sampleVenue": "Regency Sports Hall",
    "sampleLocation": "Richmond, VA",
    "sampleHost": "Velvet Gymnastics",
    "sampleNote": "Join Velvet Gymnastics at Regency Sports Hall for the Velvet Victory Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "velvet-victory",
    "bodyStyle": "ticket"
  },
  {
    "id": "mint-condition",
    "name": "Mint Condition",
    "style": "Minimal",
    "description": "Mint Condition pairs minimal artwork with a sculptural event cover.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Mint Condition Invitational",
    "previewKicker": "A weekend worth cheering for",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "manrope",
    "artwork": "/templates/gymnastics/collection-2026/mint-condition.webp",
    "artworkAlt": "Airy architectural photo of an immaculate mint-green gymnastics training hall, symmetrical balance beams and soft white skylights, calming spacious composition",
    "background": "#ecf9ef",
    "foreground": "#31534c",
    "accent": "#57816f",
    "displayFont": "Gym Inter",
    "sampleVenue": "Freshwater Training Hall",
    "sampleLocation": "Grand Rapids, MI",
    "sampleHost": "Mint Gymnastics",
    "sampleNote": "Join Mint Gymnastics at Freshwater Training Hall for the Mint Condition Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "mint-condition",
    "bodyStyle": "ticket"
  },
  {
    "id": "sunflower-salute",
    "name": "Sunflower Salute",
    "style": "Seasonal",
    "description": "Sunflower Salute pairs seasonal artwork with a layered meet journal.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Sunflower Salute Invitational",
    "previewKicker": "A beautiful day to fly",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "league-spartan",
    "artwork": "/templates/gymnastics/collection-2026/sunflower-salute.webp",
    "artworkAlt": "Folk-art print of a gymnast's triumphant raised-arm silhouette framed by gigantic sunflowers and a golden circle, ochre and dark olive ink on cream",
    "background": "#fbf0c9",
    "foreground": "#53442a",
    "accent": "#9f7b23",
    "displayFont": "Gym Spartan",
    "sampleVenue": "Suncrest Fieldhouse",
    "sampleLocation": "Wichita, KS",
    "sampleHost": "Sunflower Gymnastics",
    "sampleNote": "Join Sunflower Gymnastics at Suncrest Fieldhouse for the Sunflower Salute Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "sunflower-salute",
    "bodyStyle": "ticket"
  },
  {
    "id": "polar-parallel",
    "name": "Polar Parallel",
    "style": "Destination",
    "description": "Polar Parallel pairs destination artwork with a bold arena poster.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Polar Parallel Invitational",
    "previewKicker": "Small steps. Extraordinary moments.",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "space-mono",
    "artwork": "/templates/gymnastics/collection-2026/polar-parallel.webp",
    "artworkAlt": "Editorial photo of parallel bars in a frosted glass Nordic-style gym, icy blue morning and pale birch architecture, tranquil precise lines",
    "background": "#e9f2f6",
    "foreground": "#284454",
    "accent": "#567c8e",
    "displayFont": "ui-monospace",
    "sampleVenue": "Frostline Sports Hall",
    "sampleLocation": "Duluth, MN",
    "sampleHost": "Polar Gymnastics",
    "sampleNote": "Join Polar Gymnastics at Frostline Sports Hall for the Polar Parallel Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "polar-parallel",
    "bodyStyle": "ticket"
  },
  {
    "id": "sienna-scorebook",
    "name": "Sienna Scorebook",
    "style": "Heritage",
    "description": "Sienna Scorebook pairs heritage artwork with a framed invitation.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Sienna Scorebook Invitational",
    "previewKicker": "Bring your team spirit",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "playfair",
    "artwork": "/templates/gymnastics/collection-2026/sienna-scorebook.webp",
    "artworkAlt": "Antique sports still life with closed unlettered leather scorebook, bronze whistle and white gymnastics hand guards on a sienna wooden desk, nostalgic natural light",
    "background": "#f1e5d2",
    "foreground": "#623e2c",
    "accent": "#8f6044",
    "displayFont": "Gym Playfair",
    "sampleVenue": "Ledger Athletics Hall",
    "sampleLocation": "Lancaster, PA",
    "sampleHost": "Sienna Gymnastics",
    "sampleNote": "Join Sienna Gymnastics at Ledger Athletics Hall for the Sienna Scorebook Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "sienna-scorebook",
    "bodyStyle": "club"
  },
  {
    "id": "bubblegum-bounce",
    "name": "Bubblegum Bounce",
    "style": "Playful",
    "description": "Bubblegum Bounce pairs playful artwork with a asymmetric photo story.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Bubblegum Bounce Invitational",
    "previewKicker": "Find your next great moment",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "poppins",
    "artwork": "/templates/gymnastics/collection-2026/bubblegum-bounce.webp",
    "artworkAlt": "Whimsical glossy 3D pink gymnastics trampoline with floating pastel spheres and lilac stairs, bubblegum studio set, joyful polished toy-scale sculpture",
    "background": "#ffeef7",
    "foreground": "#6d3c64",
    "accent": "#b3579d",
    "displayFont": "Gym Rounded",
    "sampleVenue": "Bonbon Recreation Hall",
    "sampleLocation": "Omaha, NE",
    "sampleHost": "Bubblegum Gymnastics",
    "sampleNote": "Join Bubblegum Gymnastics at Bonbon Recreation Hall for the Bubblegum Bounce Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "bubblegum-bounce",
    "bodyStyle": "club"
  },
  {
    "id": "evergreen-elevation",
    "name": "Evergreen Elevation",
    "style": "Botanical",
    "description": "Evergreen Elevation pairs botanical artwork with a airy team program.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Evergreen Elevation Invitational",
    "previewKicker": "Every routine tells a story",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "oswald",
    "artwork": "/templates/gymnastics/collection-2026/evergreen-elevation.webp",
    "artworkAlt": "Painterly illustration of a gymnastics beam framed by tall evergreen boughs and distant mountains seen through gym windows, deep forest and misty cream",
    "background": "#e9ede4",
    "foreground": "#324438",
    "accent": "#627950",
    "displayFont": "Gym Condensed",
    "sampleVenue": "Evergreen Athletic Lodge",
    "sampleLocation": "Spokane, WA",
    "sampleHost": "Evergreen Gymnastics",
    "sampleNote": "Join Evergreen Gymnastics at Evergreen Athletic Lodge for the Evergreen Elevation Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "evergreen-elevation",
    "bodyStyle": "club"
  },
  {
    "id": "cobalt-circuit",
    "name": "Cobalt Circuit",
    "style": "Technical",
    "description": "Cobalt Circuit pairs technical artwork with a sculptural event cover.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Cobalt Circuit Invitational",
    "previewKicker": "A weekend worth cheering for",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "ibm-plex-mono",
    "artwork": "/templates/gymnastics/collection-2026/cobalt-circuit.webp",
    "artworkAlt": "Axonometric blueprint-like 3D illustration of a gymnastics rotation circuit with beam bars vault and floor, bright cobalt structures on white ground, precise geometry, no text",
    "background": "#e7eefc",
    "foreground": "#203e72",
    "accent": "#416eb7",
    "displayFont": "ui-monospace",
    "sampleVenue": "Circuit Training Center",
    "sampleLocation": "Rochester, NY",
    "sampleHost": "Cobalt Gymnastics",
    "sampleNote": "Join Cobalt Gymnastics at Circuit Training Center for the Cobalt Circuit Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "cobalt-circuit",
    "bodyStyle": "club"
  },
  {
    "id": "ruby-ribbonline",
    "name": "Ruby Ribbonline",
    "style": "Elegant",
    "description": "Ruby Ribbonline pairs elegant artwork with a layered meet journal.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Ruby Ribbonline Invitational",
    "previewKicker": "A beautiful day to fly",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "cormorant",
    "artwork": "/templates/gymnastics/collection-2026/ruby-ribbonline.webp",
    "artworkAlt": "Fine art still life of an unmarked ruby-red award rosette with folded cream satin on polished dark cherry wood, graceful swirling composition",
    "background": "#f6e8e8",
    "foreground": "#682f3d",
    "accent": "#9f4d62",
    "displayFont": "Gym Cormorant",
    "sampleVenue": "Garnet Hall",
    "sampleLocation": "Louisville, KY",
    "sampleHost": "Ruby Gymnastics",
    "sampleNote": "Join Ruby Gymnastics at Garnet Hall for the Ruby Ribbonline Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "ruby-ribbonline",
    "bodyStyle": "club"
  },
  {
    "id": "sandstone-spring",
    "name": "Sandstone Spring",
    "style": "Destination",
    "description": "Sandstone Spring pairs destination artwork with a bold arena poster.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Sandstone Spring Invitational",
    "previewKicker": "Small steps. Extraordinary moments.",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "montserrat",
    "artwork": "/templates/gymnastics/collection-2026/sandstone-spring.webp",
    "artworkAlt": "Travel-editorial photograph of a modern sandstone gymnastics hall with a beam and warm limestone arches, daylight and sand-colored textures",
    "background": "#f0e8d8",
    "foreground": "#514a37",
    "accent": "#89815b",
    "displayFont": "Gym Montserrat",
    "sampleVenue": "Canyon Sports Pavilion",
    "sampleLocation": "St. George, UT",
    "sampleHost": "Sandstone Gymnastics",
    "sampleNote": "Join Sandstone Gymnastics at Canyon Sports Pavilion for the Sandstone Spring Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "sandstone-spring",
    "bodyStyle": "club"
  },
  {
    "id": "lavender-locker",
    "name": "Lavender Locker",
    "style": "Editorial",
    "description": "Lavender Locker pairs editorial artwork with a framed invitation.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Lavender Locker Invitational",
    "previewKicker": "Bring your team spirit",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "manrope",
    "artwork": "/templates/gymnastics/collection-2026/lavender-locker.webp",
    "artworkAlt": "Fashion-editorial still life of lavender lockers, a neatly hung unbranded competition leotard and white gym bag, quiet pre-meet preparation, realistic photography",
    "background": "#f0ebf7",
    "foreground": "#4e4562",
    "accent": "#83709c",
    "displayFont": "Gym Inter",
    "sampleVenue": "Heather Athletic Center",
    "sampleLocation": "Knoxville, TN",
    "sampleHost": "Lavender Gymnastics",
    "sampleNote": "Join Lavender Gymnastics at Heather Athletic Center for the Lavender Locker Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "lavender-locker",
    "bodyStyle": "club"
  },
  {
    "id": "solar-somersault",
    "name": "Solar Somersault",
    "style": "Modern",
    "description": "Solar Somersault pairs modern artwork with a asymmetric photo story.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Solar Somersault Invitational",
    "previewKicker": "Find your next great moment",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "kanit",
    "artwork": "/templates/gymnastics/collection-2026/solar-somersault.webp",
    "artworkAlt": "Bold screen-print illustration of an adult gymnast in a tucked somersault silhouetted across a giant orange sun disc, cream sky and angular ochre floor geometry",
    "background": "#fbe8c9",
    "foreground": "#664226",
    "accent": "#b16c28",
    "displayFont": "Gym Anton",
    "sampleVenue": "Helios Events Center",
    "sampleLocation": "El Paso, TX",
    "sampleHost": "Solar Gymnastics",
    "sampleNote": "Join Solar Gymnastics at Helios Events Center for the Solar Somersault Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "solar-somersault",
    "bodyStyle": "club"
  },
  {
    "id": "blackberry-beam",
    "name": "Blackberry Beam",
    "style": "Artisan",
    "description": "Blackberry Beam pairs artisan artwork with a airy team program.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Blackberry Beam Invitational",
    "previewKicker": "Every routine tells a story",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "space-mono",
    "artwork": "/templates/gymnastics/collection-2026/blackberry-beam.webp",
    "artworkAlt": "Moody plum-toned charcoal and pastel drawing of a balance beam and chalky footprint textures, hand-drawn crosshatching, soft blackberry color field",
    "background": "#eee4ef",
    "foreground": "#553b59",
    "accent": "#89628d",
    "displayFont": "ui-monospace",
    "sampleVenue": "Bramble Sports Hall",
    "sampleLocation": "Boise, ID",
    "sampleHost": "Blackberry Gymnastics",
    "sampleNote": "Join Blackberry Gymnastics at Bramble Sports Hall for the Blackberry Beam Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "blackberry-beam",
    "bodyStyle": "club"
  },
  {
    "id": "skyline-sendoff",
    "name": "Skyline Sendoff",
    "style": "Electric",
    "description": "Skyline Sendoff pairs electric artwork with a sculptural event cover.",
    "group": "current",
    "layoutFamily": "editorial",
    "thumbnailMode": "rendered-card",
    "previewTitle": "Skyline Sendoff Invitational",
    "previewKicker": "A weekend worth cheering for",
    "previewClassName": "",
    "previewAccentClassName": "",
    "titleTypographyId": "league-spartan",
    "artwork": "/templates/gymnastics/collection-2026/skyline-sendoff.webp",
    "artworkAlt": "Cinematic wide photograph of a gymnastics floor in a rooftop training hall at blue hour, distant illuminated city skyline beyond huge windows, cool teal and silver",
    "background": "#152c39",
    "foreground": "#eaf5f5",
    "accent": "#83becb",
    "displayFont": "Gym Spartan",
    "sampleVenue": "Horizon Arena",
    "sampleLocation": "Chicago, IL",
    "sampleHost": "Skyline Gymnastics",
    "sampleNote": "Join Skyline Gymnastics at Horizon Arena for the Skyline Sendoff Invitational. Session details, team updates, and a full day of gymnastics await.",
    "composition": "skyline-sendoff",
    "bodyStyle": "club"
  }
];

export const isGymMeetTemplateId = (value: unknown): value is GymMeetTemplateId =>
  typeof value === "string" && GYM_MEET_TEMPLATE_LIBRARY.some((template) => template.id === value);

export const getGymMeetTemplateMeta = (value: unknown): GymMeetPageTemplateMeta =>
  GYM_MEET_TEMPLATE_LIBRARY.find((template) => template.id === value) || GYM_MEET_TEMPLATE_LIBRARY[0];

/** Retired IDs resolve to the new collection without changing saved event content. */
export const resolveGymMeetTemplateId = (data: { pageTemplateId?: string } | null | undefined): GymMeetTemplateId =>
  isGymMeetTemplateId(data?.pageTemplateId) ? data.pageTemplateId : DEFAULT_GYM_MEET_TEMPLATE_ID;
