import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const repoRoot = process.cwd();

const readSource = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), "utf8");

test("admin landing preview is gated, noindexed, and luxury-concierge led", () => {
  const source = readSource("src/app/admin/landing-preview/page.tsx");

  assert.match(source, /requireAdminSession/);
  assert.match(source, /robots:\s*\{\s*index:\s*false,\s*follow:\s*false\s*\}/);
  assert.match(source, /Noindex route\. Production \/landing is unchanged\./);
  assert.match(source, /Hosting upgrade/);
  assert.match(source, /Stop sharing fuzzy screenshots and scattered bullet lists/);
  assert.match(source, /LuxuryNav/);
  assert.match(source, /sticky top-0 z-30/);
  assert.match(source, /The Hub/);
  assert.match(source, /Snap & Convert/);
  assert.match(source, /Showcases/);
  assert.match(source, /Bespoke Guides/);
  assert.match(source, /Process/);
  assert.match(source, /FAQ/);
  assert.match(source, /Inquiries/);
  assert.match(source, /href: "#hub"/);
  assert.match(source, /href: "#snap"/);
  assert.match(source, /href: "#showcase"/);
  assert.match(source, /href: "#guides"/);
  assert.match(source, /href: "#process"/);
  assert.match(source, /href: "#faq"/);
  assert.match(source, /href: "#inquiries"/);
  assert.match(source, /mobileQuickLinks/);
  assert.match(source, /Snap AI/);
  assert.match(source, /<main id="hub"/);
  assert.match(source, /<section id="snap" className="scroll-mt-24/);
  assert.match(source, /id="guides"[\s\S]*?scroll-mt-24/);
  assert.match(source, /<section id="process" className="scroll-mt-24/);
  assert.match(source, /<section id="faq" className="scroll-mt-24/);
  assert.match(source, /<section id="inquiries" className="scroll-mt-24/);
  assert.match(source, /Turn any invite, flyer, PDF, or idea/);
  assert.match(source, /into a live event page/);
  assert.match(source, /Envitefy creates stunning invitations/);
  assert.match(source, /RSVP flows, maps, calendar saves, registries/);
  assert.match(source, /Guests need no app/);
  assert.match(source, /Start Planning with AI/);
  assert.match(source, /View Live Examples/);
  assert.match(source, /Hosting\? Upload a flyer/);
  assert.match(source, /Invited\? Save birthday/);
  assert.match(source, /ConciergeWorkspace/);
  assert.match(source, /Envitefy premium concierge/);
  assert.match(source, /Turn messy source material into one polished guest page/);
  assert.match(source, /AI build status/);
  assert.match(source, /Stage 4 \/ 4/);
  assert.match(source, /Map and calendar actions wired/);
  assert.match(source, /PhoneGuestPreview/);
  assert.match(source, /Live preview/);
  assert.match(source, /RSVP recorded/);
  assert.match(source, /RSVP attending/);
  assert.match(source, /No account required/);
  assert.match(source, /Calendar saved/);
  assert.match(source, /Directions ready/);
  assert.match(source, /Guest actions/);
  assert.match(source, /Track RSVPs/);
  assert.match(source, /Open maps fast/);
  assert.match(source, /Share gift links/);
  assert.match(source, /Update once/);
  assert.match(source, /HostLedgerPreview/);
  assert.match(source, /Host control/);
  assert.match(source, /Recent RSVP ledger/);
  assert.match(source, /Host assurance/);
  assert.match(source, /Private, editable, and calm/);
  assert.match(source, /Before Envitefy/);
  assert.match(source, /After Envitefy/);
  assert.match(source, /Live examples/);
  assert.match(source, /Live cards guests want to open/);
  assert.match(source, /tone="luxury"/);
  assert.match(source, /Bespoke guides/);
  assert.match(source, /Helpful playbooks for hosts/);
  assert.match(source, /Use cases/);
  assert.match(source, /Upload paths/);
  assert.match(source, /UploadDropzonePreview/);
  assert.match(source, /Drop in a flyer, PDF, screenshot, or paper invite photo/);
  assert.match(source, /HEIC/);
  assert.match(source, /Host path/);
  assert.match(source, /Guest path/);
  assert.match(source, /\/studio\/custom-invite\.webp/);
  assert.equal((source.match(/use-case-wedding\.webp/g) || []).length, 1);
  assert.match(source, /Add details, review the draft, share one beautiful link/);
  assert.match(source, /Event pages should answer questions/);
  assert.match(source, /Are shared event pages private/);
  assert.match(source, /unindexed share links/);
  assert.match(source, /Create your event/);
  assert.match(source, /Create Your Event/);
  assert.match(source, /Create an Invitation/);
  assert.match(source, /MarketingFooter/);
  assert.match(source, /Conversion paths/);
  assert.match(source, /Host playbooks/);
  assert.match(source, /No-App Guest Sharing/);
  assert.match(source, /Premium event pages, practical guest operations/);
  assert.match(source, /#c5a880/);
  assert.match(source, /#dfc39a/);
  assert.match(source, /#a88b58/);
  assert.match(source, /bg-slate-950/);
  assert.match(source, /LandingLiveCardShowcase/);

  assert.doesNotMatch(source, /One polished event link from idea to RSVP/);
  assert.doesNotMatch(source, /A more professional landing page: light, direct, and product-led/);
  assert.doesNotMatch(source, /Intent chooser/);
  assert.doesNotMatch(source, /product taxonomy/i);
  assert.doesNotMatch(source, /Guest action architecture/);
  assert.doesNotMatch(source, /Launch Concierge/);
  assert.doesNotMatch(source, /Luxury invitation software should remove questions/);
  assert.doesNotMatch(source, /warm surface, sage action, lavender accents, charcoal text/);
  assert.doesNotMatch(source, /Try Snap Upload/);
  assert.doesNotMatch(source, /Start with Gymnastics/);
  assert.doesNotMatch(source, /ENVITEFY \/ STUDIO \/ SNAP \/ MEET/);
  assert.doesNotMatch(source, /Envitefy Studio/);
  assert.doesNotMatch(source, /bg-\[#2a1712\]/);
  assert.doesNotMatch(source, /blur-3xl/);
});
