// @ts-nocheck
"use client";

import React from "react";

const config = {
  slug: "soccer",
  displayName: "Soccer Match",
  category: "sport_soccer",
  categoryLabel: "Soccer",
  defaultHero: "/templates/hero-images/soccer-hero.jpeg",
  detailFields: [
    { key: "opponent", label: "Opponent", placeholder: "vs River City FC" },
    { key: "league", label: "League / Division", placeholder: "U12 Premier" },
    {
      key: "field",
      label: "Field / Pitch",
      placeholder: "Field 3, East Complex",
    },
    {
      key: "kit",
      label: "Uniform Colors",
      placeholder: "Home: Navy/White, Away: White/Navy",
    },
    {
      key: "warmup",
      label: "Warm-up & Arrival",
      placeholder: "Arrive 45 min early; warm-up 2:15 PM",
    },
    {
      key: "lineup",
      label: "Lineup / Formation",
      placeholder: "4-3-3; who starts where",
    },
  ],
  themes: [
    {
      id: "pitch_royal",
      name: "Pitch Royal",
      bg: "bg-gradient-to-br from-blue-900 via-blue-800 to-slate-100",
      text: "text-white",
      accent: "text-sky-200",
      preview: "bg-gradient-to-r from-blue-900 via-blue-800 to-slate-100",
    },
    {
      id: "striker_red",
      name: "Striker Red",
      bg: "bg-gradient-to-br from-red-900 via-red-800 to-rose-300",
      text: "text-white",
      accent: "text-rose-100",
      preview: "bg-gradient-to-r from-red-900 via-red-800 to-rose-300",
    },
    {
      id: "classic_kit",
      name: "Classic Kit",
      bg: "bg-gradient-to-br from-slate-950 via-slate-700 to-slate-300",
      text: "text-white",
      accent: "text-slate-100",
      preview: "bg-gradient-to-r from-slate-950 via-slate-700 to-slate-300",
    },
    {
      id: "field_green",
      name: "Field Green",
      bg: "bg-gradient-to-br from-emerald-900 via-emerald-700 to-emerald-500",
      text: "text-white",
      accent: "text-emerald-100",
      preview:
        "bg-gradient-to-r from-emerald-900 via-emerald-700 to-emerald-500",
    },
    {
      id: "navy_united",
      name: "Navy United",
      bg: "bg-gradient-to-br from-blue-950 via-blue-900 to-slate-200",
      text: "text-white",
      accent: "text-slate-100",
      preview: "bg-gradient-to-r from-blue-950 via-blue-900 to-slate-200",
    },
    {
      id: "attack_red",
      name: "Attack Red",
      bg: "bg-gradient-to-br from-slate-950 via-red-900 to-red-700",
      text: "text-white",
      accent: "text-red-100",
      preview: "bg-gradient-to-r from-slate-950 via-red-900 to-red-700",
    },
    {
      id: "midnight_fc",
      name: "Midnight FC",
      bg: "bg-gradient-to-br from-slate-950 via-blue-900 to-blue-700",
      text: "text-white",
      accent: "text-blue-200",
      preview: "bg-gradient-to-r from-slate-950 via-blue-900 to-blue-700",
    },
    {
      id: "crimson_club",
      name: "Crimson Club",
      bg: "bg-gradient-to-br from-rose-900 via-rose-800 to-rose-400",
      text: "text-white",
      accent: "text-rose-100",
      preview: "bg-gradient-to-r from-rose-900 via-rose-800 to-rose-400",
    },
    {
      id: "golden_cleats",
      name: "Golden Cleats",
      bg: "bg-gradient-to-br from-slate-950 via-black to-amber-500",
      text: "text-white",
      accent: "text-amber-200",
      preview: "bg-gradient-to-r from-slate-950 via-black to-amber-500",
    },
    {
      id: "championship_white",
      name: "Championship White",
      bg: "bg-gradient-to-br from-white via-amber-50 to-amber-200",
      text: "text-slate-900",
      accent: "text-amber-700",
      preview: "bg-gradient-to-r from-white via-amber-50 to-amber-200",
    },
    {
      id: "aqua_fc",
      name: "Aqua FC",
      bg: "bg-gradient-to-br from-slate-950 via-teal-900 to-teal-600",
      text: "text-white",
      accent: "text-teal-100",
      preview: "bg-gradient-to-r from-slate-950 via-teal-900 to-teal-600",
    },
    {
      id: "sunset_strikers",
      name: "Sunset Strikers",
      bg: "bg-gradient-to-br from-slate-950 via-orange-800 to-amber-500",
      text: "text-white",
      accent: "text-amber-100",
      preview: "bg-gradient-to-r from-slate-950 via-orange-800 to-amber-500",
    },
    {
      id: "violet_victory",
      name: "Violet Victory",
      bg: "bg-gradient-to-br from-violet-900 via-purple-800 to-slate-100",
      text: "text-white",
      accent: "text-violet-100",
      preview: "bg-gradient-to-r from-violet-900 via-purple-800 to-slate-100",
    },
    {
      id: "elite_navy",
      name: "Elite Navy",
      bg: "bg-gradient-to-br from-blue-950 via-blue-900 to-amber-500",
      text: "text-white",
      accent: "text-amber-200",
      preview: "bg-gradient-to-r from-blue-950 via-blue-900 to-amber-500",
    },
    {
      id: "skyline_fc",
      name: "Skyline FC",
      bg: "bg-gradient-to-br from-sky-500 via-sky-400 to-blue-900",
      text: "text-white",
      accent: "text-sky-100",
      preview: "bg-gradient-to-r from-sky-500 via-sky-400 to-blue-900",
    },
    {
      id: "goalkeeper_yellow",
      name: "Goalkeeper Yellow",
      bg: "bg-gradient-to-br from-slate-950 via-amber-700 to-yellow-500",
      text: "text-white",
      accent: "text-amber-100",
      preview: "bg-gradient-to-r from-slate-950 via-amber-700 to-yellow-500",
    },
    {
      id: "columbia_crest",
      name: "Columbia Crest",
      bg: "bg-gradient-to-br from-sky-400 via-sky-200 to-white",
      text: "text-slate-900",
      accent: "text-sky-700",
      preview: "bg-gradient-to-r from-sky-400 via-sky-200 to-white",
    },
    {
      id: "forest_fc",
      name: "Forest FC",
      bg: "bg-gradient-to-br from-emerald-900 via-green-800 to-amber-500",
      text: "text-white",
      accent: "text-amber-200",
      preview: "bg-gradient-to-r from-emerald-900 via-green-800 to-amber-500",
    },
    {
      id: "patriot_fc",
      name: "Patriot FC",
      bg: "bg-gradient-to-br from-red-900 via-rose-700 to-blue-900",
      text: "text-white",
      accent: "text-rose-100",
      preview: "bg-gradient-to-r from-red-900 via-rose-700 to-blue-900",
    },
    {
      id: "silver_maroon",
      name: "Silver Maroon",
      bg: "bg-gradient-to-br from-rose-900 via-rose-700 to-slate-300",
      text: "text-white",
      accent: "text-slate-100",
      preview: "bg-gradient-to-r from-rose-900 via-rose-700 to-slate-300",
    },
    {
      id: "derby_black",
      name: "Derby Black",
      bg: "bg-gradient-to-br from-slate-950 via-black to-red-700",
      text: "text-white",
      accent: "text-rose-100",
      preview: "bg-gradient-to-r from-slate-950 via-black to-red-700",
    },
    {
      id: "coastal_fc",
      name: "Coastal FC",
      bg: "bg-gradient-to-br from-white via-teal-100 to-teal-500",
      text: "text-slate-900",
      accent: "text-teal-700",
      preview: "bg-gradient-to-r from-white via-teal-100 to-teal-500",
    },
    {
      id: "steel_blue",
      name: "Steel Blue",
      bg: "bg-gradient-to-br from-slate-900 via-blue-700 to-slate-300",
      text: "text-white",
      accent: "text-slate-100",
      preview: "bg-gradient-to-r from-slate-900 via-blue-700 to-slate-300",
    },
    {
      id: "neon_striker",
      name: "Neon Striker",
      bg: "bg-gradient-to-br from-slate-950 via-black to-lime-500",
      text: "text-white",
      accent: "text-lime-200",
      preview: "bg-gradient-to-r from-slate-950 via-black to-lime-500",
    },
  ],
};

export { config };
