#!/usr/bin/env python3
"""Publish holiday catalog metadata without changing legacy IDs or saved artwork."""
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
payload = json.loads(subprocess.run([
    "bun", "-e",
    'import {HOLIDAY_COLLECTIONS} from "./src/lib/holiday-collections"; '
    'import {SIGNUP_DESIGN_PALETTES} from "./src/lib/signup-designs"; '
    'console.log(JSON.stringify({collections:HOLIDAY_COLLECTIONS,palettes:SIGNUP_DESIGN_PALETTES}));',
], cwd=ROOT, check=True, capture_output=True, text=True).stdout)
manifest_path = ROOT / "public/templates/signup/manifest.json"
manifest = json.loads(manifest_path.read_text())
for collection in payload["collections"]:
    entries = []
    for design in collection["designs"]:
        image = f'/templates/signup/holidays/{collection["id"]}/{design["slug"]}.webp'
        if "--allow-in-progress" not in sys.argv:
            assert (ROOT / "public" / image.lstrip("/")).is_file(), image
        entries.append(dict(name=f'{collection["name"]} · {design["name"]}', tier="free", path=image,
                            artworkPath=image, occasion=collection["id"], audience="Community & Family",
                            description=f'{design["name"]}: a {collection["name"]} design for your own event details and signup sections.',
                            keywords=collection["aliases"]))
    existing = manifest.get(collection["name"], [])
    assert all(e["path"].startswith("/templates/signup/holidays/") for e in existing), "Never replace unrelated templates"
    manifest[collection["name"]] = entries
serialized = json.dumps(manifest, indent=2, ensure_ascii=False)
manifest_path.write_text(serialized + "\n")
(ROOT / "src/assets/signup-templates.ts").write_text(
    '// Artwork paths are installed by scripts/process-signup-artwork.py and scripts/publish-holiday-templates.py.\n'
    '// Canonical paths preserve template IDs and previously saved artwork.\n'
    'import type { HolidayCollectionId } from "@/lib/holiday-collections";\n'
    'export type SignupTemplateItem = { name: string; tier: "free" | "premium"; path: string; artworkPath?: string; description?: string; keywords?: string; audience?: string; occasion?: HolidayCollectionId };\n'
    'export type SignupTemplateManifest = Record<string, SignupTemplateItem[]>;\n'
    'export const SIGNUP_TEMPLATES: SignupTemplateManifest = ' + serialized + ';\n')
css = ['/* Generated by scripts/publish-holiday-templates.py; shared by the editor and public page. */']
for name, palette in payload["palettes"].items():
    css.extend([f'.holiday-bg-{name} {{ background-color: {palette["page"]}; }}',
                f'.holiday-ink-{name} {{ color: {palette["ink"]}; }}',
                f'.holiday-accent-{name} {{ color: {palette["accent"]}; }}'])
(ROOT / "src/styles").mkdir(exist_ok=True)
(ROOT / "src/styles/holiday-palettes.css").write_text("\n".join(css) + "\n")
print(f'Published {len(payload["collections"])} holiday collections, 10 designs each')
