"use client";

import {
  Baby,
  Bus,
  Cake,
  CalendarHeart,
  Heart,
  Home,
  WandSparkles,
  Wine,
} from "lucide-react";
import type { StudioCategoryTileDefinition } from "../studio-workspace-types";

export const STUDIO_CATEGORY_TILES: StudioCategoryTileDefinition[] = [
  {
    name: "Birthday",
    icon: Cake,
    description: "Curated themes for milestone dinners, birthday parties, and polished celebrations.",
    badge: "Party",
    imagePath:
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?q=80&w=2072&auto=format&fit=crop",
    themeColor: "#8F6FE8",
    sizeVariant: "wide",
    overlayStrength: "light",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Wedding",
    icon: Heart,
    description: "Timeless elegance for save-the-dates, ceremonies, receptions, and wedding weekends.",
    badge: "Featured",
    imagePath:
      "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=2070&auto=format&fit=crop",
    themeColor: "#7C5DD8",
    sizeVariant: "feature",
    overlayStrength: "medium",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Field Trip/Day",
    icon: Bus,
    description: "School outings, museum visits, class adventures, and daytime group events.",
    badge: "School",
    imagePath:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=2022&auto=format&fit=crop",
    themeColor: "#7F67D3",
    sizeVariant: "standard",
    overlayStrength: "light",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Bridal Shower",
    icon: Wine,
    description: "Refined brunches, floral gatherings, and pre-wedding celebrations with soft romance.",
    badge: "Bridal",
    imagePath:
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=2069&auto=format&fit=crop",
    themeColor: "#A06BD9",
    sizeVariant: "horizontal",
    overlayStrength: "light",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Baby Shower",
    icon: Baby,
    description: "Soft, elevated baby celebrations with gifting tables, florals, and welcoming details.",
    badge: "Baby",
    imagePath:
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?q=80&w=2070&auto=format&fit=crop",
    themeColor: "#9B7BD9",
    sizeVariant: "horizontal",
    overlayStrength: "light",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Anniversary",
    icon: CalendarHeart,
    description: "Romantic dinners, candlelit toasts, and milestone celebrations with an editorial feel.",
    badge: "Milestone",
    imagePath:
      "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?q=80&w=2070&auto=format&fit=crop",
    themeColor: "#8E6FD4",
    sizeVariant: "standard",
    overlayStrength: "medium",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Housewarming",
    icon: Home,
    description: "Warm modern home invites for open houses, move-in parties, and casual hosting.",
    badge: "Home",
    imagePath:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=2073&auto=format&fit=crop",
    themeColor: "#7D77C5",
    sizeVariant: "wide",
    overlayStrength: "light",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Custom Invite",
    icon: WandSparkles,
    description: "Create a one-of-a-kind invitation with a premium flexible canvas for any occasion.",
    badge: "Create your own",
    imagePath:
      "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=2069&auto=format&fit=crop",
    themeColor: "#8B5CF6",
    sizeVariant: "wide",
    overlayStrength: "dark",
    textTone: "light",
    surfaceVariant: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
];
