"use client";

import {
  Baby,
  Bus,
  Cake,
  CalendarHeart,
  Heart,
  Home,
  Trophy,
  WandSparkles,
  Wine,
} from "lucide-react";
import type { StudioCategoryTileDefinition } from "../studio-workspace-types";

export const STUDIO_CATEGORY_TILES: StudioCategoryTileDefinition[] = [
  {
    name: "Birthday",
    icon: Cake,
    description: "Celebration Moments",
    badge: "Party",
    imagePath: "/studio/birthday.webp",
    themeColor: "#8F6FE8",
    sizeVariant: "wide",
    overlayStrength: "light",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Game Day",
    icon: Trophy,
    description: "Team Spirit Events",
    badge: "Sports",
    imagePath: "/studio/game-day.webp",
    themeColor: "#2563EB",
    sizeVariant: "standard",
    overlayStrength: "medium",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Wedding",
    icon: Heart,
    description: "Elegant Wedding Weekends",
    badge: "Featured",
    imagePath: "/studio/wedding.webp",
    themeColor: "#7C5DD8",
    sizeVariant: "feature",
    overlayStrength: "medium",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Bridal Shower",
    icon: Wine,
    description: "Elegant Shower Gatherings",
    badge: "Bridal",
    imagePath: "/studio/bridal-shower.webp",
    themeColor: "#A06BD9",
    sizeVariant: "horizontal",
    overlayStrength: "light",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Baby Shower",
    icon: Baby,
    description: "Welcoming Baby Joy",
    badge: "Baby",
    imagePath: "/studio/baby-shower.webp",
    themeColor: "#9B7BD9",
    sizeVariant: "standard",
    overlayStrength: "light",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Field Trip/Day",
    icon: Bus,
    description: "Learning Adventures",
    badge: "School",
    imagePath: "/studio/field-trip-day.webp",
    themeColor: "#7F67D3",
    sizeVariant: "standard",
    overlayStrength: "light",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Anniversary",
    icon: CalendarHeart,
    description: "Romantic Celebrations",
    badge: "Milestone",
    imagePath: "/studio/anniversary.webp",
    themeColor: "#8E6FD4",
    sizeVariant: "standard",
    overlayStrength: "medium",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Housewarming",
    icon: Home,
    description: "New Home Gatherings",
    badge: "Home",
    imagePath: "/studio/housewarming.webp",
    themeColor: "#7D77C5",
    sizeVariant: "standard",
    overlayStrength: "light",
    textTone: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
  {
    name: "Custom Invite",
    icon: WandSparkles,
    description: "Any Occasion Design",
    badge: "Create your own",
    imagePath: "/studio/custom-invite.webp",
    themeColor: "#8B5CF6",
    sizeVariant: "standard",
    overlayStrength: "dark",
    textTone: "light",
    surfaceVariant: "dark",
    imagePositionClassName: "object-center",
    selectedLabel: "Currently selected",
  },
];
