// Auto-generated by scripts/generate-signup-templates-openrouter.mjs
export type SignupTemplateItem = { name: string; tier: 'free'|'premium'; path: string };
export type SignupTemplateManifest = Record<string, SignupTemplateItem[]>;
export const SIGNUP_TEMPLATES: SignupTemplateManifest = 
{
  "Fall & Seasonal": [
    {
      "name": "Apple Picking",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/apple-picking.png"
    },
    {
      "name": "Fall Scene",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/fall-scene.png"
    },
    {
      "name": "Fall Fun 2",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-fun-2.png"
    },
    {
      "name": "Harvest Table",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/harvest-table.png"
    },
    {
      "name": "Pumpkin Patch",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/pumpkin-patch.png"
    },
    {
      "name": "Fall Forest",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-forest.png"
    },
    {
      "name": "Fall Food Drive",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-food-drive.png"
    },
    {
      "name": "Fall Gathering",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/fall-gathering.png"
    },
    {
      "name": "Corn Maze",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/corn-maze.png"
    },
    {
      "name": "Autumn Blessings",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/autumn-blessings.png"
    },
    {
      "name": "Thanksgiving Feast",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/thanksgiving-feast.png"
    },
    {
      "name": "Friendsgiving",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/friendsgiving.png"
    },
    {
      "name": "Fall Food",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-food.png"
    },
    {
      "name": "Fall Leaves",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-leaves.png"
    },
    {
      "name": "Fall Y’all",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/fall-y-all.png"
    },
    {
      "name": "Fall Festival",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-festival.png"
    },
    {
      "name": "Fall Pumpkins",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/fall-pumpkins.png"
    }
  ],
  "Winter & Holidays": [
    {
      "name": "Winter Cabin",
      "tier": "free",
      "path": "/templates/signup/winter-and-holidays/winter-cabin.png"
    },
    {
      "name": "Santa’s Workshop",
      "tier": "premium",
      "path": "/templates/signup/winter-and-holidays/santa-s-workshop.png"
    },
    {
      "name": "Ugly Sweater Party",
      "tier": "free",
      "path": "/templates/signup/winter-and-holidays/ugly-sweater-party.png"
    },
    {
      "name": "Gingerbread Fun",
      "tier": "premium",
      "path": "/templates/signup/winter-and-holidays/gingerbread-fun.png"
    },
    {
      "name": "Holiday Lights",
      "tier": "premium",
      "path": "/templates/signup/winter-and-holidays/holiday-lights.png"
    },
    {
      "name": "Winter Wonderland",
      "tier": "free",
      "path": "/templates/signup/winter-and-holidays/winter-wonderland.png"
    },
    {
      "name": "Christmas Cookies",
      "tier": "free",
      "path": "/templates/signup/winter-and-holidays/christmas-cookies.png"
    },
    {
      "name": "New Year’s Eve",
      "tier": "premium",
      "path": "/templates/signup/winter-and-holidays/new-year-s-eve.png"
    },
    {
      "name": "Christmas Tree Farm",
      "tier": "premium",
      "path": "/templates/signup/winter-and-holidays/christmas-tree-farm.png"
    },
    {
      "name": "Holiday Giving",
      "tier": "free",
      "path": "/templates/signup/winter-and-holidays/holiday-giving.png"
    },
    {
      "name": "Christmas Village",
      "tier": "premium",
      "path": "/templates/signup/winter-and-holidays/christmas-village.png"
    },
    {
      "name": "Hanukkah Celebration",
      "tier": "premium",
      "path": "/templates/signup/winter-and-holidays/hanukkah-celebration.png"
    },
    {
      "name": "Snow Day",
      "tier": "free",
      "path": "/templates/signup/winter-and-holidays/snow-day.png"
    },
    {
      "name": "Snowflakes",
      "tier": "free",
      "path": "/templates/signup/winter-and-holidays/snowflakes.png"
    },
    {
      "name": "Merry Christmas",
      "tier": "free",
      "path": "/templates/signup/winter-and-holidays/merry-christmas.png"
    }
  ],
  "Spring": [
    {
      "name": "Spring Hike",
      "tier": "free",
      "path": "/templates/signup/spring/spring-hike.png"
    },
    {
      "name": "Easter Bunnies",
      "tier": "premium",
      "path": "/templates/signup/spring/easter-bunnies.png"
    },
    {
      "name": "Mother’s Day",
      "tier": "free",
      "path": "/templates/signup/spring/mother-s-day.png"
    },
    {
      "name": "Spring Flowers",
      "tier": "free",
      "path": "/templates/signup/spring/spring-flowers.png"
    },
    {
      "name": "Graduation Caps",
      "tier": "free",
      "path": "/templates/signup/spring/graduation-caps.png"
    },
    {
      "name": "Teacher Appreciation",
      "tier": "premium",
      "path": "/templates/signup/spring/teacher-appreciation.png"
    },
    {
      "name": "Spring Break",
      "tier": "free",
      "path": "/templates/signup/spring/spring-break.png"
    },
    {
      "name": "Spring Picnic",
      "tier": "free",
      "path": "/templates/signup/spring/spring-picnic.png"
    },
    {
      "name": "Field Day",
      "tier": "premium",
      "path": "/templates/signup/spring/field-day.png"
    },
    {
      "name": "Spring Garden",
      "tier": "free",
      "path": "/templates/signup/spring/spring-garden.png"
    }
  ],
  "Summer": [
    {
      "name": "Summer Camp",
      "tier": "free",
      "path": "/templates/signup/summer/summer-camp.png"
    },
    {
      "name": "Beach Day",
      "tier": "free",
      "path": "/templates/signup/summer/beach-day.png"
    },
    {
      "name": "Vacation Vibes",
      "tier": "premium",
      "path": "/templates/signup/summer/vacation-vibes.png"
    },
    {
      "name": "Family Reunion",
      "tier": "free",
      "path": "/templates/signup/summer/family-reunion.png"
    },
    {
      "name": "Picnic Fun",
      "tier": "free",
      "path": "/templates/signup/summer/picnic-fun.png"
    },
    {
      "name": "Fourth of July",
      "tier": "premium",
      "path": "/templates/signup/summer/fourth-of-july.png"
    },
    {
      "name": "Ice Cream Social",
      "tier": "free",
      "path": "/templates/signup/summer/ice-cream-social.png"
    },
    {
      "name": "Summer BBQ",
      "tier": "free",
      "path": "/templates/signup/summer/summer-bbq.png"
    },
    {
      "name": "Lemonade Stand",
      "tier": "free",
      "path": "/templates/signup/summer/lemonade-stand.png"
    },
    {
      "name": "Pool Party",
      "tier": "premium",
      "path": "/templates/signup/summer/pool-party.png"
    }
  ],
  "School & Education": [
    {
      "name": "Teacher Appreciation",
      "tier": "premium",
      "path": "/templates/signup/school-and-education/teacher-appreciation.png"
    },
    {
      "name": "Book Fair",
      "tier": "free",
      "path": "/templates/signup/school-and-education/book-fair.png"
    },
    {
      "name": "Field Trip",
      "tier": "free",
      "path": "/templates/signup/school-and-education/field-trip.png"
    },
    {
      "name": "Back to School",
      "tier": "free",
      "path": "/templates/signup/school-and-education/back-to-school.png"
    },
    {
      "name": "Class Party",
      "tier": "free",
      "path": "/templates/signup/school-and-education/class-party.png"
    },
    {
      "name": "Open House",
      "tier": "free",
      "path": "/templates/signup/school-and-education/open-house.png"
    },
    {
      "name": "Parent Teacher Conference",
      "tier": "free",
      "path": "/templates/signup/school-and-education/parent-teacher-conference.png"
    },
    {
      "name": "Classroom Helpers",
      "tier": "free",
      "path": "/templates/signup/school-and-education/classroom-helpers.png"
    },
    {
      "name": "School Spirit",
      "tier": "premium",
      "path": "/templates/signup/school-and-education/school-spirit.png"
    },
    {
      "name": "Student Volunteers",
      "tier": "free",
      "path": "/templates/signup/school-and-education/student-volunteers.png"
    }
  ],
  "Church & Community": [
    {
      "name": "Service Project",
      "tier": "premium",
      "path": "/templates/signup/church-and-community/service-project.png"
    },
    {
      "name": "Community Picnic",
      "tier": "free",
      "path": "/templates/signup/church-and-community/community-picnic.png"
    },
    {
      "name": "Bible Study",
      "tier": "free",
      "path": "/templates/signup/church-and-community/bible-study.png"
    },
    {
      "name": "Mission Trip",
      "tier": "premium",
      "path": "/templates/signup/church-and-community/mission-trip.png"
    },
    {
      "name": "Church Gathering",
      "tier": "free",
      "path": "/templates/signup/church-and-community/church-gathering.png"
    },
    {
      "name": "Volunteer Sign-Up",
      "tier": "free",
      "path": "/templates/signup/church-and-community/volunteer-sign-up.png"
    },
    {
      "name": "Worship Team",
      "tier": "premium",
      "path": "/templates/signup/church-and-community/worship-team.png"
    },
    {
      "name": "Sunday School",
      "tier": "free",
      "path": "/templates/signup/church-and-community/sunday-school.png"
    },
    {
      "name": "Fundraiser",
      "tier": "free",
      "path": "/templates/signup/church-and-community/fundraiser.png"
    },
    {
      "name": "Food Drive",
      "tier": "free",
      "path": "/templates/signup/church-and-community/food-drive.png"
    }
  ],
  "Sports & Recreation": [
    {
      "name": "Swim Team",
      "tier": "premium",
      "path": "/templates/signup/sports-and-recreation/swim-team.png"
    },
    {
      "name": "Cheer Squad",
      "tier": "premium",
      "path": "/templates/signup/sports-and-recreation/cheer-squad.png"
    },
    {
      "name": "Track Meet",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/track-meet.png"
    },
    {
      "name": "Baseball Team",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/baseball-team.png"
    },
    {
      "name": "Sports Banquet",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/sports-banquet.png"
    },
    {
      "name": "Gymnastics",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/gymnastics.png"
    },
    {
      "name": "Fitness Class",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/fitness-class.png"
    },
    {
      "name": "Soccer Game",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/soccer-game.png"
    },
    {
      "name": "Basketball Practice",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/basketball-practice.png"
    },
    {
      "name": "Golf Tournament",
      "tier": "premium",
      "path": "/templates/signup/sports-and-recreation/golf-tournament.png"
    }
  ],
  "Fundraising, Food, & Events": [
    {
      "name": "Car Wash",
      "tier": "free",
      "path": "/templates/signup/fundraising-food/car-wash.png"
    },
    {
      "name": "Bake Sale",
      "tier": "free",
      "path": "/templates/signup/fundraising-food/bake-sale.png"
    },
    {
      "name": "Charity Gala",
      "tier": "premium",
      "path": "/templates/signup/fundraising-food/charity-gala.png"
    },
    {
      "name": "Restaurant Night",
      "tier": "premium",
      "path": "/templates/signup/fundraising-food/restaurant-night.png"
    },
    {
      "name": "Food Pantry",
      "tier": "free",
      "path": "/templates/signup/fundraising-food/food-pantry.png"
    },
    {
      "name": "Auction Event",
      "tier": "premium",
      "path": "/templates/signup/fundraising-food/auction-event.png"
    },
    {
      "name": "Donation Drive",
      "tier": "free",
      "path": "/templates/signup/fundraising-food/donation-drive.png"
    },
    {
      "name": "Vendor Fair",
      "tier": "premium",
      "path": "/templates/signup/fundraising-food/vendor-fair.png"
    },
    {
      "name": "Raffle",
      "tier": "premium",
      "path": "/templates/signup/fundraising-food/raffle.png"
    },
    {
      "name": "Potluck Dinner",
      "tier": "free",
      "path": "/templates/signup/fundraising-food/potluck-dinner.png"
    }
  ],
  "Family & Personal": [
    {
      "name": "Anniversary Celebration",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/anniversary-celebration.png"
    },
    {
      "name": "Family Event",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/family-event.png"
    },
    {
      "name": "Housewarming",
      "tier": "free",
      "path": "/templates/signup/family-and-personal/housewarming.png"
    },
    {
      "name": "Birthday Party",
      "tier": "free",
      "path": "/templates/signup/family-and-personal/birthday-party.png"
    },
    {
      "name": "Block Party",
      "tier": "free",
      "path": "/templates/signup/family-and-personal/block-party.png"
    },
    {
      "name": "Wedding",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/wedding.png"
    },
    {
      "name": "Baby Shower",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/baby-shower.png"
    },
    {
      "name": "Game Night",
      "tier": "free",
      "path": "/templates/signup/family-and-personal/game-night.png"
    },
    {
      "name": "Bridal Shower",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/bridal-shower.png"
    },
    {
      "name": "Family Holiday",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/family-holiday.png"
    }
  ],
  "Business & Professional": [
    {
      "name": "Conference Schedule",
      "tier": "premium",
      "path": "/templates/signup/business-and-professional/conference-schedule.png"
    },
    {
      "name": "Client Meeting",
      "tier": "free",
      "path": "/templates/signup/business-and-professional/client-meeting.png"
    },
    {
      "name": "Team Lunch",
      "tier": "free",
      "path": "/templates/signup/business-and-professional/team-lunch.png"
    },
    {
      "name": "Corporate Event",
      "tier": "premium",
      "path": "/templates/signup/business-and-professional/corporate-event.png"
    },
    {
      "name": "Workshop",
      "tier": "free",
      "path": "/templates/signup/business-and-professional/workshop.png"
    },
    {
      "name": "Networking Night",
      "tier": "premium",
      "path": "/templates/signup/business-and-professional/networking-night.png"
    },
    {
      "name": "Professional Gathering",
      "tier": "premium",
      "path": "/templates/signup/business-and-professional/professional-gathering.png"
    },
    {
      "name": "Office Meeting",
      "tier": "free",
      "path": "/templates/signup/business-and-professional/office-meeting.png"
    },
    {
      "name": "Training Session",
      "tier": "free",
      "path": "/templates/signup/business-and-professional/training-session.png"
    }
  ],
  "Other / Special Interest": [
    {
      "name": "Tech Event",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/tech-event.png"
    },
    {
      "name": "Political Campaign",
      "tier": "premium",
      "path": "/templates/signup/other-special-interest/political-campaign.png"
    },
    {
      "name": "Gaming Tournament",
      "tier": "premium",
      "path": "/templates/signup/other-special-interest/gaming-tournament.png"
    },
    {
      "name": "Environment & Cleanup",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/environment-and-cleanup.png"
    },
    {
      "name": "Senior Services",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/senior-services.png"
    },
    {
      "name": "Travel Group",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/travel-group.png"
    },
    {
      "name": "Real Estate Open House",
      "tier": "premium",
      "path": "/templates/signup/other-special-interest/real-estate-open-house.png"
    },
    {
      "name": "Arts & Culture",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/arts-and-culture.png"
    },
    {
      "name": "Pets & Animals",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/pets-and-animals.png"
    }
  ],
  "General": [
    {
      "name": "HOA Meeting",
      "tier": "free",
      "path": "/templates/signup/general/hoa-meeting.png"
    },
    {
      "name": "Ad Hoc Meeting",
      "tier": "premium",
      "path": "/templates/signup/general/ad-hoc-meeting.png"
    },
    {
      "name": "Board Meeting",
      "tier": "free",
      "path": "/templates/signup/general/board-meeting.png"
    },
    {
      "name": "Team Planning Session",
      "tier": "free",
      "path": "/templates/signup/general/team-planning-session.png"
    },
    {
      "name": "Volunteer Orientation",
      "tier": "premium",
      "path": "/templates/signup/general/volunteer-orientation.png"
    },
    {
      "name": "Town Hall Meeting",
      "tier": "free",
      "path": "/templates/signup/general/town-hall-meeting.png"
    },
    {
      "name": "Community Discussion",
      "tier": "free",
      "path": "/templates/signup/general/community-discussion.png"
    },
    {
      "name": "Staff Training",
      "tier": "premium",
      "path": "/templates/signup/general/staff-training.png"
    },
    {
      "name": "Committee Meeting",
      "tier": "free",
      "path": "/templates/signup/general/committee-meeting.png"
    },
    {
      "name": "Monthly Meetup",
      "tier": "free",
      "path": "/templates/signup/general/monthly-meetup.png"
    },
    {
      "name": "Project Kickoff",
      "tier": "premium",
      "path": "/templates/signup/general/project-kickoff.png"
    },
    {
      "name": "Workshop Registration",
      "tier": "free",
      "path": "/templates/signup/general/workshop-registration.png"
    }
  ]
}
;