// Auto-generated by scripts/generate-signup-templates-openrouter.mjs
export type SignupTemplateItem = { name: string; tier: 'free'|'premium'; path: string };
export type SignupTemplateManifest = Record<string, SignupTemplateItem[]>;
export const SIGNUP_TEMPLATES: SignupTemplateManifest = 
{
  "Fall & Seasonal": [
    {
      "name": "Apple Picking",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/apple-picking.png"
    },
    {
      "name": "Fall Scene",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/fall-scene.png"
    },
    {
      "name": "Fall Fun 2",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-fun-2.png"
    },
    {
      "name": "Harvest Table",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/harvest-table.png"
    },
    {
      "name": "Pumpkin Patch",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/pumpkin-patch.png"
    },
    {
      "name": "Fall Forest",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-forest.png"
    },
    {
      "name": "Fall Food Drive",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-food-drive.png"
    },
    {
      "name": "Fall Gathering",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/fall-gathering.png"
    },
    {
      "name": "Corn Maze",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/corn-maze.png"
    },
    {
      "name": "Autumn Blessings",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/autumn-blessings.png"
    },
    {
      "name": "Thanksgiving Feast",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/thanksgiving-feast.png"
    },
    {
      "name": "Friendsgiving",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/friendsgiving.png"
    },
    {
      "name": "Fall Food",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-food.png"
    },
    {
      "name": "Fall Leaves",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-leaves.png"
    },
    {
      "name": "Fall Y’all",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/fall-y-all.png"
    },
    {
      "name": "Fall Festival",
      "tier": "free",
      "path": "/templates/signup/fall-and-seasonal/fall-festival.png"
    },
    {
      "name": "Fall Pumpkins",
      "tier": "premium",
      "path": "/templates/signup/fall-and-seasonal/fall-pumpkins.png"
    }
  ],
  "Church & Community": [
    {
      "name": "Service Project",
      "tier": "premium",
      "path": "/templates/signup/church-and-community/service-project.png"
    },
    {
      "name": "Community Picnic",
      "tier": "free",
      "path": "/templates/signup/church-and-community/community-picnic.png"
    },
    {
      "name": "Bible Study",
      "tier": "free",
      "path": "/templates/signup/church-and-community/bible-study.png"
    },
    {
      "name": "Mission Trip",
      "tier": "premium",
      "path": "/templates/signup/church-and-community/mission-trip.png"
    },
    {
      "name": "Church Gathering",
      "tier": "free",
      "path": "/templates/signup/church-and-community/church-gathering.png"
    },
    {
      "name": "Volunteer Sign-Up",
      "tier": "free",
      "path": "/templates/signup/church-and-community/volunteer-sign-up.png"
    },
    {
      "name": "Worship Team",
      "tier": "premium",
      "path": "/templates/signup/church-and-community/worship-team.png"
    },
    {
      "name": "Sunday School",
      "tier": "free",
      "path": "/templates/signup/church-and-community/sunday-school.png"
    },
    {
      "name": "Fundraiser",
      "tier": "free",
      "path": "/templates/signup/church-and-community/fundraiser.png"
    },
    {
      "name": "Food Drive",
      "tier": "free",
      "path": "/templates/signup/church-and-community/food-drive.png"
    }
  ],
  "Sports & Recreation": [
    {
      "name": "Swim Team",
      "tier": "premium",
      "path": "/templates/signup/sports-and-recreation/swim-team.png"
    },
    {
      "name": "Cheer Squad",
      "tier": "premium",
      "path": "/templates/signup/sports-and-recreation/cheer-squad.png"
    },
    {
      "name": "Track Meet",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/track-meet.png"
    },
    {
      "name": "Baseball Team",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/baseball-team.png"
    },
    {
      "name": "Sports Banquet",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/sports-banquet.png"
    },
    {
      "name": "Gymnastics",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/gymnastics.png"
    },
    {
      "name": "Fitness Class",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/fitness-class.png"
    },
    {
      "name": "Soccer Game",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/soccer-game.png"
    },
    {
      "name": "Basketball Practice",
      "tier": "free",
      "path": "/templates/signup/sports-and-recreation/basketball-practice.png"
    },
    {
      "name": "Golf Tournament",
      "tier": "premium",
      "path": "/templates/signup/sports-and-recreation/golf-tournament.png"
    }
  ],
  "Fundraising & Food": [
    {
      "name": "Car Wash",
      "tier": "free",
      "path": "/templates/signup/fundraising-and-food/car-wash.png"
    },
    {
      "name": "Bake Sale",
      "tier": "free",
      "path": "/templates/signup/fundraising-and-food/bake-sale.png"
    },
    {
      "name": "Charity Gala",
      "tier": "premium",
      "path": "/templates/signup/fundraising-and-food/charity-gala.png"
    },
    {
      "name": "Restaurant Night",
      "tier": "premium",
      "path": "/templates/signup/fundraising-and-food/restaurant-night.png"
    },
    {
      "name": "Food Pantry",
      "tier": "free",
      "path": "/templates/signup/fundraising-and-food/food-pantry.png"
    },
    {
      "name": "Auction Event",
      "tier": "premium",
      "path": "/templates/signup/fundraising-and-food/auction-event.png"
    },
    {
      "name": "Donation Drive",
      "tier": "free",
      "path": "/templates/signup/fundraising-and-food/donation-drive.png"
    },
    {
      "name": "Vendor Fair",
      "tier": "premium",
      "path": "/templates/signup/fundraising-and-food/vendor-fair.png"
    },
    {
      "name": "Raffle",
      "tier": "premium",
      "path": "/templates/signup/fundraising-and-food/raffle.png"
    },
    {
      "name": "Potluck Dinner",
      "tier": "free",
      "path": "/templates/signup/fundraising-and-food/potluck-dinner.png"
    }
  ],
  "Family & Personal": [
    {
      "name": "Anniversary Celebration",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/anniversary-celebration.png"
    },
    {
      "name": "Family Event",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/family-event.png"
    },
    {
      "name": "Housewarming",
      "tier": "free",
      "path": "/templates/signup/family-and-personal/housewarming.png"
    },
    {
      "name": "Birthday Party",
      "tier": "free",
      "path": "/templates/signup/family-and-personal/birthday-party.png"
    },
    {
      "name": "Block Party",
      "tier": "free",
      "path": "/templates/signup/family-and-personal/block-party.png"
    },
    {
      "name": "Wedding",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/wedding.png"
    },
    {
      "name": "Baby Shower",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/baby-shower.png"
    },
    {
      "name": "Game Night",
      "tier": "free",
      "path": "/templates/signup/family-and-personal/game-night.png"
    },
    {
      "name": "Bridal Shower",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/bridal-shower.png"
    },
    {
      "name": "Family Holiday",
      "tier": "premium",
      "path": "/templates/signup/family-and-personal/family-holiday.png"
    }
  ],
  "Business & Professional": [
    {
      "name": "Conference Schedule",
      "tier": "premium",
      "path": "/templates/signup/business-and-professional/conference-schedule.png"
    },
    {
      "name": "Client Meeting",
      "tier": "free",
      "path": "/templates/signup/business-and-professional/client-meeting.png"
    },
    {
      "name": "Team Lunch",
      "tier": "free",
      "path": "/templates/signup/business-and-professional/team-lunch.png"
    },
    {
      "name": "Corporate Event",
      "tier": "premium",
      "path": "/templates/signup/business-and-professional/corporate-event.png"
    },
    {
      "name": "Workshop",
      "tier": "free",
      "path": "/templates/signup/business-and-professional/workshop.png"
    },
    {
      "name": "Networking Night",
      "tier": "premium",
      "path": "/templates/signup/business-and-professional/networking-night.png"
    },
    {
      "name": "Professional Gathering",
      "tier": "premium",
      "path": "/templates/signup/business-and-professional/professional-gathering.png"
    },
    {
      "name": "Office Meeting",
      "tier": "free",
      "path": "/templates/signup/business-and-professional/office-meeting.png"
    },
    {
      "name": "Training Session",
      "tier": "free",
      "path": "/templates/signup/business-and-professional/training-session.png"
    }
  ],
  "Other / Special Interest": [
    {
      "name": "Tech Event",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/tech-event.png"
    },
    {
      "name": "Political Campaign",
      "tier": "premium",
      "path": "/templates/signup/other-special-interest/political-campaign.png"
    },
    {
      "name": "Gaming Tournament",
      "tier": "premium",
      "path": "/templates/signup/other-special-interest/gaming-tournament.png"
    },
    {
      "name": "Environment & Cleanup",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/environment-and-cleanup.png"
    },
    {
      "name": "Senior Services",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/senior-services.png"
    },
    {
      "name": "Travel Group",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/travel-group.png"
    },
    {
      "name": "Real Estate Open House",
      "tier": "premium",
      "path": "/templates/signup/other-special-interest/real-estate-open-house.png"
    },
    {
      "name": "Arts & Culture",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/arts-and-culture.png"
    },
    {
      "name": "Pets & Animals",
      "tier": "free",
      "path": "/templates/signup/other-special-interest/pets-and-animals.png"
    }
  ],
  "General": [
    {
      "name": "HOA Meeting",
      "tier": "free",
      "path": "/templates/signup/general/hoa-meeting.png"
    },
    {
      "name": "Ad Hoc Meeting",
      "tier": "premium",
      "path": "/templates/signup/general/ad-hoc-meeting.png"
    },
    {
      "name": "Board Meeting",
      "tier": "free",
      "path": "/templates/signup/general/board-meeting.png"
    },
    {
      "name": "Team Planning Session",
      "tier": "free",
      "path": "/templates/signup/general/team-planning-session.png"
    },
    {
      "name": "Volunteer Orientation",
      "tier": "premium",
      "path": "/templates/signup/general/volunteer-orientation.png"
    },
    {
      "name": "Town Hall Meeting",
      "tier": "free",
      "path": "/templates/signup/general/town-hall-meeting.png"
    },
    {
      "name": "Community Discussion",
      "tier": "free",
      "path": "/templates/signup/general/community-discussion.png"
    },
    {
      "name": "Staff Training",
      "tier": "premium",
      "path": "/templates/signup/general/staff-training.png"
    },
    {
      "name": "Committee Meeting",
      "tier": "free",
      "path": "/templates/signup/general/committee-meeting.png"
    },
    {
      "name": "Monthly Meetup",
      "tier": "free",
      "path": "/templates/signup/general/monthly-meetup.png"
    },
    {
      "name": "Project Kickoff",
      "tier": "premium",
      "path": "/templates/signup/general/project-kickoff.png"
    },
    {
      "name": "Workshop Registration",
      "tier": "free",
      "path": "/templates/signup/general/workshop-registration.png"
    }
  ],
  "Parties & Events": [
    {
      "name": "Birthday Party",
      "tier": "free",
      "path": "/templates/signup/parties-and-events/birthday-party.png"
    },
    {
      "name": "Wedding",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/wedding.png"
    },
    {
      "name": "Baby Shower",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/baby-shower.png"
    },
    {
      "name": "Game Night",
      "tier": "free",
      "path": "/templates/signup/parties-and-events/game-night.png"
    },
    {
      "name": "Bridal Shower",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/bridal-shower.png"
    },
    {
      "name": "Family Holiday",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/family-holiday.png"
    },
    {
      "name": "Holiday Party",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/holiday-party.png"
    },
    {
      "name": "Graduation Party",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/graduation-party.png"
    },
    {
      "name": "Retirement Party",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/retirement-party.png"
    },
    {
      "name": "Engagement Party",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/engagement-party.png"
    },
    {
      "name": "Baby Shower",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/baby-shower.png"
    },
    {
      "name": "Game Night",
      "tier": "free",
      "path": "/templates/signup/parties-and-events/game-night.png"
    },
    {
      "name": "Bridal Shower",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/bridal-shower.png"
    },
    {
      "name": "Family Holiday",
      "tier": "premium",
      "path": "/templates/signup/parties-and-events/family-holiday.png"
    }
  ],
  "Health & Fitness": [
    {
      "name": "Fitness Class",
      "tier": "free",
      "path": "/templates/signup/health-and-fitness/fitness-class.png"
    },
    {
      "name": "Yoga Class",
      "tier": "premium",
      "path": "/templates/signup/health-and-fitness/yoga-class.png"
    },
    {
      "name": "Pilates Class",
      "tier": "premium",
      "path": "/templates/signup/health-and-fitness/pilates-class.png"
    },
    {
      "name": "Spin Class",
      "tier": "premium",
      "path": "/templates/signup/health-and-fitness/spin-class.png"
    },
    {
      "name": "Zumba Class",
      "tier": "premium",
      "path": "/templates/signup/health-and-fitness/zumba-class.png"
    },
    {
      "name": "Bootcamp Class",
      "tier": "premium",
      "path": "/templates/signup/health-and-fitness/bootcamp-class.png"
    },
    {
      "name": "Dance Class",
      "tier": "premium",
      "path": "/templates/signup/health-and-fitness/dance-class.png"
    },
    {
      "name": "Morning Run",
      "tier": "free",
      "path": "/templates/signup/health-and-fitness/morning-run.png"
    },
    {
      "name": "Cycling Club",
      "tier": "free",
      "path": "/templates/signup/health-and-fitness/cycling-club.png"
    },
    {
      "name": "CrossFit Session",
      "tier": "premium",
      "path": "/templates/signup/health-and-fitness/crossfit-session.png"
    },
    {
      "name": "Martial Arts Class",
      "tier": "premium",
      "path": "/templates/signup/health-and-fitness/martial-arts-class.png"
    },
    {
      "name": "Boxing Class",
      "tier": "premium",
      "path": "/templates/signup/health-and-fitness/boxing-class.png"
    },
    {
      "name": "Swimming Lessons",
      "tier": "free",
      "path": "/templates/signup/health-and-fitness/swimming-lessons.png"
    },
    {
      "name": "Tennis Club",
      "tier": "free",
      "path": "/templates/signup/health-and-fitness/tennis-club.png"
    },
    {
      "name": "Basketball League",
      "tier": "free",
      "path": "/templates/signup/health-and-fitness/basketball-league.png"
    },
    {
      "name": "Volleyball League",
      "tier": "free",
      "path": "/templates/signup/health-and-fitness/volleyball-league.png"
    },
    {
      "name": "Wellness Workshop",
      "tier": "premium",
      "path": "/templates/signup/health-and-fitness/wellness-workshop.png"
    }
  ],
  "Clubs & Groups": [
    {
      "name": "Book Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/book-club.png"
    },
    {
      "name": "Running Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/running-club.png"
    },
    {
      "name": "Bike Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/bike-club.png"
    },
    {
      "name": "Hiking Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/hiking-club.png"
    },
    {
      "name": "Rock Climbing Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/rock-climbing-club.png"
    },
    {
      "name": "Swim Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/swim-club.png"
    },
    {
      "name": "Soccer Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/soccer-club.png"
    },
    {
      "name": "Baseball Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/baseball-club.png"
    },
    {
      "name": "Basketball Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/basketball-club.png"
    },
    {
      "name": "Football Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/football-club.png"
    },
    {
      "name": "Tennis Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/tennis-club.png"
    },
    {
      "name": "Volleyball Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/volleyball-club.png"
    },
    {
      "name": "Golf Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/golf-club.png"
    },
    {
      "name": "Cheerleading Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/cheerleading-club.png"
    },
    {
      "name": "Dance Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/dance-club.png"
    },
    {
      "name": "Cheerleading Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/cheerleading-club.png"
    },
    {
      "name": "Dance Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/dance-club.png"
    },
    {
      "name": "Cheerleading Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/cheerleading-club.png"
    },
    {
      "name": "Dance Club",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/dance-club.png"
    },
    {
      "name": "Drive Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/drive-group.png"
    },
    {
      "name": "Fisherman Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/fisherman-group.png"
    },
    {
      "name": "Horseback Riding Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/horseback-riding-group.png"
    },
    {
      "name": "Bird Watching Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/bird-watching-group.png"
    },
    {
      "name": "Gardening Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/gardening-group.png"
    },
    {
      "name": "Reading Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/reading-group.png"
    },
    {
      "name": "Writing Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/writing-group.png"
    },
    {
      "name": "Cooking Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/cooking-group.png"
    },
    {
      "name": "Baking Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/baking-group.png"
    },
    {
      "name": "Painting Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/painting-group.png"
    },
    {
      "name": "Pottery Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/pottery-group.png"
    },
    {
      "name": "Knitting Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/knitting-group.png"
    },
    {
      "name": "Crocheting Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/crocheting-group.png"
    },
    {
      "name": "Sewing Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/sewing-group.png"
    },
    {
      "name": "Quilting Group",
      "tier": "free",
      "path": "/templates/signup/clubs-and-groups/quilting-group.png"
    }
  ]
}
;